create table demand_detail
(
    number          text null,
    region          text null,
    industry        text null,
    description     text null,
    stage           text null,
    tech_categories text null,
    tech            text null,
    tech_overview   text null,
    source          text null,
    demand_id       int auto_increment
        primary key
)
    charset = utf8;

INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('PP001', '巴西', '造纸', '行业需要利用其他可再生的原材料来代替木材，减少对森林资源的依赖，并且降低生产成本', '源头控制', '资源高效利用', '原料多样化技术', '通过采用多样化的原料，如竹子、稻草、秸秆等非木材原料，降低木材消耗和环境影响', '王英斌.巴西制浆造纸行业力推ESG管理[J].纸和造纸,2023,42(01):68.', 1);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('PP002', '巴西', '造纸', '巴西造纸行业需要采用生物质发电、生物燃料和生物质热能利用等技术，将生产废弃物和废水等资源转化为能源，降低能源消耗和碳排放', '生产过程', '资源高效利用', '生物质能源技术', '该技术包括生物质发电、生物燃料和生物质热能利用等，旨在降低造纸行业的能源消耗和碳排放', 'BRIC Countries (Brazil, Russia, India, China) Paper and Paperboard Market Summary, Competitive Analysis and Forecast, 2017-2026
https://www.researchandmarkets.com/reports/5665478/bric-countries-brazil-russia-india-china#tag-pos-1', 2);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('PP003', '巴西', '造纸', '需要更加高效的生产工艺和设备来减少能源消耗', '生产过程', '资源高效利用；资源化控制', '能源节约和利用技术', '采用高效节能设备和系统，优化能源利用效率，同时回收废热和废液，降低生产成本和环境影响', 'Paper and Paperboard Retail BRIC (Brazil, Russia, India, China) Industry Guide - Market Summary, Competitive Analysis and Forecast to 2025
https://www.researchandmarkets.com/reports/5463674/paper-and-paperboard-retail-bric-brazil#tag-pos-2', 3);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('PP004', '巴西', '造纸', '采用可再生能源，例如风能、太阳能、生物质和水力发电等。这些能源可以替代传统的化石燃料，减少碳排放，提高能源效率', '生产过程', '资源高效利用', '可再生能源利用技术', '采用可再生能源，例如风能、太阳能、生物质和水力发电等。这些能源可以替代传统的化石燃料，减少碳排放，提高能源效率', '巴西纸浆造纸行业的技术演变https://online.fliphtml5.com/rhwu/zbrk/#p=1', 4);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('PP005', '巴西', '造纸', '生产过程清洁化技术是巴西造纸行业当前重要的技术需求，旨在提高生产效率和产品质量的同时减少环境污染和废弃物产生。', '生产过程', '能源节约及清洁化', '生产过程清洁化技术', '采用清洁生产技术，优化原料选择和加工过程，减少污染物排放和废弃物产生', '巴西纸浆造纸行业的技术演变https://online.fliphtml5.com/rhwu/zbrk/#p=1', 5);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('PP006', '巴西', '造纸', '采用可再生能源、低碳化生产工艺和产品等技术，降低碳排放和环境影响', '末端控制', '温室气体减排', '低碳化技术', '采用可再生能源、低碳化生产工艺和产品等技术，降低碳排放和环境影响', 'Brazil Paper and Pulp Market: Prospects, Trends Analysis, Market Size and Forecasts up to 2028
https://www.researchandmarkets.com/reports/5713828/brazil-paper-and-pulp-market-prospects-trends#tag-pos-3', 6);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('PP007', '巴西', '造纸', '包括采用低氮氧化物燃烧技术、气体燃烧余热回收技术、燃料多样化等措施，降低工业燃料的污染排放', '末端控制', '大气污染防治', '环保清洁燃料技术', '包括采用低氮氧化物燃烧技术、气体燃烧余热回收技术、燃料多样化等措施，降低工业燃料的污染排放', '2022年报https://iba.org/datafiles/publicacoes/relatorios/relatorio-anual-iba2022-compactado.pdf', 7);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('PP008', '巴西', '造纸', '采用烟气脱硫技术，如湿法脱硫、半干法脱硫等，减少二氧化硫等有害气体的排放。', '末端控制', '大气污染防治', '脱硫技术', '采用烟气脱硫技术，如湿法脱硫、半干法脱硫等，减少二氧化硫等有害气体的排放。', '2022年报https://iba.org/datafiles/publicacoes/relatorios/relatorio-anual-iba2022-compactado.pdf', 8);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('PP009', '巴西', '造纸', '该技术包括植树、育苗、森林保护和再生等，旨在保护环境和森林资源，确保可持续发展', '源头控制', '资源化控制', '可持续森林管理技术', '该技术包括植树、育苗、森林保护和再生等，旨在保护环境和森林资源，确保可持续发展', '2022年报https://iba.org/datafiles/publicacoes/relatorios/relatorio-anual-iba2022-compactado.pdf', 9);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('TE001', '巴西', '纺织', '巴西纺织工业联合会（ABIT）指出，纺织业是一个高度污染的行业，因此需要采用更环保的染色技术。', '生产过程', '能源节约及清洁化', '环保染色技术', '采用氧化还原染色剂、离子液体染色剂等环保染色技术，可以降低水资源的使用和化学污染物的排放。', '巴西纺织服装行业协会https://www.abit.org.br/noticias', 10);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('TE002', '巴西', '纺织', '巴西政府的能源和矿产资源部（MME）指出，纺织业是一个能源消耗大户，因此需要采用更节能的生产技术。', '生产过程', '能源节约及清洁化', '节能技术', '采用高效节能的纺纱机、织机等设备，可以降低能源消耗和碳排放。', '巴西纺织品产业发展迅速，成为全球重要的纺织品制造中心https://www.wyapsw.com/info/d3956164g.html', 11);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('TE003', '巴西', '纺织', '巴西纺织行业需要开发和采用先进的水污染控制技术，同时，该行业需要关注水资源的可持续利用问题，并致力于减少水的浪费和污染。', '末端控制', '水污染防治', '水污染控制技术', '废水回收和重复利用、化学物质的最小化使用、水质监测和管理等方面的技术。', 'Textile Manufacturing Market in Brazil 2022-2026
https://www.researchandmarkets.com/reports/5576344/textile-manufacturing-market-in-brazil-2022-2026#cat-pos-3', 12);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('TE004', '巴西', '纺织', '巴西纺织行业需要开发和采用先进的空气污染控制技术。该行业需要关注空气质量的问题，并致力于减少空气污染物的排放。', '末端控制', '大气污染控制', '空气污染控制技术需求', '废气处理、烟气净化和粉尘控制', 'https://www.cepea.esalq.usp.br/', 13);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('PP001', '马来西亚', '造纸', '当前全球环境保护意识日益高涨，马来西亚造纸行业也需要采取更加环保可持续的生产方式。其中，绿色制浆与纸张生产技术成为了一种非常重要的技术需求。', '源头控制', '资源高效利用', '绿色制浆与纸张生产技术', '绿色制浆与纸张生产技术可以将废旧纸张回收再利用，并采用无氯漂白等环保工艺，降低污染排放，达到节能减排的目的。', '马来西亚化学工业委员会网站http://www.mpma.org.my/
马来西亚科技创新局网站https://www.mosti.gov.my/
马来西亚环保署网站http://www.doe.gov.my/', 14);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('PP002', '马来西亚', '造纸', '随着信息技术的快速发展，数字化制造技术已经成为了全球制造业的一个重要趋势。马来西亚造纸行业也需要逐步实现数字化制造技术的应用', '生产过程', '能源清洁化', '数字化制造技术', '通过引入人工智能、云计算等先进技术，实现生产流程自动化，并提高产品质量和生产效率。', '马来西亚国家发展部门网站https://www.mida.gov.my/', 15);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('PP003', '马来西亚', '造纸', '随着全球非化石能源的推广和普及，马来西亚造纸企业需要探索利用可再生能源技术', '生产过程', '能源清洁化', '可再生能源技术', '太阳能、风能等作为生产能源，减少对环境的影响，同时提高企业的经济效益。', '马来西亚能源委员会网站http://www.seda.gov.my/', 16);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('PP004', '马来西亚', '造纸', '马来西亚造纸行业需要引入智能监测和控制技术，通过采用传感器、物联网等先进技术监测生产过程中的数据，并对生产过程进行实时调整和优化，提高生产效率和产品质量，同时降低人力成本。', '生产过程', '资源化控制', '智能监测和控制技术', '马来西亚造纸行业需要引入智能监测和控制技术，通过采用传感器、物联网等先进技术监测生产过程中的数据，并对生产过程进行实时调整和优化，提高生产效率和产品质量，同时降低人力成本。', '马来西亚智能科技与创新局网站https://www.mimos.my/', 17);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('PP005', '马来西亚', '造纸', '为了减少温室气体的排放，马来西亚需要采用碳捕捉和储存技术。这项技术可以将化石燃料等排放源处排放的二氧化碳进行捕捉并进行填埋或注入地下储层，从而实现大规模减排。', '末端控制', '温室气体减排', '碳捕捉和储存技术', '为了减少温室气体的排放，马来西亚需要采用碳捕捉和储存技术。这项技术可以将化石燃料等排放源处排放的二氧化碳进行捕捉并进行填埋或注入地下储层，从而实现大规模减排。', 'Pulp-and-paper industry in Malaysia: Business Report 2023
https://www.researchandmarkets.com/reports/3643189/pulp-and-paper-industry-in-malaysia-business#tag-pos-1', 18);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('TE001', '马来西亚', '纺织', '马来西亚纺织行业需要采用更环保的加工技术，减少对环境的污染。例如，采用低污染染料和化学品、水循环系统等技术。', '生产过程', '水污染纺织', '纺织品绿色加工技术', '马来西亚纺织行业需要采用更环保的加工技术，减少对环境的污染。例如，采用低污染染料和化学品、水循环系统等技术。', 'Textile Manufacturing Market in Malaysia 2022-2026
https://www.researchandmarkets.com/reports/5561299/textile-manufacturing-market-in-malaysia-2022-2026#cat-pos-2', 19);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('TE002', '马来西亚', '纺织', '随着人工成本的上升和生产效率的需求，马来西亚纺织行业需要引入智能化的生产技术，例如自动化机器人、智能传感器等。', '生产过程', '资源化控制', '智能化纺织生产技术', '随着人工成本的上升和生产效率的需求，马来西亚纺织行业需要引入智能化的生产技术，例如自动化机器人、智能传感器等。', 'Malaysia Textile Manufacturing Market - Growth, Trends, COVID-19 Impact, and Forecasts (2023-2028)
https://www.researchandmarkets.com/reports/5572658/malaysia-textile-manufacturing-market-growth#cat-pos-1', 20);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('TE003', '马来西亚', '纺织', '随着科技的发展和需求的不断变化，马来西亚纺织行业需要生产更高品质、更高性能的纤维材料，例如碳纤维、玻璃纤维等。', '源头控制', '资源高效利用', '高性能纤维制造技术', '随着科技的发展和需求的不断变化，马来西亚纺织行业需要生产更高品质、更高性能的纤维材料，例如碳纤维、玻璃纤维等。', 'Prospects for the Textile and Clothing Industry in Malaysia, 2019
https://www.researchandmarkets.com/reports/4753341/prospects-for-the-textile-and-clothing-industry#cat-pos-3', 21);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('TE004', '马来西亚', '纺织', '马来西亚纺织行业需要引入更智能化的印染技术，例如数字化印花、数码印染、热转印等。', '生产过程', '资源化控制', '纺织品智能化印染技术', '马来西亚纺织行业需要引入更智能化的印染技术，例如数字化印花、数码印染、热转印等。', 'Textile Manufacturing Market in Malaysia 2022-2026
https://www.researchandmarkets.com/reports/5561299/textile-manufacturing-market-in-malaysia-2022-2026#cat-pos-2', 22);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('TE005', '马来西亚', '纺织', '马来西亚纺织行业需要引入智能化监测技术，以实现生产过程的自动化控制和数据分析。例如，纺织品质量在线检测、生产能耗监测等。', '生产过程', '资源化控制', '纺织品生产过程的智能监测技术', '马来西亚纺织行业需要引入智能化监测技术，以实现生产过程的自动化控制和数据分析。例如，纺织品质量在线检测、生产能耗监测等。', 'Textile Manufacturing Market in Malaysia 2022-2026
https://www.researchandmarkets.com/reports/5561299/textile-manufacturing-market-in-malaysia-2022-2026#cat-pos-2', 23);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('PP001', '南非', '造纸', '南非造纸行业需要采用更环保的制浆技术，减少对环境的影响。例如，采用纸浆再生技术、生物质能源等技术。', '源头控制', '资源高效利用', '绿色制浆技术', '南非造纸行业需要采用更环保的制浆技术，减少对环境的影响。例如，采用纸浆再生技术、生物质能源等技术。', 'The Manufacture of Paper, Pulp and Paper Products in South Africa 2022
https://www.researchandmarkets.com/reports/5624996/the-manufacture-of-paper-pulp-and-paper#tag-pos-1', 25);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('PP002', '南非', '造纸', '南非造纸行业需要引入数字化生产技术，例如自动化控制系统、数据分析等，提高生产效率和质量。', '生产过程', '资源化控制', '数字化生产技术', '南非造纸行业需要引入数字化生产技术，例如自动化控制系统、数据分析等，提高生产效率和质量。', 'The Manufacture of Paper, Pulp and Paper Products in South Africa 2022
https://www.researchandmarkets.com/reports/5624996/the-manufacture-of-paper-pulp-and-paper#tag-pos-1', 26);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('PP003', '南非', '造纸', '南非造纸行业需要引入更节能减排的技术，例如回收利用废纸、降低生产过程中的二氧化碳排放等。', '末端控制', '温室气体减排', '节能减排技术', '南非造纸行业需要引入更节能减排的技术，例如回收利用废纸、降低生产过程中的二氧化碳排放等。', 'The Manufacture of Paper and Related Products in South Africa 2020
https://www.researchandmarkets.com/reports/5009179/the-manufacture-of-paper-and-related-products-in#tag-pos-2', 27);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('PP004', '南非', '造纸', '南非造纸行业需要开发生物基纸制造技术，以降低对传统纸浆的依赖，并实现可持续发展。例如，采用竹材、麻杆等天然纤维材料生产纸张。', '源头控制', '能源节约及清洁化', '生物基纸制造技术', '南非造纸行业需要开发生物基纸制造技术，以降低对传统纸浆的依赖，并实现可持续发展。例如，采用竹材、麻杆等天然纤维材料生产纸张。', 'The Manufacture of Paper and Related Products in South Africa 2020
https://www.researchandmarkets.com/reports/5009179/the-manufacture-of-paper-and-related-products-in#tag-pos-2', 28);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('PP005', '南非', '造纸', '南非造纸行业需要引入更智能化的包装技术，例如智能标签、智能包装等，以提高包装的安全性和可靠性。', '生产过程', '资源高效利用', '智能化包装技术', '南非造纸行业需要引入更智能化的包装技术，例如智能标签、智能包装等，以提高包装的安全性和可靠性。', 'The Manufacture of Paper and Related Products in South Africa 2020
https://www.researchandmarkets.com/reports/5009179/the-manufacture-of-paper-and-related-products-in#tag-pos-2', 29);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('TE001', '南非', '纺织', '南非纺织行业需要投资智能化供应链管理技术，以提高生产和交付效率。这需要对供应链流程进行重新设计和投资IT系统。', '源头控制', '资源高效利用', '智能化供应链管理技术', '南非纺织行业需要投资智能化供应链管理技术，以提高生产和交付效率。这需要对供应链流程进行重新设计和投资IT系统。', 'South Africa Nonwoven Fabrics Market Overview, 2027
https://www.researchandmarkets.com/reports/5684727/south-africa-nonwoven-fabrics-market-overview#cat-pos-1', 31);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('TE002', '南非', '纺织', '南非纺织行业需要开发新型纤维材料，以提高产品的质量和性能。这包括研究新型纤维材料的性质和应用。', '源头控制', '资源化控制', '新型纤维材料技术', '南非纺织行业需要开发新型纤维材料，以提高产品的质量和性能。这包括研究新型纤维材料的性质和应用。', 'South Africa Nonwoven Fabrics Market Overview, 2027
https://www.researchandmarkets.com/reports/5684727/south-africa-nonwoven-fabrics-market-overview#cat-pos-1', 32);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('TE003', '南非', '纺织', '南非纺织行业需要采用数字化设计和制造技术，以提高生产效率和降低成本。这需要投资数字化技术和培训员工。', '生产过程', '资源化控制', '数字化设计和制造技术', '南非纺织行业需要采用数字化设计和制造技术，以提高生产效率和降低成本。这需要投资数字化技术和培训员工。', 'The Textile Industry in South Africa 2022
https://www.researchandmarkets.com/reports/5568484/the-textile-industry-in-south-africa-2022#cat-pos-2', 33);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('TE004', '南非', '纺织', '南非纺织行业需要采用先进的染色和印花技术，以提高产品的质量和外观。这包括研究新型染料和印花技术的应用。', '生产过程', '能源节约及清洁化', '染色和印花技术', '南非纺织行业需要采用先进的染色和印花技术，以提高产品的质量和外观。这包括研究新型染料和印花技术的应用。', 'The Textile Industry in South Africa 2022
https://www.researchandmarkets.com/reports/5568484/the-textile-industry-in-south-africa-2022#cat-pos-2', 34);
INSERT INTO demand.demand_detail (number, region, industry, description, stage, tech_categories, tech, tech_overview, source, demand_id) VALUES ('TE005', '南非', '纺织', '采用碳捕捉和碳储存技术，可将二氧化碳气体从排放源捕捉并储存起来，从而减少温室气体排放。', '末端控制', '温室气体减排', '碳捕捉和碳储存技术', '采用碳捕捉和碳储存技术，可将二氧化碳气体从排放源捕捉并储存起来，从而减少温室气体排放。', 'The Textile Industry in South Africa 2022
https://www.researchandmarkets.com/reports/5568484/the-textile-industry-in-south-africa-2022#cat-pos-2', 35);