create table demandeng
(
    region          text null,
    industry        text null,
    description     text null,
    stage           text null,
    tech_categories text null,
    tech            text null,
    tech_overview   text null,
    source          text null,
    number          text null,
    demand_id       int auto_increment
        primary key
)
    charset = utf8;

INSERT INTO demand.demandeng (region, industry, description, stage, tech_categories, tech, tech_overview, source, number, demand_id) VALUES ('Brazil', 'Pulp', 'The paper industry needs to use other renewable raw materials to replace wood, reduce dependence on forest resources and reduce production costs', 'Source control', 'Efficient use of resources', 'Feedstock diversification technology', 'Reduced wood consumption and environmental impact through the use of diverse raw materials such as bamboo, straw, straw and other non-wood materials', 'Wang Yingbin. Brazil''s pulp and paper industry pushes for ESG management[J]. Paper and Paper,2023,42(01):68.', null, 1);
INSERT INTO demand.demandeng (region, industry, description, stage, tech_categories, tech, tech_overview, source, number, demand_id) VALUES ('Brazil', 'Pulp', 'The Brazilian paper industry needs to adopt technologies such as biomass power generation, biofuels and biomass thermal energy use to convert resources such as production waste and wastewater into energy and reduce energy consumption and carbon emissions', 'Production process', 'Efficient use of resources', 'Biomass energy technology', 'The technology includes biomass for power generation, biofuels and biomass for thermal energy, and aims to reduce energy consumption and carbon emissions in the paper industry', 'BRIC Countries (Brazil, Russia, India, China) Paper and Paperboard Market Summary, Competitive Analysis and Forecast, 2017-2026
https://www.researchandmarkets.com/reports/5665478/bric-countries-brazil-russia-india-china#tag-pos-1', null, 2);
INSERT INTO demand.demandeng (region, industry, description, stage, tech_categories, tech, tech_overview, source, number, demand_id) VALUES ('Brazil', 'Pulp', 'More efficient production processes and equipment are needed to reduce energy consumption', 'Production process', 'Biodiversity conservation', 'Energy conservation and utilization technologies', 'Energy efficient equipment and systems are used to optimise energy efficiency, while recycling waste heat and liquids to reduce production costs and environmental impact', 'Paper and Paperboard Retail BRIC (Brazil, Russia, India, China) Industry Guide - Market Summary, Competitive Analysis and Forecast to 2025
https://www.researchandmarkets.com/reports/5463674/paper-and-paperboard-retail-bric-brazil#tag-pos-2', null, 3);
INSERT INTO demand.demandeng (region, industry, description, stage, tech_categories, tech, tech_overview, source, number, demand_id) VALUES ('Brazil', 'Pulp', 'The use of renewable energy sources such as wind, solar, biomass and hydroelectricity. These sources of energy can replace traditional fossil fuels, reduce carbon emissions and improve energy efficiency', 'Production process', 'Efficient use of resources', 'Renewable energy use technologies', 'The use of renewable energy sources such as wind, solar, biomass and hydroelectricity. These sources of energy can replace traditional fossil fuels, reduce carbon emissions and improve energy efficiency', 'Technological evolution of the pulp and paper industry in Brazil https://online.fliphtml5.com/rhwu/zbrk/#p=1', null, 4);
INSERT INTO demand.demandeng (region, industry, description, stage, tech_categories, tech, tech_overview, source, number, demand_id) VALUES ('Brazil', 'Pulp', 'Process clean-up technology is an important current technological need for the Brazilian paper industry, aiming to improve production efficiency and product quality while reducing environmental pollution and waste generation.', 'Production process', 'Energy saving and clean energy', 'Cleaner production process technologies', 'Adopt cleaner production technologies, optimise raw material selection and processing, and reduce pollutant emissions and waste generation', 'Technological evolution of the pulp and paper industry in Brazil https://online.fliphtml5.com/rhwu/zbrk/#p=1', null, 5);
INSERT INTO demand.demandeng (region, industry, description, stage, tech_categories, tech, tech_overview, source, number, demand_id) VALUES ('Brazil', 'Pulp', 'Reduce carbon emissions and environmental impact by adopting technologies such as renewable energy and low carbon production processes and products', 'End-of-life disposal', 'Carbon reduction', 'Decarbonisation technology', 'Reduce carbon emissions and environmental impact by adopting technologies such as renewable energy and low carbon production processes and products', 'Brazil Paper and Pulp Market: Prospects, Trends Analysis, Market Size and Forecasts up to 2028
https://www.researchandmarkets.com/reports/5713828/brazil-paper-and-pulp-market-prospects-trends#tag-pos-3', null, 6);
INSERT INTO demand.demandeng (region, industry, description, stage, tech_categories, tech, tech_overview, source, number, demand_id) VALUES ('Brazil', 'Pulp', 'Including the use of low NOx combustion technologies, gas combustion waste heat recovery technologies, fuel diversification and other measures to reduce pollution emissions from industrial fuels', 'End-of-life disposal', 'Air pollution prevention and control', 'Environmentally friendly clean fuel technology', 'Including the use of low NOx combustion technologies, gas combustion waste heat recovery technologies, fuel diversification and other measures to reduce pollution emissions from industrial fuels', '2022年报https://iba.org/datafiles/publicacoes/relatorios/relatorio-anual-iba2022-compactado.pdf', null, 7);
INSERT INTO demand.demandeng (region, industry, description, stage, tech_categories, tech, tech_overview, source, number, demand_id) VALUES ('Brazil', 'Pulp', 'The use of flue gas desulphurisation technology, such as wet desulphurisation and semi-dry desulphurisation, reduces the emission of harmful gases such as sulphur dioxide.', 'End-of-life disposal', 'Air pollution prevention and control', 'Desulphurisation technology', 'The use of flue gas desulphurisation technology, such as wet desulphurisation and semi-dry desulphurisation, reduces the emission of harmful gases such as sulphur dioxide.', '2022年报https://iba.org/datafiles/publicacoes/relatorios/relatorio-anual-iba2022-compactado.pdf', null, 8);
INSERT INTO demand.demandeng (region, industry, description, stage, tech_categories, tech, tech_overview, source, number, demand_id) VALUES ('Brazil', 'Pulp', 'The technology includes tree planting, seedling nursery, forest conservation and regeneration and aims to protect the environment and forest resources and ensure sustainable development', 'Source control', 'Biodiversity conservation', 'Sustainable forest management techniques', 'The technology includes tree planting, seedling nursery, forest conservation and regeneration and aims to protect the environment and forest resources and ensure sustainable development', '2022年报https://iba.org/datafiles/publicacoes/relatorios/relatorio-anual-iba2022-compactado.pdf', null, 9);