create table detail
(
    detail_id     int auto_increment
        primary key,
    industry      varchar(50)  null,
    region        varchar(50)  null,
    standard      varchar(200) null,
    number        varchar(200) null,
    effectiveness varchar(20)  null,
    abstracts     varchar(600) null,
    link          varchar(200) null,
    scope         int          null,
    year          int          null
);

INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (1, '造纸', '中国', '清洁生产标准造纸工业(漂白碱法蔗渣浆生产工艺)', 'HJ/T 317-2006', '是', '标准规定了造纸工业（漂白碱法蔗渣浆生产工艺）的清洁生产要求。', 'https://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/other/qjscbz/200611/t20061129_96653.shtml', 1, 2006);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (2, '造纸', '中国', '清洁生产标准造纸工业(漂白化学烧碱法麦草浆生产工艺)', 'HJ/T 339-2007', '是', '标准规定了造纸工业（漂白化学烧碱法麦草浆生产工艺）企业清洁生产的一般要求。', null, 1, 2007);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (3, '造纸', '中国', '清洁生产标准造纸工业(硫酸盐化学木浆生产工艺)', 'HJ/T 340-2007', '是', '标准规定了造纸工业（本色硫酸盐化学木浆的生产和漂白硫酸盐化学木浆工艺）清洁生产的一般要求。', 'https://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/other/qjscbz/200704/t20070403_102432.shtml', 1, 2007);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (4, '造纸', '中国', '《清洁生产标准 造纸工业（废纸制浆）》', 'HJ 468—2009', '是', '标准规定了造纸工业（废纸制浆）企业清洁生产的一般要求。', 'https://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/other/qjscbz/200904/t20090415_150469.htm', 1, 2009);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (5, '造纸', '中国', '制浆造纸行业现场环境监察指南（试行）', null, '是', '指南规范了制浆造纸企业的现场环境监察工作', 'https://www.mee.gov.cn/gkml/hbb/bgt/201011/t20101101_196957.htm', 1, 2010);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (6, '造纸', '中国', '造纸行业木材制浆工艺污染防治可行技术指南（试行）', null, '是', null, 'https://www.mee.gov.cn/gkml/hbb/bgg/201312/t20131231_265891.htm', 1, 2013);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (7, '造纸', '中国', '造纸行业非木材制浆工艺污染防治可行技术指南（试行）', null, '是', null, 'https://www.mee.gov.cn/gkml/hbb/bgg/201312/t20131231_265892.htm', 1, 2013);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (8, '造纸', '中国', '造纸行业废纸制浆及造纸工艺污染防治可行技术指南（试行）', null, '是', null, 'https://www.mee.gov.cn/gkml/hbb/bgg/201312/t20131231_265893.htm', 1, 2013);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (9, '造纸', '中国', '《制浆造纸工业水污染物排放标准》', 'GB 3544-2008 代替GB 3544-2001', '是', '标准规定了制浆造纸企业或生产设施水污染物排放限值。', 'https://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/shjbh/swrwpfbz/200807/t20080701_124695.htm ', 3, 2008);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (10, '造纸', '中国', '《进口废纸环境保护管理规定》', '国办发〔2017〕70号', '是', '标准规定了进口废纸环境管理的一般要求。', 'https://www.mee.gov.cn/gkml/hbb/bwj/201712/t20171218_428134.htm ', 3, 2017);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (11, '造纸', '中国', '造纸工业污染防治技术政策', null, '是', null, 'https://www.mee.gov.cn/gkml/hbb/bgg/201708/t20170808_419350.htm ', 3, 2017);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (12, '造纸', '中国', '《制浆造纸工业污染防治可行技术指南》', 'HJ 2302—2018', '是', '标准规定了制浆造纸工业废水、废气、固体废物和噪声污染防治可行技术。', 'https://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/wrfzjszc/201801/t20180112_429627.shtml', 3, 2018);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (13, '造纸', '美国', null, null, '是', '关于联邦法规电子法典的环境保护类别针对纸浆、纸张和纸板点源类别的说明。', 'https://www.ecfr.gov/cgi-bin/retrieveECFR?gp=&SID=1f13dafc01e3ec9570aba6d9167f5b0f&mc=true&n=sp40.32.430.b&r=SUBPART&ty=HTML', 1, 1998);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (14, '造纸', '美国', '40 CFR ( 第 40条 -保护环境 )：第430部分——纸浆、纸张、纸板点源类别', 'RIN：2070-AJ44', '是', '关于压制木制品的甲醛排放规定。', null, 1, 2016);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (15, '造纸', '美国', '纸浆、纸张和纸板排放指南', '联邦法规引文：
40 CFR Part 430', '是', '关于纸浆、纸张和纸板类排放指南和标准。', 'https://www.epa.gov/eg/pulp-paper-and-paperboard-effluent-guidelines', 3, 1974);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (16, '造纸', '美国', '纸浆和纸张生产 (MACT I & III)：源类别的有害空气污染物国家排放标准', '联邦法规引文：
40 CFR Part 63 Subpart S', '是', '关于纸浆生产源的排放规定。', 'https://www.epa.gov/stationary-sources-air-pollution/pulp-and-paper-production-mact-i-iii-national-emissions-standards ', 3, 2001);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (17, '造纸', '美国', '硫酸盐、苏打、亚硫酸盐、独立式半化学浆厂( MactⅡ)：化学回收燃烧源危险空气污染物国家排放标准', '联邦法规引文：
40 CFR Part 63 Subpart MM', '是', '关于纸浆厂燃烧源的排放。', 'https://www.epa.gov/stationary-sources-air-pollution/kraft-soda-sulfite-and-stand-alone-semichemical-pulp-mills-mact-ii ', 3, 2001);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (18, '造纸', '美国', '纸张和其他涂料：国家有害空气污染物排放标准', '联邦法规引文：
40 CFR Part 63 Subpart JJJJ', '是', '关于纸和表面涂层的空气污染物 国家排放标准。', null, 3, 2002);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (19, '造纸', '欧盟', '纸浆、纸和纸板生产的最佳可用技术参考文件', '欧盟工业排放标准：2010/75/EU', '是', null, 'https://op.europa.eu/en/publication-detail/-/publication/fcaab1a5-d287-40af-b21c-115e529685fc/language-en', 3, 2010);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (20, '造纸', '澳大利亚', '澳大利亚新漂白桉木硫酸盐纸浆厂的环境指南', null, null, null, null, 1, 1989);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (21, '造纸', '巴西', '第14.128号文件规定了国家有关材料回收利用的政策和适用于固体废物管理的经济和财政手段', null, '是', '法令由 7 条组成，规定了国家材料回收政策以及适用于固体废物管理的经济和金融工具。', 'http://www.almg.gov.br/ ', 3, 2001);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (22, '造纸', '巴西', '巴西联邦污水标准', null, '否', null, null, 3, 1993);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (23, '造纸', '芬兰', '芬兰林业的国家环境保护目标', null, '否', null, null, 3, 1993);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (24, '造纸', '德国', '废纸回收条例', null, '是', '该条例旨在通过公共废物处理框架内的废纸分类收集，促进废纸的高质量回收。', 'http://www.hamburg.de/ ', 3, 2010);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (25, '造纸', '德国', '德国制浆造纸工业废水排放标准', null, '否', null, null, 3, 1989);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (26, '造纸', '法国', '法国化学纸浆厂废水中悬浮固体和耗氧物质的最大允许量', null, '否', null, null, 3, 1993);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (27, '造纸', '印度尼西亚', '印度尼西亚制浆造纸工业废水质量标准', null, '否', null, null, 3, 1991);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (28, '造纸', '加拿大', '纸浆和纸张的出水规定', 'SOR/92-269', '是', '规定了与制浆造纸厂和场外处理设施的废水有关的某些有害物质的规定，并授权在某些情况下存放有限数量的这些有害物质。', 'https://www.canada.ca/en/environment-climate-change/services/environmental-indicators/pulp-paper-effluent-quality.html', 3, 1992);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (29, '造纸', '加拿大', '纸浆和造纸厂废水氯化二恶英和呋喃法规', 'SOR/92-267', '是', '有关纸浆和造纸厂废水中多氯二苯并对二恶英和多氯二苯并呋喃的释放的法规', null, 3, 1992);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (30, '造纸', '加拿大', '制浆造纸厂消泡剂和木片规定', 'SOR 2-268', '是', '有关在使用氯漂白工艺的纸浆和造纸厂中生产、进口、销售、销售和使用含有二苯并呋喃或二苯并-对二恶英的消泡剂以及在所有纸浆和造纸厂中含有多氯酚的木片的法规', null, 3, 1992);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (31, '造纸', '加拿大', '工业排放-氮氧化物和二氧化硫', 'O. Reg. 194/0', '是', '纸浆和造纸行业的氮氧化物和二氧化硫 排放限值', null, 3, 2005);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (32, '造纸', '加拿大', '家用包装和纸张管理规定', 'R.R.S. c. E-10.21 Reg. ', '是', '家庭包装和纸张管理计划规定', null, 3, 2013);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (33, '造纸', '加拿大', '环境管理和保护(总)规章', 'R.R.S. c. E-10.22 Reg. 1', '是', '纸浆或造纸厂、木材处理设施、木制品的相关规定', null, 3, 2014);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (34, '造纸', '斯洛文尼亚', '纸浆生产废水排放中物质和热量排放的规定', null, '是', '斯洛文尼亚共和国政府条例由 11 条和两个附件组成，规定了有关纸浆生产厂和综合生产设施排放工业废水中物质排放的具体要求纸浆、纸和纸板。该法规特别规定了工业废水的参数（第 3 条）和​​与减少排放相关的具体措施', 'http://www.pisrs.si/', 3, 2006);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (35, '造纸', '印度', '环境（保护）规则', null, '是', '环境污染物排放、排放标准按附表一至附表四规定执行。中央政府可以根据第 5 条规定的因素禁止或限制建立工业或开展特定过程或操作。', 'http://envfor.nic.in/', 3, 1986);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (36, '造纸', '老挝', '工业手工业部长关于工厂废水排放的规定', null, '是', '第 3 条列出了不能排放到环境和公共水源中的物质。第四条规定了纺织服装厂、纸浆造纸厂、造纸厂、屠宰场等工厂的通用标准和具体标准。', null, 3, 1994);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (37, '造纸', '奥地利', '废水排放条例-纸业', null, '是', '法令限制将奥地利造纸业的废水排放到公共水域；尤其是，必须对含有污染物质的废水进行监测并减少排放量。', 'http://www.ris.bka.gv.at/ ', 3, 2000);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (38, '造纸', '奥地利', '废水排放条例-纺织，皮革和纸张', null, '是', '法令限制将奥地利纺织、皮革和造纸工业的废水排放到公共水域；尤其是，必须对含有污染物质的废水进行监测并减少排放量。', 'http://www.ris.bka.gv.at/ ', 3, 2000);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (39, '造纸', '荷兰', '183号法令包含规则相对于包装，包装废弃物，纸张和纸板', null, '是', '法令令包含有关收集、回收和使用纸和纸板包装以及纸和纸板的规则。它规定进口商和生产商有义务使用再生纸，并规定了可能用于包装的铅等有毒物质的百分比。该法令也适用于食品包装。', 'http://www.overheid.nl/ ', 3, 2005);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (40, '造纸', '摩尔多瓦共和国', '第409号:修订环境保护法', null, '是', '法令规定了再生纸的用途', null, 3, 2004);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (41, '造纸', '越南', '用于生产原料的进口废弃材料的环境保护条例', 'NO. 03/2004/QD-BTNMT ', '是', '该决定规定了当废弃原材料（钢、铜、铝、锌、玻璃、纸板、纸、塑料等）被进口并在国内用作不被视为废物的次要材料时的环境保护条例。', null, 3, 1993);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (42, '石化', '中国', '清洁生产标准   石油炼制业', 'HJ/T 125-2003', '是', '为贯彻实施《中华人民共和国环境保护法》和《中华人民共和国清洁生产促进法》，进一步推动中国的清洁生产，防止生态破坏，保护人民健康，促进经济发展，并为炼油厂开展清洁生产提供技术支持和导向，制订本标准。 本标准为推荐性标准，可用于燃料型炼油厂的清洁生产审核和清洁生产潜力与机会的判断，以及清洁生产绩效评定和清洁生产绩效公告制度。燃料-润滑油型、燃料-化工型石油炼制企业可参照执行。 本标准为首次发布，自2003年6月1日起实施。', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (43, '石化', '中国', '石油炼制工业污染物排放标准', 'GB 31570-2015', '是', '为贯彻《中华人民共和国环境保护法》、《中华人民共和国水污染防治法》、《中华人民共和国大气污染防治法》等法律、法规，保护环境，防治污染，促进石油炼制工业的技术进步和可持续发展，制定本标准。本标准规定了石油炼制工业企业及其生产设施的水污染物和大气污染物排放限值、监测和监督管理要求。石油炼制工业企业排放恶臭污染物、环境噪声适用相应的国家污染物排放标准，产生固体废物的鉴别、处理和处置适用相应的国家固体废物污染控制标准。配套的动力锅炉执行《锅炉大气污染物排放标准》或《火电厂大气污染物排放标准》。', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (44, '石化', '中国', '石油化学工业污染物排放标准', 'GB 31571-2015', '是', '为贯彻《中华人民共和国环境保护法》、《中华人民共和国水污染防治法》、《中华人民共和国大气污染防治法》等法律、法规，保护环境，防治污染，促进石油化学工业的技术进步和可持续发展，制定本标准。本标准规定了石油化学工业企业及其生产设施的水污染物和大气污染物排放限值、监测和监督管理要求。石油化学工业企业排放恶臭污染物、环境噪声适用相应的国家污染物排放标准，产生固体废物的鉴别、处理和处置适用相应的国家固体废物污染控制标准。配套的动力锅炉执行《锅炉大气污染物排放标准》或《火电厂大气污染物排放标准》。本标准为首次发布。', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (45, '石化', '中国', '清洁生产评价指标体系 石油炼制业', 'DB11／T 1157-2015', '是', '本标准规定了石油炼制业清洁生产的评价指标体系、评价方法、指标计算与数据来源。本标准适用于石油炼制企业的清洁生产审核、评估与绩效验收。', 'http://scjgj.beijing.gov.cn/', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (46, '石化', '中国', '石化行业能源消耗统计指标及计算方法 炼油', 'NB/SH/T 5001.1-2013', '是', '本标准规定了炼油生产的能源消耗统计指标及计算方法。本标准适用于主要以原油及外购原料油为原料，生产液化石油气、丙烷、丙烯、苯、甲苯、混合二甲苯、汽油、煤油、柴油、燃料油、润滑油基础油、溶剂油、石蜡、沥青、石油焦和化工原料等产品生产过程中所消耗能源的统计及计算。', 'http://www.nea.gov.cn/', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (47, '石化', '中国', '脸油单位产品能源消耗限额', 'GB 30251-2013', '是', '本标准规定了炼油单位产品能源消耗限额的技术要求、统计范围和计算方法、节能管理与措施。本标准适用于以原油及外购原料油为原料，生产汽油、柴油、煤油、润滑油基础油、溶剂油、燃料油、液化石油气、丙烷、丙烯、苯、甲苯、混合二甲苯、石蜡、沥青、石油焦及化工原料等生产过程能耗计算、考核，以及新建项目的能耗控制。', 'https://www.antpedia.com/standard/6804158.html', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (48, '石化', '中国', '清洁生产标准 基本化学原料制造业 (环氧乙烷/乙二醇)', 'HJ/T 190-2006', '是', '为贯彻实施《中华人民共和国环境保护法》和《中华人民共和国清洁生产促进法》，保护环境，为基本化学原料制造企业开展清洁生产提供技术支持和导向，制订本标准。 本标准为推荐性标准，可用于生产环氧乙烷/乙二醇的企业进行清洁生产审核和清洁生产潜力与机会的判断，以及清洁生产绩效评定和清洁生产绩效公告制度。', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (49, '石化', '中国', '清洁生产标准 石油炼制业（沥青）', 'HJ 443-2008', '是', '为贯彻《中华人民共和国环境保护法》和《中华人民共和国清洁生产促进法》，保护环境，为石油炼制行业（沥青）生产企业开展清洁生产提供技术支持和导向，制定本标准。本标准规定了在达到国家和地方环境标准的基础上，根据当前的行业技术、装备水平和管理水平，石油炼制业沥青生产企业清洁生产的一般要求。本标准分三级，一级代表国际清洁生产先进水平，二级代表国内清洁生产先进水平，三级代表国内清洁生产基本水平。随着技术的不断进步和发展，本标准也将不断修订，一般三至五年修订一次。本标准适用于石油炼制业（沥青）清洁生产的一般要求。本标准将清洁生产标准分为四类，即生产工艺与装备要求、资源能源利用指标、污染物产生指标（末端处理前', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (50, '石化', '中国', '清洁生产标准 氯碱工业（聚氯乙烯）', 'HJ 476-2009', '是', '为贯彻《中华人民共和国环境保护法》和《中华人民共和国清洁生产促进法》，保护环境，为聚氯乙烯生产企业开展清洁生产提供技术支持和导向，制定本标准。本标准规定了在达到国家和地方污染物排放标准的基础上，根据当前的行业技术、装备水平和管理水平，提出了聚氯乙烯生产企业清洁生产的一般要求。本标准分为三级，电石法聚氯乙烯一级代表国内清洁生产领先水平，二级代表国内清洁生产先进水平，三级代表国内清洁生产基本水平；乙烯法聚氯乙烯一级代表国际清洁生产先进水平，二级代表国内清洁生产先进水平，三级代表国内清洁生产基本水平。随着技术的不断进步和发展，本标准将适时修订。本标准规定了氯碱工业（聚氯乙烯）企业清洁生产的一般要求。', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (51, '石化', '中国', '清洁生产标准 氯碱工业（烧碱）', ' HJ 475－2009', '是', '为贯彻《中华人民共和国环境保护法》和《中华人民共和国清洁生产促进法》，保护环境，为烧碱生产企业开展清洁生产提供技术支持和导向，制定本标准。本标准规定了在达到国家和地方污染排放标准的基础上，根据当前的行业技术水平、装备水平和管理水平，提出了烧碱生产企业清洁生产的一般要求。本标准分为三级，隔膜法烧碱一级代表国内清洁生产领先水平，二级代表国内清洁生产先进水平，三级代表国内清洁生产基本水平；离子膜法烧碱一级代表国际清洁生产先进水平，二级代表国内清洁生产先进水平，三级代表国内清洁生产基本水平。随着技术的不断进步和发展，本标准将适时修订。本标准规定了氯碱工业（烧碱）企业清洁生产的一般要求。本标准将氯碱工业', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (52, '石化', '中国', '石油炼制工业废气治理工程技术规范', ' HJ 1094-2020', '是', '为贯彻《中华人民共和国环境保护法》《中华人民共和国大气污染防治法》等法律法规，防治环境污染，改善生态环境质量，规范石油炼制工业废气治理工程的建设及运行管理，制定本标准。本标准规定了石油炼制工业废气治理工程中的总体要求、工艺设计、检测与过程控制、施工与验收、运行管理的技术要求。本标准为指导性标准。', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (53, '石化', '中国', '污染源源强核算技术指南 石油炼制工业', 'HJ 982—2018', '是', '为贯彻落实《中华人民共和国环境保护法》《中华人民共和国环境影响评价法》《中华人民共和国大气污染防治法》《中华人民共和国水污染防治法》《中华人民共和国环境噪声污染防治法》《中华人民共和国固体废物污染环境防治法》等法律法规，完善固定污染源源强核算体系，指导和规范石油炼制工业污染源源强核算工作，制定本标准。', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (54, '石化', '中国', '排污单位自行监测技术指南 石油化学工业', 'HJ 947-2018', '是', '为落实《中华人民共和国环境保护法》《中华人民共和国水污染防治法》《中华人民共和国大气污染防治法》，指导和规范石油化学工业排污单位自行监测工作，制定本标准。本标准提出了石油化学工业和合成树脂工业（聚氯乙烯树脂生产装置除外）排污单位自行监测的一般要求、监测方案制定、信息记录和报告的基本内容和要求。', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (55, '石化', '中国', '石油炼制工业废水治理工程技术规范', 'HJ 2045-2014', '是', '为贯彻《中华人民共和国环境保护法》和《中华人民共和国水污染防治法》，规范石油炼制工业废水治理工程的设计、建设与运行管理，防治环境污染，保护环境和人体健康，制定本标准。本标准规定了石油炼制工业废水治理工程的设计、施工、验收与运行管理的技术要求。本标准为指导性标准。', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (56, '石化', '中国', '环境影响评价技术导则 石油化工建设项目', 'HJ/T 89-2003', '是', '本标准规定了石油化工建设项目（以下简称建设项目）环境影响评价的一般性原则、内容和方法。 石油化工建设项目系指以石油和石油气（包括天然气和炼厂气）为原料，从事炼油、化工、化纤和化肥生产以及相关的储存、运输、科研等建设项目。 本标准适用于石油化工新建、改建、扩建和技术改造项目的环境影响评价。', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (57, '石化', '中国', '环境标志产品技术要求 塑料包装制品', ' HJ 209-2017', '是', '为贯彻《中华人民共和国环境保护法》，有效利用和节约资源，减少塑料包装制品对环境和人体健康的影响，制定本标准。本标准对塑料包装制品的原材料和生产过程，产品降解性能、生物碳含量、印刷、标识等提出了环境保护要求。', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (58, '石化', '中国', '废塑料回收与再生利用污染控制技术规范(试行)', 'HJ/T 364-2007', '是', '为贯彻《中华人民共和国环境保护法》和《中华人民共和国固体废物污染环境防治法》，在废塑料回收与再生利用过程中保护环境、防治污染，适应管理工作的需要，制定本标准。 本标准规定了废塑料回收、贮存、运输、预处理、再生利用等过程的污染控制和环境保护监督管理的要求。 本标准适用于包括进口废塑料在内的各种废塑料的回收与再生利用，不适用于属于医疗废物和危险废物的废塑料。', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (59, '石化', '中国', '环境标志产品技术要求 泡沫塑料', 'HJ/T 233-2006', '是', '为贯彻《中华人民共和国环境保护法》，减少泡沫塑料在生产、使用过程中对环境和人体健康的影响，制定本标准。 本标准对发泡剂的使用物质，进行了限定。 本标准对《环境标志产品技术要求 无CFCs泡沫塑料》（HJBZ 42－2000）的技术内容进行了部分改动并对其进行了全面修改。 本技术要求规定了泡沫塑料环境标志产品的基本要求、技术内容及其检检方法。 本技术要求适用于除一次性发泡餐具外的所有泡沫塑料产品。 本标准自2006年3月1日起实施。', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (60, '石化', '中国', '环境标志产品技术要求 塑料门窗', 'HJ/T 237-2006', '是', '为贯彻《中华人民共和国环境保护法》，减少塑料门窗在生产、使用过程中对环境和人体健康的影响，节约能源、减少环境污染、降低原材料消耗、提高资源利用率，制定本标准。 本标准对《环境标志产品认证技术要求 塑料门窗》（HBC 14-2002）的技术内容进行了部分改动并对其进行了全面修改。 本标准规定了塑料门窗环境标志产品的术语和定义、基本要求、技术内容及检验方法。 本标准适用于符合型材相关要求并按照统一的规范进行组装、安装的各类塑料门窗的环境标志产品认证。 本标准自2006年3月1日起实施。', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (61, '石化', '国际标准化组织', '石油、石化和天然气行业 - 特定部门的质量管理系统对产品和服务供应组织的要求', 'ISO 29001：2020', '是', '本文对石油、石化、天然气等行业产品和服务供应组织的质量管理体系要求进行了界定。以管理与石油、石化和天然气行业相关的供应链风险和机会，并为使要求与行业内采用的补充标准保持一致提供框架。', 'https://www.iso.org/home.html', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (62, '石化', '国际标准化组织', ' 能源管理系统 - 使用指南要求', 'ISO 50001：2018', '是', '本文件对建立、实施、维护和完善能源管理系统（EnMS）的要求作了具体规定。预期的结果是使组织能够遵循系统的方法，实现能源性能和 EnMS 的持续改进。

本文档：

a） 适用于任何组织，无论其类型、规模、复杂性、地理位置、组织文化或其提供的产品和服务如何：

b） 适用于影响组织管理和控制的能源绩效的活动;

c） 适用，无论消耗的能源数量、使用或类型如何：

d） 要求持续提高能源性能，但没有界定要实现的能源性能改进水平：

e） 可独立使用，或与其他管理系统对齐或集成。

附件 A 为使用本文档提供指导。附件 B 提供了本版本与上一版本的比较。', 'https://www.iso.org/home.html', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (63, '石化', '国际标准化组织', '能源管理系统 - ISO 50001 能源管理系统的实施、维护和完善指南', 'ISO 50004：2020', '是', '本文件为按照ISO 50001：2018的系统方法建立、实施、维护和完善能源管理系统（EnMS）提供了切实可行的指导方针和实例。本文档中的指导适用于任何组织。

本文件没有就如何开发综合管理系统提供指导。

虽然本文件中的指导符合 ISO 50001：2018 的要求，但它没有对这些要求提供解释。', 'https://www.iso.org/home.html', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (64, '石化', '国际标准化组织', '能源审计 - 使用指南要求', 'ISO 50002：2014', '是', 'ISO 50002：2014 规定了进行能源绩效能源审计的流程要求。它适用于所有类型的机构和组织，以及各种形式的能源和能源使用。

ISO 50002：2014 规定了进行能源审计的原则、能源审计中常见流程的要求以及能源审计的可交付性。

ISO 50002：2014 没有满足能源审计服务机构能力的甄选和评估要求，也不涉及对组织能源管理系统的审计，如 ISO 50003 中所述。

ISO 50002：2014 还提供了有关其使用的信息指导。', 'https://www.iso.org/home.html', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (65, '石化', '国际标准化组织', '环境管理系统 - 使用指南要求', 'ISO 14001:2015', '是', 'ISO 14001：2015 规定了组织可用于提高环境绩效的环境管理系统的要求。ISO 14001：2015 旨在供寻求系统管理其环境责任的组织使用，从而促进可持续发展的环境支柱。

ISO 14001：2015 帮助组织实现其环境管理系统的预期结果，该系统为环境、组织本身和相关方提供价值。根据本组织的环境政策，环境管理系统的预期成果包括：

·提高环境性能;

·履行遵约义务;

·实现环境目标。

ISO 14001：2015 适用于任何组织，无论其规模、类型和性质如何，并适用于组织确定其可以控制或影响的活动、产品和服务的环境方面，从生命周期的角度来看。ISO 14001：2015 未说明', 'https://www.iso.org/home.html', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (66, '石化', '国际标准化组织', '环境管理 - 环境绩效评估指南', 'ISO 14031：2013', '否', 'ISO 14031：2013 指导组织内环境绩效评估 （EPE） 的设计和使用。它适用于所有组织，无论类型、大小、位置和复杂性如何。

ISO 14031：2013 未建立环境绩效水平。

ISO 14031：2013 中的指导可用于支持组织自己对 EPE 的方法，包括承诺遵守法律和其他要求、防止污染和不断改进。', 'https://www.iso.org/home.html', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (67, '石化', '国际标准化组织', '环境管理 - 环境绩效评估指南', 'ISO 14031：2021', '是', '本文件为组织内环境绩效评估 （EPE） 的设计和使用提供了指南。它适用于所有组织，无论类型、大小、位置和复杂性如何。

本文件没有确定环境绩效水平。它不用于建立任何其他环境管理系统 （EMS） 符合要求。

本文件中的指导可用于支持组织自己对 EPE 的方法，包括承诺遵守法律和其他要求、防止污染和不断改进等。

请注意，本文档是一个通用标准，不包括关于评估或加权不同类型部门、学科等不同类型影响的具体方法的指导。根据组织活动的性质，往往还需要前往其他来源，就具体部门专题、不同主题或不同的科学学科提供补充信息和指导。', 'https://www.iso.org/home.html', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (68, '石化', '国际标准化组织', '塑料 - 塑料废物回收和再利用指南', 'ISO 15270:2008', '是', 'ISO 15270：2008 为制定涵盖塑料废物回收（包括回收）的标准和规范提供指导。该标准确定了回收消费者前和消费后来源产生的塑料废物的不同选择。它还规定了恢复过程所有步骤中应考虑的质量要求，并提供了将材料标准、测试标准和产品规格纳入的一般建议。因此，标准中提出的过程阶段、要求、建议和术语具有一般适用性。', 'https://www.iso.org/home.html', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (69, '石化', '世界银行', '环境，健康和安全指南-石油炼制业', null, '是', '1. 环境、健康和安全 (EHS) 指南是技术参考文件，其中包含良好国际行业规范 (GIIP) 的一般和行业特定示例。 1 当世界银行集团的一个或多个成员参与一个项目时，本 EHS 指南将按照其各自政策和标准的要求应用。这些行业部门 EHS 指南旨在与通用 EHS 指南文件一起使用，该文件为用户提供有关可能适用于所有行业部门的常见 EHS 问题的指南。对于复杂的项目，使用多个行业部门。
2. EHS 指南包含的性能水平和措施通常被认为可以通过现有技术以合理的成本在新设施中实现。将 EHS 指南应用于现有设施可能涉及建立特定地点的目标，以及实现这些目标的适当时间表。
3. EHS 指南的适用性应', 'www.ifc.org/ehsguidelines.', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (70, '石化', '欧盟', '工业排放指令', '2010/75 / EU', '是', '该指令在修订过程中遵循了综合治理、最佳可行技术、灵活性、监测管理、公众参与等五项原则，针对各类主要工业污染领域做出了详细而科学的规定，以期最大限度地减少在整个欧盟范围内各种工业源的污染。 该指令涉及能源产业、金属生产和加工、采矿、化工、废物处理等多个行业，在规定行业内的企业项目需获得有关机构发放的综合许可证后方可开工运行。该指令在制定了工业活动污染的防治一体化规定的同时也制定了相关规则，防止或者在不能防止的地方减少针对空气、水以及土壤的废物排放，减少废物的产生，以实现对环境更好地整体保护。
', 'https://ec.europa.eu/environment/eussd/smgp/index.htm', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (71, '石化', '欧盟', '矿物石油和天然气精炼的最佳可用技术 （BAT） 参考文档。2010/75/欧盟工业排放指令（综合污染预防和控制）', 'JRC94879', '是', '题为"矿物石油和天然气精炼"的BREF是一系列报告欧盟成员国、有关行业、促进环境保护的非政府组织和委员会之间信息交流结果的一部分，以起草、审查并在必要时根据《工业排放指令》（2010/75/EU）第13条第1款的要求更新BAT参考文件。本文件由欧洲联盟委员会根据该指令第13（6）条出版。该矿物石油和天然气精炼布雷夫涵盖附件一至2010/75/欧盟指令第1.2节规定的某些工业活动，即矿物石油和天然气部门提炼的能源工业。本文特别涵盖了以下炼油工艺和活动：-烷基化-基础石油生产-沥青生产-催化裂化-催化改造-焦化-冷却-脱盐-燃烧炼油燃料用于能源生产-以太化-气体分离-氢消耗过程-氢气生产-同化-天', 'https://publications.jrc.ec.europa.eu/repository/handle/JRC94879', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (72, '石化', '欧盟', '塑料袋指令', '(EU) 2015/720', '是', '《塑料袋指令》是《包装和包装废物指令》（94/62/EC）的修正案，旨在解决轻质塑料袋的不可持续消费和使用问题，该指令是欧洲十大垃圾指令之一。轻质塑料袋通常只使用一次，但它们需要几个世纪才能在自然环境中完全降解。在此之前，它们经常被陆地或海洋动物摄入，或分解成微塑料。无论哪种方式，他们最终积累在人类和动物的食物链。该指令要求会员国采取措施，如国家减排目标和/或经济工具（如费用、税收）和营销限制（禁令），但条件是后者是相称的和非歧视性的。会员国采取的措施包括以下两者之一：
采取措施，确保到2019年12月31日，人均年消费量不超过90个轻质塑料袋，到2025年12月31日，每人年消费量不超过40', 'https://ec.europa.eu/environment/eussd/smgp/index.htm', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (73, '石化', '欧盟', '电子电器设备废弃物指令', '2012/19/EU', '是', '为防止或减少产生报废电子电气设备以及加强对电子电气设备的管理，保护环境和人类健康。通过原材料的使用，提高使用效率，降低其所带来的负面涌向，最终达到可持续发展。该指令针对电子电气设备生命周期内所有相关方（生产商、分销商和消费者）的环境表现提出相关要规定，共包括27项条款和12项附件。', 'https://ec.europa.eu/environment/eussd/smgp/index.htm', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (74, '石化', '美国', '环境保护', null, '是', '联邦环境法规规定了针对各行业的水污染物、大气污染物、固体废弃物排放标准，能源政策，有毒物质管理计划等。', 'https://www.ecfr.gov/', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (75, '石化', '美国', '节约电力和水资源', null, '是', '国家能源管理方案和水资源管理方案。', 'https://www.ecfr.gov/', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (76, '石化', '伊朗', '确定空气污染物允许限值的决议', null, '是', '内阁根据《2017年清洁空气法》第12条通过了本条例。该条例确定了不同工业部门的空气污染物排放允许限值，包括：水泥工业、铸造业、发电厂、炼油厂和石化业、重金属和其他行业。环境部是执行和监督该条例的负责当局。', 'rc.majlis.ir', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (77, '石化', '印度尼西亚', '国家环境事务部长关于上游石化工业企业和/或活动的废水质量标准的第8/2007号条例', null, '是', '本条例旨在通过规定上游石化行业企业和/或活动的废水质量标准来控制水污染', 'http://extwprlegs1.fao.org/docs/pdf/ins77177.pdf', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (78, '石化', '安哥拉', '石油化工和生物燃料精炼国家方向条例', ' NO. 185/14 ', '是', '该条例由4章2个附件组成，规定了上述《指示》的组成、职责和责任，其权为：a） 促进和合作制定有关炼油、石化、生物燃料和润滑油生产和使用的必要政策：b） 监测和控制与这些部门有关的活动：c） 建议', 'http://extwprlegs1.fao.org/docs/pdf/ang134833.pdf', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (79, '石化', '安哥拉', '适用于与石油产品有关的任何活动的法律框架', 'NO. 132/13 ', '是', '这项总统令由15章组成，确立了适用于与石油产品有关的任何活动的法律框架，从原油精炼工艺、储存、通过管道运输石油产品、安哥拉共和国石油产品系统的后勤监督，到石油产品的分销以及毛市场和详细市场的运作等。', 'http://extwprlegs1.fao.org/docs/pdf/ang127372.pdf', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (80, '石化', '安哥拉', '设立石油产品管理机构', 'NO. 133/13', '是', '这项总统令批准了《安哥拉共和国石油衍生品管理机构规约》。《规约》由5章2个附件组成，规定了上述机构的组成、职责和责任，有权从事与石油产品有关的任何活动，从原油、炼油工艺、储存、通过管道运输石油产品、共和国石油产品系统的后勤监督等。', 'http://extwprlegs1.fao.org/docs/pdf/ang130803.pdf', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (81, '石化', '安哥拉', '批准关于原油精炼和石油产品的运输、储存、贸易和供应的立法', 'NO. 28/11', '是', '该法共13章，批准了关于原油精炼和石油产品的运输、储存、贸易和供应的立法。这项立法旨在规范上述与石油产品及其衍生品有关的活动的一般运作。本法适用于整个国家领土，包括所有从事与上述部门有关的活动的公立或私营、个人或集体实体。', 'http://extwprlegs1.fao.org/docs/pdf/ang120535.pdf', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (82, '石化', '孟加拉国', '石油2016年法案', 'NO. 3 of 2016', '是', '该法由六章组成，对石油进口、运输、储存、分销、炼油、混合、测试、许可以及与石油开采有关的所有方面进行了规范。该法分为以下几个方面：定义（第1章）：石油控制（第2章）：许可证（第3章）：石油测试（第4章）：第五章犯罪和处罚（第5章）：杂项（第6章）。', 'http://extwprlegs1.fao.org/docs/pdf/bgd158187.pdf', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (83, '石化', '葡萄牙', '关于国家石油系统组织和运作的总体基础的第31/2006号法令', 'NO. 31/2006', '是', '该法令共7章，确立了国家石油系统组织和运作的总体基础，以及适用于开展原油和石油产品市场的储存、运输、分销、炼油和销售活动以及组织活动的一般规定。它适用于整个国家领土。', 'http://extwprlegs1.fao.org/docs/pdf/por149484.pdf', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (84, '石化', '印度', '《石油和天然气管制委员会法》', 'NO. 19 of 2006', '是', '该法规定将石油和天然气管理委员会作为一个法人团体设立，并界定其权力和职能。董事会的职能包括：注册从事石油、石油产品和天然气等炼油、加工、运输、销售、进出口等的实体：保护消费者利益：征收费用和其他费用;制定技术和安全标准。', 'http://extwprlegs1.fao.org/docs/pdf/ind68501.pdf', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (85, '石化', '埃塞俄比亚', '石油业务公告', 'NO. 295/1986', '是', '本公告规定了涉及和涉及石油勘探、开发、开采、生产、处理、储存、运输和销售的作业规则，不包括原油精炼，但包括天然气加工。《公告》界定了部长管理石油业务和控制承包商的权力，并规定了与承包商缔结的石油协定的细节。', 'http://extwprlegs1.fao.org/docs/pdf/eth85045.pdf', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (86, '石化', '澳大利亚', '《产品管理法》（石油）', 'Act 2000', '是', '（a） 制定废油产品管理安排：（b） 确保废物油的环境可持续管理、再提炼和再利用：和 （c） 支持废油的经济回收选择。根据本法，向在提出支付产品管理（石油）福利时登记有权享受产品管理（石油）福利的人提供赠款（"产品管理（石油）福利"。', 'https://view.officeapps.live.com/op/view.aspx?src=http%3A%2F%2Fextwprlegs1.fao.org%2Fdocs%2Ftexts%2Faus45239.doc&wdOrigin=BROWSELINK', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (87, '石化', '卡波维德', '规范国家石油系统', 'NO. 56/2010 ', '是', '这项法令由7章组成，规定了国家石油系统的运作和组织。它规定了为执行与原油及其副产品有关的上述活动而必须履行的授权活动和要求，例如：进出口、储存、加工、运输、分销、炼油和贸易。法令法界定了许可证程序、石油基础设施和物流、石油产品。', 'http://extwprlegs1.fao.org/docs/pdf/cvi109389.pdf', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (88, '石化', '阿塞拜疆', '关于禁止排放工业污水类型的企业第122号部长令', 'NO.122', '是', '根据《供水和污水法》第723-IQ第39条，颁布本法令，规定禁止处理工业污水的企业类型。该法令规定，禁止石油生产、炼油、化学和石化工业排放污水。', 'http://extwprlegs1.fao.org/docs/pdf/aze160703.pdf', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (89, '石化', '瑞典', '关于大型焚烧厂的条例', '2013:252', '是', '该条例规定了大型燃烧厂和精炼残余燃料（炼油厂使用的原油精炼产生的转化残留物）的预防措施条例。大型焚化炉设施应当申请燃烧活动地点、计量和运行许可证。运营和排放标准的容量应根据国际标准化组织规定的 CEN 和 ISO 标准的授权进行衡量。', 'http://extwprlegs1.fao.org/docs/pdf/swe124074.pdf', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (90, '石化', '开曼群岛（英国）', '《燃料市场监管法》', 'NO. 20 of 2017', '是', '本法界定了燃料部门为2016年《公用事业条例和竞争法》提供和提供的服务。它规定，内阁应制定和维持旨在确保以符合公共利益的方式执行燃料的进口、出口、转口、运输、加工、精炼、储存、分销、销售和销售的政策。', 'http://extwprlegs1.fao.org/docs/pdf/cay171866.pdf', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (91, '纺织', '中国', '清洁生产标准纺织业(棉印染)', 'HJ/T185-2006', '是', '本标准为推荐性标准，可用于纺织行业（棉印染）生产企业的清洁生产审核和清洁生产潜力与机会的判断，以及清洁生产绩效评定和清洁生产绩效公告制度。', 'https://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/other/qjscbz/200610/t20061001_78200.htm', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (92, '纺织', '中国', '清洁生产标准化纤行业(氨纶)', 'HJ/T359-2007', '是', '本标准适用于采用干法溶剂纺丝工艺路线的氨纶生产厂家（不包括原料生产和生活过程）的企业清洁生产审核和清洁生产潜力与机会的判断，以及清洁生产绩效评定和清洁生产绩效公告制度。', 'https://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/other/qjscbz/200708/t20070808_107735.shtml', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (93, '纺织', '中国', '清洁生产标准化纤行业(涤纶)', 'HJ/T429-2008', '是', '本标准规定了化纤行业(涤纶)生产企业清洁生产的一般要求。本标准适用于采用对苯二甲酸直接酯化法生产聚酯和以聚酯为原料生产涤纶纤维的企业清洁生产审核和清洁生产潜力与机会的判断，以及清洁生产绩效评定、清洁生产绩效公告制度，也适用于环境影响评价和排污许可证等环境管理制度。本标准为首次发布。本标准为指导性标准。', 'https://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/other/qjscbz/200804/t20080414_121142.shtml', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (94, '纺织', '中国', '牛仔服装洗水行业清洁生产评价指标体系', 'T/GDTEX 05-2019', '是', '本标准规定了牛仔服装洗水企业清洁生产的一般要求，将清洁生产指标分为六类，即生产工艺及设备要求、资源和能源消耗指标、资源综合利用指标、污染物产生指标、产品特征指标和清洁生产管理指标，本标准适用于牛仔服装洗水企业或包括牛仔服装洗水工序的综合性纺织企业清洁生产水平评价', 'http://www.gdtextiles.cn/nd.jsp?id=272', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (95, '纺织', '中国', '绿色设计产品评价技术规范 羊绒针织制品', 'T/CAB 0025-2017', '是', '本标准规定了羊绒针织制品生命周期绿色设计评价的定义、评价要求、生命周期评价报告编制方法。', 'https://www.miit.gov.cn/cms_files/filemanager/oldfile/miit/n1146285/n1146352/n3054355/n3057542/c7796801/part/7797276.pdf', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (96, '纺织', '中国', '绿色设计产品评价技术规范 再生涤纶', 'T/CNTAC 52-2020', '是', '本标准给出了再生涤纶生命周期绿色设计评价的术语和定义、评价要求、绿色设计产品评价报告编写要求、产品生命周期评价报告编写要求、绿色设计产品判定依据。', 'https://www.miit.gov.cn/cms_files/filemanager/oldfile/miit/n1146285/n1146352/n3054355/n3057542/c7796801/part/7797281.pdf', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (97, '纺织', '中国', '绿色设计产品评价技术规范 户外多用途面料', 'T/CAB 0034-2018', '是', '本标准规定了户外多用途面料生命周期绿色设计评价的定义、评价要求、生命周期评价报告编制方法', 'https://www.miit.gov.cn/jgsj/jns/qjsc/art/2021/art_651f1af99f914c2fb68ca8a2aab4c943.html', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (98, '纺织', '中国', '绿色设计产品评价技术规范 丝绸制品', 'FZ/T 07003-2019', '是', '本标准规定了丝绸制品生命周期绿色设计评价的术语和定义、评价要求、评价方法、生命周期评价报告编制方法', 'https://www.miit.gov.cn/jgsj/jns/qjsc/art/2021/art_651f1af99f914c2fb68ca8a2aab4c943.html', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (99, '纺织', '中国', '绿色设计产品评价技术规范 涤纶磨毛印染布', 'T/CAB 0030-2018', '是', '本标准规定了涤纶磨毛印染布生命周期绿色设计评价的定义、评价要求、生命周期评价报告编制方法。', 'https://www.miit.gov.cn/jgsj/jns/qjsc/art/2021/art_651f1af99f914c2fb68ca8a2aab4c943.html', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (100, '纺织', '中国', '绿色设计产品评价技术规范 巾被织物', 'T/CNTAC 34-2019', '是', '本标准规定了巾被织物生命周期绿色设计评价的定义、评价要求、生命周期评价报告编制方法', 'https://www.miit.gov.cn/jgsj/jns/qjsc/art/2021/art_651f1af99f914c2fb68ca8a2aab4c943.html', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (101, '纺织', '中国', '绿色设计产品评价技术规范 毛精纺产品', 'T/CNTAC 39-2019', '是', '本标准给出了毛精纺产品生命周期绿色设计评价的术语和定义、评价要求、自评价报告编写要求、产品生命周期评价报告编写要求和绿色设计产品判定依据。', 'https://www.miit.gov.cn/jgsj/jns/qjsc/art/2021/art_651f1af99f914c2fb68ca8a2aab4c943.html', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (102, '纺织', '中国', '绿色设计产品评价技术规范 羊绒产品', 'T/CNTAC 38-2019', '是', '本标准给出了羊绒产品生命周期绿色设计评价的术语和定义、评价要求、自评价报告编写要求、产品生命周期评价报告编写要求和绿色设计产品判定依据', 'https://www.miit.gov.cn/n1146285/n1146352/n3054355/n3057542/n5920352/c7251483/part/7251661.pdf', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (103, '纺织', '中国', '绿色设计产品评价技术规范 布艺类产品', 'T/CNTAC 41-2019', '是', '本标准给出了布艺类产品生命周期绿色设计评价的术语和定义、评价要求、自评价报告编写要求、产品生命周期评价报告编写要求和绿色设计产品判定依据', 'https://www.miit.gov.cn/jgsj/jns/qjsc/art/2021/art_651f1af99f914c2fb68ca8a2aab4c943.html', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (104, '纺织', '中国', '绿色设计产品评价技术规范 婴幼儿湿巾', 'T/CAB 0052-2019', '是', '本标准适用于婴幼儿湿巾绿色设计产品评价，包括采用非织造布为原材料制造的可供婴幼儿使用的湿巾。', 'https://www.miit.gov.cn/jgsj/jns/qjsc/art/2021/art_651f1af99f914c2fb68ca8a2aab4c943.html', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (105, '纺织', '中国', '绿色设计产品评价技术规范 色纺纱', 'T/CNTAC 51-2020', '是', '本标准给出了色纺纱产品生命周期绿色设计评价的术语和定义、评价要求、自评价报告编写要求、产品生命周期评价报告编写要求和绿色设计产品判定依据', 'https://www.miit.gov.cn/jgsj/jns/qjsc/art/2021/art_651f1af99f914c2fb68ca8a2aab4c943.html', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (106, '纺织', '中国', '绿色设计产品评价技术规范 针织印染布', 'T/CNTAC 40-2019', '是', '本标准给出了针织印染布产品生命周期绿色设计评价的术语和定义、评价要求、自评价报告编写要求、产品生命周期评价报告编写要求和绿色设计产品判定依据', 'https://www.miit.gov.cn/n1146285/n1146352/n3054355/n3057542/n5920352/c7251483/part/7251663.pdf', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (107, '纺织', '中国', '绿色设计产品评价技术规范 皮服', 'T/CNTAC 35-2019', '是', '本标准规定了皮服绿色设计产品评价的术语、定义、评价要求、产品生命周期评价报告编制方法和评价方法', 'https://www.miit.gov.cn/jgsj/jns/qjsc/art/2021/art_651f1af99f914c2fb68ca8a2aab4c943.html', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (108, '纺织', '中国', '纺织行业绿色工厂评价导则', 'FZ/T 07004-2019', '是', '本标准规定了纺织行业绿色工厂评价的指标体系及通用要求。本标准适用于具有实际生产过程的棉（含棉型化纤）纺织及印染加工、毛纺织及染整精加工、麻纺织及染整精加工、丝绢纺织及印染精加工、化纤织造及印染精加工、针织品及其制品制造、家用纺织制成品制造、产业用纺织制成品制造、纺织服装服饰制造、化学纤维制造、纺织专用设备制造企业等，并作为纺织行业制定绿色工厂评价体系的总体要求。', 'https://www.spc.org.cn/online/FZ%252FT%252007004-2019/?', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (109, '纺织', '中国', '涤纶长丝织物行业印染绿色工厂评价要求', 'T/CAB 2018-2019', '是', '本标准适用于对涤纶长丝织物印染行业绿色工厂的评价。对其他化纤面料印染生产工厂开展绿色工厂的评价也可参照使用。', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (110, '纺织', '中国', '纺织行业绿色供应链管理企业评价指标体系', 'FZ/T 07005-2020', '是', '本标准规定了纺织行业企业绿色供应链管理的目的、范围、评价体系，包括绿色供应链管理战略、实施绿色供应商管理、绿色生产、绿色销售与回收、绿色信心平台建设及信息披露5个方面。', 'https://www.spc.org.cn/online/FZ%252FT%252007005-2020/?', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (111, '纺织', '中国', '纺织染整工业废水治理工程技术规范', 'HJ 471-2020', '是', '本标准规定了纺织染整工业废水治理工程的设计、施工、验收、运行和维护的技术要求。本标准为指导性标准。', 'https://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/jcffbz/202001/t20200115_759457.shtml', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (112, '纺织', '中国', '绿色产品评价 纺织产品', 'GB/T 35611-2017', '是', '本标准规定了绿色纺织产品的评价指标和评价方法。', 'https://www.spc.org.cn/online/GB%252FT%252035611-2017/?', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (113, '钢铁', '中国', '铸造工业大气污染物排放标准', 'GB39726-2020', '是', '本标准规定了铸造工业大气污染物排放控制要求、监测和监督管理要求。铸造工业企业或生产设施排放水污染物、恶臭污染物、环境噪声适用相应的国家污染物排放标准，产生固体废物的鉴别、处理和处置适用相应的国家固体废物污染控制标准。', 'http://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/dqhjbh/dqgdwrywrwpfbz/202012/t20201225_814815.shtml', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (114, '钢铁', '中国', '炼钢工业大气污染物排放标准', 'GB28664-2012', '是', '本标准规定了炼钢生产企业或生产设施大气污染物排放限值、监测和监控要求，以及标准的实施与监督等相关规定。本标准适用于现有炼钢生产企业或生产设施大气污染物排放管理，以及炼钢工业建设项目的环境影响评价、环境保护设施设计、竣工环境保护验收及其投产后的大气污染物排放管理。', 'http://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/dqhjbh/dqgdwrywrwpfbz/201207/t20120731_234142.shtml', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (115, '钢铁', '中国', '轧钢工业大气污染物排放标准', 'GB28665-2012', '是', '本标准规定了轧钢生产企业或生产设施的大气污染物排放限值、监测和监控要求，以及标准的实施与监督等相关规定。本标准适用于现有轧钢生产企业或生产设施大气污染物排放管理，以及轧钢工业建设项目的环境影响评价、环境保护设施设计、竣工环境保护验收及其投产后的大气污染物排放管理。', 'http://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/dqhjbh/dqgdwrywrwpfbz/201207/t20120731_234143.shtml', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (116, '钢铁', '中国', '钢铁工业水污染物排放标准', 'GB13456-2012', '是', '本标准规定了钢铁生产企业或生产设施水污染物排放限值、监测和监控要求，以及标准的实施与监督等相关规定。本标准适用于现有钢铁生产企业或生产设施的水污染物排放管理。', 'http://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/shjbh/swrwpfbz/201207/t20120731_234144.shtml', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (117, '钢铁', '中国', '钢铁企业节能设计规范', 'GB50632-2010', '是', '本规范适用于钢铁企业的总体发展规划、钢铁业新建和改建的设计，以及 钢铁企业能源规划等项目。钢铁联合企业生产流程包括烧结、球团，焦化、炼 铁、炼钢、轧钢等工艺以及公辅设施;此外还包括与钢铁生产密切相关并有一 定独立性的采矿、选矿、铁合金、炭素制品、耐火材料、冶金石灰、金属制品 等钢铁辅助企业。', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (118, '钢铁', '中国', '工业企业温室气体排放核算和报告通则', 'GB/T 32150—2015', '是', '该标准规定了工业企业温室气体排放核算与报告的术语和定义、基本原则、工作流程、核算边界确定、核算步骤与方法、质量保证、报告要求等内容。该标准适用于指导行业温室气体排放核算方法与报告要求标准的编制，也可为工业企业开展温室气体排放核算与报告活动提供方法参考。', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (119, '钢铁', '中国', '温室气体排放核算与报告要求 第5部分:钢铁生产企业', 'GB/T 32151—2015', '是', '本文件该部分规定了钢铁生产企业温室气体排放量的核算和报告相关的术语、核算边界、核算步骤与核算方法、数据质量管理、报告内容和格式等内容。', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (120, '钢铁', '中国', '基于项目的温室气体减排量评估技术规范 钢铁行业余能利用', 'GB/T 33755—2017', '是', '本标准规定了钢铁行业余能利用项目温室气体减排量评估的术语和定义及评估内容。', 'http://www.gb688.cn/bzgk/gb/newGbInfo?hcNO=2B101CC72890C5B68115856FFE264D45', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (121, '钢铁', '中国', '钢铁企业温室气体排放核查技术规范', 'RB/T 251—2018', '是', '本标准规定了高-转炉（长流程）钢铁生产企业、电炉（短流程）钢铁生产企业温室气体排放核查步骤、核查要求以及核查报告等要求。', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (122, '钢铁', '中国', '清洁生产标准 钢铁行业', 'HJ/T 189-2006', '否', ' 本标准为推荐性标准，可用于钢铁联合企业和电炉钢厂（短流程）的清洁生产审核和清洁生产潜力与机会的判断，以及清洁生产绩效评定和清洁生产绩效公告制度。', 'http://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/other/qjscbz/200610/t20061001_78207.shtml', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (123, '钢铁', '中国', '钢铁行业清洁生产评价指标体系（试行）', null, '否', '本指标体系用于评价钢铁企业的清洁生产水平，作为创建清洁生产先进企业的主要依据，并为企业推行清洁生产提供技术指导。', 'https://www.ndrc.gov.cn/hdjl/yjzq/201305/W020190927558534301256.pdf', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (124, '钢铁', '中国', '清洁生产标准钢铁行业（中厚板轧钢）', 'HJ/T 318-2006', '否', '本标准适用于钢铁行业 中厚板轧钢的清洁生产审核、清洁生产潜力与机会的判断、清洁生产绩效评定和清洁生产绩效公告制。', 'http://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/other/qjscbz/200611/t20061129_96654.shtml', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (125, '钢铁', '中国', '清洁生产标准钢铁行业（烧结）', 'HJ/T 426-2008', '否', '本标准将清洁生产指标分为六类，即生产工艺与装备要求、资源能源利用指标、产品指标、污染物产生指标、废物回收利用指标和环境管理要求。本标准适用于钢铁行业具有烧结生产工艺企业的清洁生产审核和清洁生产潜力与机会的判断、清洁生产绩效评定和清洁生产绩效公告制度，也适用于环境影响评价和排污许可证等环境管理制度。', 'http://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/other/qjscbz/200804/t20080414_121139.shtml', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (126, '钢铁', '中国', '清洁生产标准钢铁行业（高炉炼铁）', 'HJ/T 427-2008', '否', '本标准将清洁生产指标分为六类，即生产工艺与装备要求、资源能源利用指标、产品指标、污染物产生控制指标、废物回收利用指标和环境管理要求。本标准适用于钢铁行业具有高炉炼铁生产工艺企业的清洁生产审核和清洁生产潜力与机会的判断、清洁生产绩效评定和清洁生产绩效公告制度，也适用于环境影响评价和排污许可证等环境管理制度。', 'http://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/other/qjscbz/200804/t20080414_121140.shtml', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (127, '钢铁', '中国', '清洁生产标准钢铁行业（炼钢）', 'HJ/T 428-2008', '否', '本标准将清洁生产指标分为六类，即生产工艺与装备要求、资源能源利用指标、产品指标、污染物产生控制指标、废物回收利用指标和环境管理要求。本标准适用于钢铁行业具有炼钢生产工序的钢铁企业的清洁生产审核和清洁生产潜力与机会的判断、清洁生产绩效评定和清洁生产绩效公告制度，也适用于环境影响评价和排污许可证等环境管理制度。', 'http://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/other/qjscbz/200804/t20080414_121141.shtml', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (128, '钢铁', '中国', '清洁生产标准钢铁行业（钛合金）', 'HJ 470-2009', '否', ' 本标准规定了在达到国家和地方污染物排放标准的基础上，根据当前的行业技术、装备水平和管理水平，钢铁行业铁合金企业清洁生产的一般要求。本标准共分为三级，一级代表国际清洁生产先进水平，二级代表国内清洁生产先进水平，三级代表国内清洁生产基本水平。随着技术的不断进步和发展，本标准将适时修订。本标准规定了钢铁行业铁合金企业清洁生产的一般要求。本标准将钢铁行业铁合金企业清洁生产指标分为四类，即生产工艺与装备要求、资源与能源利用指标、废物回收利用指标和环境管理要求。本标准适用于采用电炉法生产硅铁、高碳锰铁、锰硅合金、中低碳锰铁、高碳铬铁和中低微碳铬铁共六个品种产品铁合金企业的清洁生产审核和清洁生产潜力与机会', 'http://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/other/qjscbz/200904/t20090414_150411.shtml', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (129, '钢铁', '中国', '钢铁行业（烧结、球团）清洁生产评价指标体系', null, '是', '该体系对于钢铁行业生产工序产生的颗粒物排放量、二氧化硫、氮氧化物排放量等进行了指标规定，此外还对水污染物排放标准进行了说明。', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (130, '钢铁', '中国', '钢铁行业（高炉炼铁）清洁生产评价指标体系', null, '是', '本指标体系依据综合评价指数总得分值将企业清洁生产水平分为三级，Ⅰ级代表国际清洁生产领先水平，Ⅱ级代表国内清洁生产先进水平，Ⅲ级代表国内清洁生产水平一般水平。', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (131, '钢铁', '中国', '钢铁行业（炼钢）清洁生产评价指标体系', null, '是', '本指标体系依据综合评价指数总得分值将企业清洁生产水平分为三级，Ⅰ级代表国际清洁生产领先水平，Ⅱ级代表国内清洁生产先进水平，Ⅲ级代表国内清洁生产水平一般水平。', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (132, '钢铁', '中国', '钢铁行业（钢延压加工）清洁生产评价指标体系', null, '是', '本指标体系依据综合评价指数总得分值将企业清洁生产水平分为三级，Ⅰ级代表国际清洁生产领先水平，Ⅱ级代表国内清洁生产先进水平，Ⅲ级代表国内清洁生产水平一般水平。', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (133, '钢铁', '中国', '钢铁行业（钛合金）清洁生产评价指标体系）', null, '是', '本指标体系依据综合评价指数总得分值将企业清洁生产水平分为三级，Ⅰ级代表国际清洁生产领先水平，Ⅱ级代表国内清洁生产先进水平，Ⅲ级代表国内清洁生产水平一般水平。', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (134, '钢铁', '中国', '粗钢生产主要工序单位产品能源消耗限额', 'GB21256-2013', '是', '本标准规定了粗钢生产主要工序单位产品能源消耗限额的限定值、准入值和先进值的技术要求、统计范围和计算方法及节能措施。', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (135, '钢铁', '中国', '铁合金单位产品能源消耗限额', 'GB21341-2017', '是', '本标准规定了铁合金单位产品能源消耗限额等术语和定义、技术要求、统计范围、计算方法。', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (136, '钢铁', '中国', '铁矿采选工业污染物排放标准', 'GB28661-2012', '是', '本标准规定了铁矿采选生产企业或生产设施的水污染物和大气污染物排放限值、监测和监控要求，以及标准的实施与监督等相关规定。本标准适用于现有铁矿采选生产企业或生产设施的水污染物和大气污染物排放管理，以及铁矿采选工业建设项目的环境影响评价、环境保护设施设计、环境保护工程竣工验收及其投产后的水污染物和大气污染物排放管理。', 'https://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/shjbh/swrwpfbz/201207/t20120731_234139.shtml', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (137, '钢铁', '斯洛文尼亚', '关于从轻合金、黑色金属和钢铁生产设施向大气排放物质的法令', null, '是', '本条例规定，用于熔化、熔化、保持温度和铸造灰铸铁、铁和钢合金（以下简称"铁铸造厂"） 的装置：

• 废气中某些物质的具体限值，

• 减少向空气中排放物质的措施，

• 将生产灰铸铁、铁和钢合金的现有装置改编为本条例。', 'http://extwprlegs1.fao.org/docs/html/slv130513.htm', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (138, '钢铁', '斯洛文尼亚', '	关于从铸铁、钢铁合金铸造厂向空气中排放物质的规定', null, '是', '该文件规定了与铸铁、钢铁合金铸造厂向空气中排放物质有关的具体排放限值废气中的某些物质；与减少排放到空气中有关的措施；改造现有设施生产铸铁、钢铁合金的条件。', 'http://extwprlegs1.fao.org/docs/html/slv97922.htm', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (139, '钢铁', '斯洛文尼亚', '钢铁生产和加工工厂排放废水中物质排放的规定', null, '是', '斯洛文尼亚共和国政府的这项条例由十条和两个附件组成，规定了有关从处理钢铁生产和加工的工业工厂排放废水时排放物质和热量的规定。该条例特别规定了废水的限值和与减少排放有关的具体措施。', 'http://extwprlegs1.fao.org/docs/html/slv97930.htm', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (140, '钢铁', '乌克兰', '《钢铁制造设备（安装）允许排放污染物的技术规范条例》（初级和二级熔炼）', null, '是', '该条例规定了用于制造或制造钢铁（初级和二级熔炼）的设备（装置）排放污染物的最大允许限值，其生产率超过每小时2.5吨（安装钢的气氧精炼）。它还规定了有害物质在排放中的浓度限制。这些技术规范为允许向大气中排放污染物制定了现行和长期标准。', 'http://extwprlegs1.fao.org/docs/pdf/ukr171887.pdf', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (141, '钢铁', '阿尔巴尼亚', '用于确定某些类型的金属废料何时不再是废物的标准', null, '是', '该法规规定了用于确定铁、钢和铝废料何时不再被视为废物的标准。该条例将欧洲委员会第 333/2011 号条例完全转化为国家法律。处理符合性声明的规则以及废物中有机污染物和危险物质的允许百分比在法规所附的单独附件中规定。', 'http://extwprlegs1.fao.org/docs/pdf/alb137760.pdf', null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (142, '水泥', '中国', '清洁生产标准 水泥工业', 'HJ467-2009', '否', null, null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (143, '水泥', '中国', '《建材工业大气污染物排放标准》(山东)', 'DB372373-2018', '是', '本标准规定了山东省水泥大气污染物的排放限值和监测要求，以及标准的实施与监督等有关要求。 本标准适用于山东省现有水泥工业企业的大气污染物排放管理，以及新建、改建、扩建项目的环境影响评价、环境保护设施设计、竣工环境保护验收、排污许可及其投产后的大气污染物排放管理。 利用水泥生产设施协同处置危险废物、生活垃圾等，除执行本标准外，还应同时满足《水泥窑协同处置固体废物污染控制标准》等相关标准的规定。', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (144, '水泥', '中国', '水泥工厂脱硝工程技术规范', 'GB 51045 - 2014', '是', '适用于新型干法水泥熟料生产线新建、改建和扩建的脱硝工程的设计、施工、验收及运行维护', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (145, '水泥', '中国', '危险废物(含医疗废物)焚烧处置设施二恶英排放监测技术规范', 'HJ/T365-2007', '是', '规定了危险废物焚烧处置设施二恶英排放检测的点位布设、采样时的运行工况、采样器材、分析方法、质量保证和质量控制、数据处理、结果表达和监测报告等技术要求。', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (146, '水泥', '中国', '中华人民共和国地质矿产行业标准水泥灰岩绿色矿山建设规范 ', 'DZ/T0318-2018', '是', '规定了水泥灰岩绿色矿山矿区环境、资源开发方式、资源综合利用、节能减排、科技创新与数字化矿山、企业管理与企业形象方面的基本要求', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (147, '水泥', '中国', '水泥工业大气污染物排放标准', 'GB 4915-2013', '是', '本标准规定了水泥制造企业（含独立粉磨站）、水泥原料矿山、散装水泥中转站、水泥制品企业及其生产设施的大气污染排放限值、监测和监督管理要求。', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (148, '水泥', '中国', '水泥工厂环境保护设施设计标准', 'GB/T 50558-2019', '是', '适用于水泥工厂和粉磨站新建、扩建和改建项目环境保护设施设计。', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (149, '水泥', '中国', '水泥工厂职业安全卫生设计规范', 'GB 50577-2010', '是', '适用于水泥工厂新建、改建和扩建生产线工程设计中的劳动安全、职业卫生设计。', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (150, '水泥', '中国', '水泥生产企业防尘防毒技术规范 ', 'AQ/T4247-2015', '是', '规定了水泥生产企业尘毒防治的基本要求、选址与布局、工艺过程工程防护、个人防护措施、管理措施、事故应急处置措施、职业健康监护和职业卫生培训等要求', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (151, '水泥', '中国', '水泥生产防尘技术规程', 'GB/T16911-2008', '是', '规定了水泥生产企业厂址选择和厂房设计的防尘要求、工艺设计的防尘要求、车间防尘措施、产尘工序的防尘措施，个体防护和防尘管理。', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (152, '水泥', '中国', '水泥窑协同处置固体废物污染控制标准', 'GB 30485-2013_2500', '是', '规定了协同处置固体废物水泥窑的设施技术要求、入窑废物特性要求、运行技术要求、污染物排放限值、生产的水泥产品污染物控制要求、监测和监督管理要求。', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (153, '水泥', '中国', '污染源源强核算技术指南 水泥工业', 'HJ 886—2018', '是', '规定了水泥工业污染源源强核算的程序、方法及选取原则、内容和要求', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (154, '水泥', '中国', '温室气体排放核算与报告要求：水泥生产企业', 'GB/T 32151', '是', '规定了水泥生产企业温室气体排放量的核算和报告相关的术语、核算边界、核算步骤与核算方法、数据质量管理、报告内容和格式等内容。', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (155, '水泥', '中国', '环境标志产品技术要求 刚性防水材料', 'HJ456-2009', '是', '规定了刚性防水材料环境标志产品的术语和定义、基本要求、技术内容和检验方法', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (156, '水泥', '中国', '车间空气中呼吸性水泥粉尘卫生标准 ', 'GB 16238-1996  ', '是', '规定了车间空气中呼吸性水泥粉尘最高容许浓度及其监测检验方法。', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (157, '水泥', '中国', '水泥行业清洁生产评价指标体系', '三部委 2014年 第3号', '是', '规定了水泥行业企业清洁生产的要求，主要包括了生产工艺及装备指标、资源能耗指标、资源综合利用指标、污染物产生指标、产品特征指标和清洁生产管理指标等六类', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (158, '水泥', '中国', '《水泥工业污染防治技术政策》', '环境保护部  2013 年 第 31 号 ', '是', '提出了水泥工业污染防治可采取的技术路线、原则和方法，包括源头控制、大气污染物排放控制、利用水泥生产设施协同处置固体废物、其他污染物排放控制、研发新技术和新材料等内容。', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (159, '水泥', '中国', '水泥行业清洁生产技术推行方案', '工信部', '是', '要求在水泥行业重点推广水泥窑氮氧化物减排技术、水泥窑协同处置废弃物技术以及水泥窑窑衬使用无铬耐火材料（砖）等技术。', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (160, '水泥', '中国', '“十四五”循环经济发展规划的通知', '国家发展改革委', '是', '通知中有关水泥行业内容如下：强化重点行业清洁生产。依法在“双超双有高耗能”行业实施强制性清洁生产审核，引导其他行业自觉自愿开展审核。进一步规范清洁生产审核行为，提高清洁生产审核质量。推动石化、化工、焦化、水泥、有色、电镀、印染、包装印刷等重点行业“一行一策”制定清洁生产改造提升计划。加快清洁生产技术创新、成果转化与标准体系建设，建立健全差异化奖惩机制，探索开展区域、工业园区和行业清洁生产整体审核试点示范工作。推进城市废弃物协同处置。完善政策机制和标准规范，推动协同处置设施参照城市环境基础设施管理，保障设施持续稳定运行。通过市场化方式确定城市废弃物协同处置付费标准，有序推进水泥窑、冶炼窑炉协同处', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (161, '水泥', '欧盟', '固定源排放--能源密集型行业温室气体排放的确定--第三部分：水泥行业', 'EN 19694-3-2016', '是', '本欧洲标准规定了计算水泥行业温室气体排放的统一方法', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (162, '水泥', '欧盟', '水泥和建筑石灰 - 环境产品声明 - 补充EN 15804的产品类别规则', 'EN 16908-2017', '是', '该产品特性要求主要用于创建水泥和建筑石灰的从摇篮到坟墓的环境标志认证', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (163, '水泥', '俄罗斯', '工业生态控制最佳可得技术-水泥', 'GOST R 56828.45-2019 ', '是', '最佳可用技术. 水泥生产. 工业生态控制', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (164, '水泥', '奥地利标准化学会', '水泥工业空气污染物排放限制', 'OENORM M9451-1988', '是', '水泥行业的空气污染物排放限值', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (165, '水泥', '越南', '水泥生产空气质量排放标准', 'TCVN 7735-2007 ', '是', '空气质量.水泥制造业排放标准', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (166, '水泥', '印度', '水泥窑烟囱排放颗粒物排放限制', 'IS 10693 Pt.1-1983 ', '是', '硅酸盐水泥生产厂水泥窑烟囱/烟囱排放颗粒物的排放限值。', null, null, null);
INSERT INTO standard.detail (detail_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (167, '水泥', '肯尼亚', '水泥厂大气排放准则', 'KS EAS 750-2010', '是', '空气质量. 水泥厂排放空气质量的指南', null, null, null);