create table standardList
(
    standard_id   int auto_increment
        primary key,
    industry      varchar(50)  null,
    region        varchar(50)  not null,
    standard      varchar(200) null,
    number        varchar(100) null,
    effectiveness varchar(20)  null,
    scope         int          null
)DEFAULT  CHARSET=utf8;

INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (1, '造纸', '中国', '清洁生产标准造纸工业(漂白碱法蔗渣浆生产工艺)', 'HJ/T 317-2006', '是', 1);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (2, '造纸', '中国', '清洁生产标准造纸工业(漂白化学烧碱法麦草浆生产工艺)', 'HJ/T 339-2007', '是', 1);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (3, '造纸', '中国', '清洁生产标准造纸工业(硫酸盐化学木浆生产工艺)', 'HJ/T 340-2007', '是', 1);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (4, '造纸', '中国', '《清洁生产标准 造纸工业（废纸制浆）》', 'HJ 468—2009', '是', 1);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (5, '造纸', '中国', '制浆造纸行业现场环境监察指南（试行）', null, '是', 1);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (6, '造纸', '中国', '造纸行业木材制浆工艺污染防治可行技术指南（试行）', null, '是', 1);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (7, '造纸', '中国', '造纸行业非木材制浆工艺污染防治可行技术指南（试行）', null, '是', 1);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (8, '造纸', '中国', '造纸行业废纸制浆及造纸工艺污染防治可行技术指南（试行）', null, '是', 1);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (9, '造纸', '中国', '《制浆造纸工业水污染物排放标准》', 'GB 3544-2008 代替GB 3544-2001', '是', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (10, '造纸', '中国', '《进口废纸环境保护管理规定》', '国办发〔2017〕70号', '是', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (11, '造纸', '中国', '造纸工业污染防治技术政策', null, '是', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (12, '造纸', '中国', '《制浆造纸工业污染防治可行技术指南》', 'HJ 2302—2018', '是', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (13, '造纸', '美国', null, null, '是', 1);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (14, '造纸', '美国', '40 CFR ( 第 40条 -保护环境 )：第430部分——纸浆、纸张、纸板点源类别', 'RIN：2070-AJ44', '是', 1);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (15, '造纸', '美国', '纸浆、纸张和纸板排放指南', '联邦法规引文：
40 CFR Part 430', '是', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (16, '造纸', '美国', '纸浆和纸张生产 (MACT I & III)：源类别的有害空气污染物国家排放标准', '联邦法规引文：
40 CFR Part 63 Subpart S', '是', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (17, '造纸', '美国', '硫酸盐、苏打、亚硫酸盐、独立式半化学浆厂( MactⅡ)：化学回收燃烧源危险空气污染物国家排放标准', '联邦法规引文：
40 CFR Part 63 Subpart MM', '是', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (18, '造纸', '美国', '纸张和其他涂料：国家有害空气污染物排放标准', '联邦法规引文：
40 CFR Part 63 Subpart JJJJ', '是', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (19, '造纸', '欧盟', '纸浆、纸和纸板生产的最佳可用技术参考文件', '欧盟工业排放标准：2010/75/EU', '是', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (20, '造纸', '澳大利亚', '澳大利亚新漂白桉木硫酸盐纸浆厂的环境指南', null, null, 1);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (21, '造纸', '巴西', '第14.128号文件规定了国家有关材料回收利用的政策和适用于固体废物管理的经济和财政手段', null, '是', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (22, '造纸', '巴西', '巴西联邦污水标准', null, '否', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (23, '造纸', '芬兰', '芬兰林业的国家环境保护目标', null, '否', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (24, '造纸', '德国', '废纸回收条例', null, '是', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (25, '造纸', '德国', '德国制浆造纸工业废水排放标准', null, '否', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (26, '造纸', '法国', '法国化学纸浆厂废水中悬浮固体和耗氧物质的最大允许量', null, '否', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (27, '造纸', '印度尼西亚', '印度尼西亚制浆造纸工业废水质量标准', null, '否', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (28, '造纸', '加拿大', '纸浆和纸张的出水规定', 'SOR/92-269', '是', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (29, '造纸', '加拿大', '纸浆和造纸厂废水氯化二恶英和呋喃法规', 'SOR/92-267', '是', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (30, '造纸', '加拿大', '制浆造纸厂消泡剂和木片规定', 'SOR 2-268', '是', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (31, '造纸', '加拿大', '工业排放-氮氧化物和二氧化硫', 'O. Reg. 194/0', '是', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (32, '造纸', '加拿大', '家用包装和纸张管理规定', 'R.R.S. c. E-10.21 Reg. ', '是', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (33, '造纸', '加拿大', '环境管理和保护(总)规章', 'R.R.S. c. E-10.22 Reg. 1', '是', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (34, '造纸', '斯洛文尼亚', '纸浆生产废水排放中物质和热量排放的规定', null, '是', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (35, '造纸', '印度', '环境（保护）规则', null, '是', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (36, '造纸', '老挝', '工业手工业部长关于工厂废水排放的规定', null, '是', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (37, '造纸', '奥地利', '废水排放条例-纸业', null, '是', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (38, '造纸', '奥地利', '废水排放条例-纺织，皮革和纸张', null, '是', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (39, '造纸', '荷兰', '183号法令包含规则相对于包装，包装废弃物，纸张和纸板', null, '是', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (40, '造纸', '摩尔多瓦共和国', '第409号:修订环境保护法', null, '是', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (41, '造纸', '越南', '用于生产原料的进口废弃材料的环境保护条例', 'NO. 03/2004/QD-BTNMT ', '是', 3);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (42, '石化', '中国', '清洁生产标准   石油炼制业', 'HJ/T 125-2003', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (43, '石化', '中国', '石油炼制工业污染物排放标准', 'GB 31570-2015', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (44, '石化', '中国', '石油化学工业污染物排放标准', 'GB 31571-2015', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (45, '石化', '中国', '清洁生产评价指标体系 石油炼制业', 'DB11／T 1157-2015', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (46, '石化', '中国', '石化行业能源消耗统计指标及计算方法 炼油', 'NB/SH/T 5001.1-2013', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (47, '石化', '中国', '脸油单位产品能源消耗限额', 'GB 30251-2013', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (48, '石化', '中国', '清洁生产标准 基本化学原料制造业 (环氧乙烷/乙二醇)', 'HJ/T 190-2006', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (49, '石化', '中国', '清洁生产标准 石油炼制业（沥青）', 'HJ 443-2008', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (50, '石化', '中国', '清洁生产标准 氯碱工业（聚氯乙烯）', 'HJ 476-2009', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (51, '石化', '中国', '清洁生产标准 氯碱工业（烧碱）', ' HJ 475－2009', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (52, '石化', '中国', '石油炼制工业废气治理工程技术规范', ' HJ 1094-2020', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (53, '石化', '中国', '污染源源强核算技术指南 石油炼制工业', 'HJ 982—2018', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (54, '石化', '中国', '排污单位自行监测技术指南 石油化学工业', 'HJ 947-2018', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (55, '石化', '中国', '石油炼制工业废水治理工程技术规范', 'HJ 2045-2014', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (56, '石化', '中国', '环境影响评价技术导则 石油化工建设项目', 'HJ/T 89-2003', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (57, '石化', '中国', '环境标志产品技术要求 塑料包装制品', ' HJ 209-2017', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (58, '石化', '中国', '废塑料回收与再生利用污染控制技术规范(试行)', 'HJ/T 364-2007', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (59, '石化', '中国', '环境标志产品技术要求 泡沫塑料', 'HJ/T 233-2006', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (60, '石化', '中国', '环境标志产品技术要求 塑料门窗', 'HJ/T 237-2006', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (61, '石化', '国际标准化组织', '石油、石化和天然气行业 - 特定部门的质量管理系统对产品和服务供应组织的要求', 'ISO 29001：2020', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (62, '石化', '国际标准化组织', ' 能源管理系统 - 使用指南要求', 'ISO 50001：2018', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (63, '石化', '国际标准化组织', '能源管理系统 - ISO 50001 能源管理系统的实施、维护和完善指南', 'ISO 50004：2020', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (64, '石化', '国际标准化组织', '能源审计 - 使用指南要求', 'ISO 50002：2014', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (65, '石化', '国际标准化组织', '环境管理系统 - 使用指南要求', 'ISO 14001:2015', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (66, '石化', '国际标准化组织', '环境管理 - 环境绩效评估指南', 'ISO 14031：2013', '否', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (67, '石化', '国际标准化组织', '环境管理 - 环境绩效评估指南', 'ISO 14031：2021', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (68, '石化', '国际标准化组织', '塑料 - 塑料废物回收和再利用指南', 'ISO 15270:2008', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (69, '石化', '世界银行', '环境，健康和安全指南-石油炼制业', null, '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (70, '石化', '欧盟', '工业排放指令', '2010/75 / EU', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (71, '石化', '欧盟', '矿物石油和天然气精炼的最佳可用技术 （BAT） 参考文档。2010/75/欧盟工业排放指令（综合污染预防和控制）', 'JRC94879', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (72, '石化', '欧盟', '塑料袋指令', '(EU) 2015/720', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (73, '石化', '欧盟', '电子电器设备废弃物指令', '2012/19/EU', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (74, '石化', '美国', '环境保护', null, '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (75, '石化', '美国', '节约电力和水资源', null, '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (76, '石化', '伊朗', '确定空气污染物允许限值的决议', null, '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (77, '石化', '印度尼西亚', '国家环境事务部长关于上游石化工业企业和/或活动的废水质量标准的第8/2007号条例', null, '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (78, '石化', '安哥拉', '石油化工和生物燃料精炼国家方向条例', ' NO. 185/14 ', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (79, '石化', '安哥拉', '适用于与石油产品有关的任何活动的法律框架', 'NO. 132/13 ', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (80, '石化', '安哥拉', '设立石油产品管理机构', 'NO. 133/13', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (81, '石化', '安哥拉', '批准关于原油精炼和石油产品的运输、储存、贸易和供应的立法', 'NO. 28/11', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (82, '石化', '孟加拉国', '石油2016年法案', 'NO. 3 of 2016', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (83, '石化', '葡萄牙', '关于国家石油系统组织和运作的总体基础的第31/2006号法令', 'NO. 31/2006', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (84, '石化', '印度', '《石油和天然气管制委员会法》', 'NO. 19 of 2006', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (85, '石化', '埃塞俄比亚', '石油业务公告', 'NO. 295/1986', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (86, '石化', '澳大利亚', '《产品管理法》（石油）', 'Act 2000', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (87, '石化', '卡波维德', '规范国家石油系统', 'NO. 56/2010 ', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (88, '石化', '阿塞拜疆', '关于禁止排放工业污水类型的企业第122号部长令', 'NO.122', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (89, '石化', '瑞典', '关于大型焚烧厂的条例', '2013:252', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (90, '石化', '开曼群岛（英国）', '《燃料市场监管法》', 'NO. 20 of 2017', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (91, '纺织', '中国', '清洁生产标准纺织业(棉印染)', 'HJ/T185-2006', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (92, '纺织', '中国', '清洁生产标准化纤行业(氨纶)', 'HJ/T359-2007', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (93, '纺织', '中国', '清洁生产标准化纤行业(涤纶)', 'HJ/T429-2008', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (94, '纺织', '中国', '牛仔服装洗水行业清洁生产评价指标体系', 'T/GDTEX 05-2019', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (95, '纺织', '中国', '绿色设计产品评价技术规范 羊绒针织制品', 'T/CAB 0025-2017', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (96, '纺织', '中国', '绿色设计产品评价技术规范 再生涤纶', 'T/CNTAC 52-2020', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (97, '纺织', '中国', '绿色设计产品评价技术规范 户外多用途面料', 'T/CAB 0034-2018', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (98, '纺织', '中国', '绿色设计产品评价技术规范 丝绸制品', 'FZ/T 07003-2019', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (99, '纺织', '中国', '绿色设计产品评价技术规范 涤纶磨毛印染布', 'T/CAB 0030-2018', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (100, '纺织', '中国', '绿色设计产品评价技术规范 巾被织物', 'T/CNTAC 34-2019', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (101, '纺织', '中国', '绿色设计产品评价技术规范 毛精纺产品', 'T/CNTAC 39-2019', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (102, '纺织', '中国', '绿色设计产品评价技术规范 羊绒产品', 'T/CNTAC 38-2019', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (103, '纺织', '中国', '绿色设计产品评价技术规范 布艺类产品', 'T/CNTAC 41-2019', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (104, '纺织', '中国', '绿色设计产品评价技术规范 婴幼儿湿巾', 'T/CAB 0052-2019', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (105, '纺织', '中国', '绿色设计产品评价技术规范 色纺纱', 'T/CNTAC 51-2020', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (106, '纺织', '中国', '绿色设计产品评价技术规范 针织印染布', 'T/CNTAC 40-2019', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (107, '纺织', '中国', '绿色设计产品评价技术规范 皮服', 'T/CNTAC 35-2019', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (108, '纺织', '中国', '纺织行业绿色工厂评价导则', 'FZ/T 07004-2019', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (109, '纺织', '中国', '涤纶长丝织物行业印染绿色工厂评价要求', 'T/CAB 2018-2019', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (110, '纺织', '中国', '纺织行业绿色供应链管理企业评价指标体系', 'FZ/T 07005-2020', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (111, '纺织', '中国', '纺织染整工业废水治理工程技术规范', 'HJ 471-2020', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (112, '纺织', '中国', '绿色产品评价 纺织产品', 'GB/T 35611-2017', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (113, '钢铁', '中国', '铸造工业大气污染物排放标准', 'GB39726-2020', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (114, '钢铁', '中国', '炼钢工业大气污染物排放标准', 'GB28664-2012', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (115, '钢铁', '中国', '轧钢工业大气污染物排放标准', 'GB28665-2012', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (116, '钢铁', '中国', '钢铁工业水污染物排放标准', 'GB13456-2012', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (117, '钢铁', '中国', '钢铁企业节能设计规范', 'GB50632-2010', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (118, '钢铁', '中国', '工业企业温室气体排放核算和报告通则', 'GB/T 32150—2015', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (119, '钢铁', '中国', '温室气体排放核算与报告要求 第5部分:钢铁生产企业', 'GB/T 32151—2015', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (120, '钢铁', '中国', '基于项目的温室气体减排量评估技术规范 钢铁行业余能利用', 'GB/T 33755—2017', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (121, '钢铁', '中国', '钢铁企业温室气体排放核查技术规范', 'RB/T 251—2018', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (122, '钢铁', '中国', '清洁生产标准 钢铁行业', 'HJ/T 189-2006', '否', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (123, '钢铁', '中国', '钢铁行业清洁生产评价指标体系（试行）', null, '否', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (124, '钢铁', '中国', '清洁生产标准钢铁行业（中厚板轧钢）', 'HJ/T 318-2006', '否', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (125, '钢铁', '中国', '清洁生产标准钢铁行业（烧结）', 'HJ/T 426-2008', '否', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (126, '钢铁', '中国', '清洁生产标准钢铁行业（高炉炼铁）', 'HJ/T 427-2008', '否', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (127, '钢铁', '中国', '清洁生产标准钢铁行业（炼钢）', 'HJ/T 428-2008', '否', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (128, '钢铁', '中国', '清洁生产标准钢铁行业（钛合金）', 'HJ 470-2009', '否', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (129, '钢铁', '中国', '钢铁行业（烧结、球团）清洁生产评价指标体系', null, '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (130, '钢铁', '中国', '钢铁行业（高炉炼铁）清洁生产评价指标体系', null, '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (131, '钢铁', '中国', '钢铁行业（炼钢）清洁生产评价指标体系', null, '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (132, '钢铁', '中国', '钢铁行业（钢延压加工）清洁生产评价指标体系', null, '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (133, '钢铁', '中国', '钢铁行业（钛合金）清洁生产评价指标体系）', null, '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (134, '钢铁', '中国', '粗钢生产主要工序单位产品能源消耗限额', 'GB21256-2013', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (135, '钢铁', '中国', '铁合金单位产品能源消耗限额', 'GB21341-2017', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (136, '钢铁', '中国', '铁矿采选工业污染物排放标准', 'GB28661-2012', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (137, '钢铁', '斯洛文尼亚', '关于从轻合金、黑色金属和钢铁生产设施向大气排放物质的法令', null, '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (138, '钢铁', '斯洛文尼亚', '	关于从铸铁、钢铁合金铸造厂向空气中排放物质的规定', null, '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (139, '钢铁', '斯洛文尼亚', '钢铁生产和加工工厂排放废水中物质排放的规定', null, '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (140, '钢铁', '乌克兰', '《钢铁制造设备（安装）允许排放污染物的技术规范条例》（初级和二级熔炼）', null, '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (141, '钢铁', '阿尔巴尼亚', '用于确定某些类型的金属废料何时不再是废物的标准', null, '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (142, '水泥', '中国', '清洁生产标准 水泥工业', 'HJ467-2009', '否', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (143, '水泥', '中国', '《建材工业大气污染物排放标准》(山东)', 'DB372373-2018', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (144, '水泥', '中国', '水泥工厂脱硝工程技术规范', 'GB 51045 - 2014', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (145, '水泥', '中国', '危险废物(含医疗废物)焚烧处置设施二恶英排放监测技术规范', 'HJ/T365-2007', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (146, '水泥', '中国', '中华人民共和国地质矿产行业标准水泥灰岩绿色矿山建设规范 ', 'DZ/T0318-2018', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (147, '水泥', '中国', '水泥工业大气污染物排放标准', 'GB 4915-2013', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (148, '水泥', '中国', '水泥工厂环境保护设施设计标准', 'GB/T 50558-2019', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (149, '水泥', '中国', '水泥工厂职业安全卫生设计规范', 'GB 50577-2010', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (150, '水泥', '中国', '水泥生产企业防尘防毒技术规范 ', 'AQ/T4247-2015', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (151, '水泥', '中国', '水泥生产防尘技术规程', 'GB/T16911-2008', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (152, '水泥', '中国', '水泥窑协同处置固体废物污染控制标准', 'GB 30485-2013_2500', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (153, '水泥', '中国', '污染源源强核算技术指南 水泥工业', 'HJ 886—2018', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (154, '水泥', '中国', '温室气体排放核算与报告要求：水泥生产企业', 'GB/T 32151', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (155, '水泥', '中国', '环境标志产品技术要求 刚性防水材料', 'HJ456-2009', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (156, '水泥', '中国', '车间空气中呼吸性水泥粉尘卫生标准 ', 'GB 16238-1996  ', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (157, '水泥', '中国', '水泥行业清洁生产评价指标体系', '三部委 2014年 第3号', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (158, '水泥', '中国', '《水泥工业污染防治技术政策》', '环境保护部  2013 年 第 31 号 ', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (159, '水泥', '中国', '水泥行业清洁生产技术推行方案', '工信部', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (160, '水泥', '中国', '“十四五”循环经济发展规划的通知', '国家发展改革委', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (161, '水泥', '欧盟', '固定源排放--能源密集型行业温室气体排放的确定--第三部分：水泥行业', 'EN 19694-3-2016', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (162, '水泥', '欧盟', '水泥和建筑石灰 - 环境产品声明 - 补充EN 15804的产品类别规则', 'EN 16908-2017', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (163, '水泥', '俄罗斯', '工业生态控制最佳可得技术-水泥', 'GOST R 56828.45-2019 ', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (164, '水泥', '奥地利标准化学会', '水泥工业空气污染物排放限制', 'OENORM M9451-1988', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (165, '水泥', '越南', '水泥生产空气质量排放标准', 'TCVN 7735-2007 ', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (166, '水泥', '印度', '水泥窑烟囱排放颗粒物排放限制', 'IS 10693 Pt.1-1983 ', '是', null);
INSERT INTO standard.standardList (standard_id, industry, region, standard, number, effectiveness, scope) VALUES (167, '水泥', '肯尼亚', '水泥厂大气排放准则', 'KS EAS 750-2010', '是', null);