create table detailEng
(
    detailEng_id  int auto_increment
        primary key,
    industry      varchar(50)  null,
    region        varchar(50)  null,
    standard      varchar(200) null,
    number        varchar(200) null,
    effectiveness varchar(20)  null,
    abstracts     varchar(300) null,
    link          varchar(200) null,
    scope         int          null,
    year          int          null
);

INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (1, 'Paper  Industry', 'China', 'Cleaner production standard— Process of bleached alkali bagasse pulp in paper industry', 'HJ/T 317-2006', 'YES', 'This standard specifies the requirements for cleaner production in the paper industry ( Process of bleached alkali bagasse pulp).', 'https://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/other/qjscbz/200611/t20061129_96653.shtml', 1, 2006);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (2, 'Paper  Industry', 'China', 'Cleaner production standard–Production of bleached soda straw pulp, paper industry', 'HJ/T 339-2007', 'YES', 'The standard provides general requirements for cleaner production in paper industry ( production of bleached soda straw pulp ) .', null, 1, 2007);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (3, 'Paper  Industry', 'China', 'Cleaner production standard–Production of kraft chemical wood-pulp, paper industry', 'HJ/T 340-2007', 'YES', 'The standard provides general requirements for cleaner production in paper industry ( production of kraft chemical wood-pulp ) .', 'https://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/other/qjscbz/200704/t20070403_102432.shtml', 1, 2007);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (4, 'Paper  Industry', 'China', 'Cleaner production standard Waste paper pulping（paper industry）', 'HJ 468—2009', 'YES', 'The standard provides general requirements for cleaner production in paper industry ( waste paper pulping ) .', 'https://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/other/qjscbz/200904/t20090415_150469.htm', 1, 2009);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (5, 'Paper  Industry', 'China', 'Guidelines for Environmental Monitoring in Pulp and Paper Industry ( Trial )', null, 'YES', 'Guidelines regulate on-site environmental monitoring in pulp and paper enterprises.', 'https://www.mee.gov.cn/gkml/hbb/bgt/201011/t20101101_196957.htm', 1, 2010);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (6, 'Paper  Industry', 'China', 'Technical Guide for Pollution Control of Wood Fiber Pulping in Paper Industry ( Trial )', null, 'YES', null, 'https://www.mee.gov.cn/gkml/hbb/bgg/201312/t20131231_265891.htm ', 1, 2013);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (7, 'Paper  Industry', 'China', 'Technical Guide for Pollution Control of NOn-Wood Fiber Pulping in Paper Industry ( Trial )', null, 'YES', null, 'https://www.mee.gov.cn/gkml/hbb/bgg/201312/t20131231_265891.htm ', 1, 2013);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (8, 'Paper  Industry', 'China', 'Technical Guide for Pollution Control of Waste Paper Pulp and Papermaking Processes in Papermaking Industry ( Trial )', null, 'YES', null, 'https://www.mee.gov.cn/gkml/hbb/bgg/201312/t20131231_265891.htm ', 1, 2013);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (9, 'Paper  Industry', 'China', 'Discharge standard of water pollutants for pulp and paper industry', 'GB 3544 - 2008 replaced GB 3544 - 2001', 'YES', 'The standard specifies the emission limits of water pollutants for pulp and paper enterprises or production facilities.', 'https://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/shjbh/swrwpfbz/200807/t20080701_124695.htm ', 3, 2008);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (10, 'Paper  Industry', 'China', 'Regulations on Environmental Protection of Imported Waste Paper', 'promulgated by the State Council〔2017〕NO.70', 'YES', 'The standard specifies the general requirements for environmental management of imported waste paper.', 'https://www.mee.gov.cn/gkml/hbb/bwj/201712/t20171218_428134.htm ', 3, 2017);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (11, 'Paper  Industry', 'China', 'Technical Policy for Pollution Control in Paper Industry', null, 'YES', null, 'https://www.mee.gov.cn/gkml/hbb/bgg/201708/t20170808_419350.htm ', 3, 2017);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (12, 'Paper  Industry', 'China', 'Guideline for available techniques of pollution prevention and control for pulp and paper industry', 'HJ 2302—2018', 'YES', 'The standard specifies the feasible techNOlogy for the prevention and control of wastewater, waste gas, solid waste and NOise pollution in pulp and paper industry.', 'https://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/wrfzjszc/201801/t20180112_429627.shtml', 3, 2018);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (13, 'Paper  Industry', 'USA', '40 CFR(TITLE 40—Protection of Environment)：PART 430—THE PULP, PAPER, AND PAPERBOARD POINT SOURCE CATEGORY', null, 'YES', 'Statement of Environmental Protection Categories ( Pulp, Paper and Paperboard Point Sources ) in the Electronic Code of State Regulation.', null, 1, 1998);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (14, 'Paper  Industry', 'USA', ' Formaldehyde Emissions from Pressed Wood Products', 'RIN：2070-AJ44', 'YES', 'Regulations on formaldehyde emission of wood products.', null, 1, 2016);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (15, 'Paper  Industry', 'USA', 'Pulp, Paper and Paperboard Effluent Guidelines', 'Citation of federal regulations:40 CFR Part 430', 'YES', 'Emission guidelines and standards for pulp, paper and paperboard.', null, 3, 1974);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (16, 'Paper  Industry', 'USA', 'Pulp and Paper Production (MACT I & III): National Emissions Standards for Hazardous Air Pollutants (NESHAP) for Source Categories', 'Citation of federal regulations:40 CFR Part 63 Subpart S', 'YES', 'Emission regulations on pulp production sources.', null, 3, 2001);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (17, 'Paper  Industry', 'USA', 'Kraft, Soda, Sulfite, and Stand-Alone Semichemical Pulp Mills (MACT II): National Emission Standards for Hazardous Air Pollutants (NESHAP) for Chemical Recovery Combustion Sources', 'Citation of federal regulations:40 CFR Part 63 Subpart MM', 'YES', 'Emission regulations on combustion sources in pulp mills.', null, 3, 2001);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (18, 'Paper  Industry', 'USA', 'Paper and Other Web Coating: National Emission Standards for Hazardous Air Pollutants (NESHAP)', 'Citation of federal regulations:40 CFR Part 63 Subpart JJJJ', 'YES', ' National Emission Standards for Air Pollutants from Paper and Surface Coatings', null, 3, 2002);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (19, 'Paper  Industry', 'European Union', 'Best Available Techniques (BAT) Reference Document for the Production of Pulp, Paper and Board. ', 'Industrial Emissions Directive 2010/75/EU', 'YES', null, 'https://op.europa.eu/en/publication-detail/-/publication/fcaab1a5-d287-40af-b21c-115e529685fc/language-en', 3, 2015);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (20, 'Paper  Industry', 'Australia', 'Environmental guidelines for new bleached eucalypt kraft pulp mills in Australia', null, null, null, null, 1, 1989);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (21, 'Paper  Industry', 'Brazil', 'Law NO. 14.128 providing for the State Policy on Recycling of Materials and the ecoNOmic and financial instruments applicable to the Management of Solid Waste', null, 'YES', 'This Law, consisting of 7 articles, provides for the State Policy on Recycling of Materials and the ecoNOmic and financial instruments applicable to the Management of Solid Waste. ', 'http://www.almg.gov.br/ ', 3, 2001);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (22, 'Paper  Industry', 'Brazil', 'Federal effluent standards in Brazil', null, 'NO', null, null, 3, 1993);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (23, 'Paper  Industry', 'Finland', 'The national goals for environmental protection by the forest industry in Finland', null, 'NO', null, null, 3, 1993);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (24, 'Paper  Industry', 'Germany', 'Waste Paper Collection Ordinance', null, 'YES', 'The Ordinance aims to promote high-quality recycling of waste paper through separate collection of waste paper within the frame of public waste disposal. ', 'http://www.hamburg.de/ ', 3, 2010);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (25, 'Paper  Industry', 'Germany', 'Effluent standards for pulp and paper industry in Germany', null, 'NO', null, null, 3, 1989);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (26, 'Paper  Industry', 'France', 'Maximum permitted amounts of suspended solids and oxygen-consuming substances in wastewaters from chemical pulp mills in France', null, 'NO', null, null, 3, 1993);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (27, 'Paper  Industry', 'Indonesia', 'Effluent quality standard for pulp and paper industry in Indonesia', null, 'NO', null, null, 3, 1991);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (28, 'Paper  Industry', 'Canada', 'The Pulp and Paper Effluent Regulations', 'SOR/92-269', 'YES', 'The regulations on some harmful substances related to wastewater from pulp and paper mills and off-site treatment facilities are stipulated, and a limited number of these harmful substances are authorized to be stored in some cases.', 'https://www.canada.ca/en/environment-climate-change/services/environmental-indicators/pulp-paper-effluent-quality.html', 3, 1992);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (29, 'Paper  Industry', 'Canada', 'Pulp and Paper Mill Effluent Chlorinated Dioxins and Furans Regulations', 'SOR/92-267', 'YES', 'Regulation on release of PCDDs and PCDFs from pulp and paper mill wastewater.', null, 3, 1992);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (30, 'Paper  Industry', 'Canada', 'Pulp and Paper Mill Defoamer and Wood Chip Regulation ', 'SOR 2-269', 'YES', 'Regulations relating to the production, import, sale, sale and use of defoamers containing dibenzofuran or dibenzo-p-dioxin in pulp and paper mills using chlorine bleaching processes and wood chips containing polypheNOls in all pulp and paper mills.', null, 3, 1992);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (31, 'Paper  Industry', 'Canada', 'Industry Emissions - Nitrogen Oxides and Sulphur Dioxide', 'O. Reg. 194/1', 'YES', 'Emission limits for nitrogen oxides and sulfur dioxide in pulp and paper industries.', null, 3, 2005);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (32, 'Paper  Industry', 'Canada', 'Household Packaging and Paper Stewardship Program Regulations ', 'R.R.S. c. E-10.22 Reg.', 'YES', 'This regulates for court packing and paper management plan', null, 3, 2013);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (33, 'Paper  Industry', 'Canada', 'Environmental Management and Protection (General) Regulations ', 'R.R.S. c. E-10.22 Reg. 2', 'YES', 'Requirements for pulp or paper mills, wood treatment facilities, wood products.', null, 3, 2014);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (34, 'Paper  Industry', 'Slovenia', 'Regulation on the emission of substances and heat in the discharge of waste water from the production of pulp', null, 'YES', 'This Regulation of the Government of the Republic of Slovenia, which is composed of 11 articles and two Annexes, establishes specific requirements concerning the emission of substances in the discharge of industrial waste water from plants dealing with the production of pulp and from facilities for ', 'http://www.pisrs.si/', 3, 2006);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (35, 'Paper  Industry', 'India', 'Environment (Protection) Third Amendment Rules', null, 'YES', 'Standards for emission or discharge of environmental pollutants shall be as specified in Schedules I to IV. The central government may prohibit or restrict the establishment of industries or the carrying out of specific processes or operations based on factors specified in Rule 5. ', 'http://envfor.nic.in/', 3, 1986);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (36, 'Paper  Industry', 'Lao', 'Provisions of the Minister of Industry-Handicraft on the discharge of Waste Water from Factories.', null, 'YES', 'Article 3 contains a list of substances that canNOt be discharged into the environment and public water sources. Article 4 establishes general and specific standards for factories, such as textile and garment factories, pulp and paper factories, paper mills, slaughterhouses. ', null, 3, 1994);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (37, 'Paper  Industry', 'Austria', 'Waste Water Emission Ordinance - Paper Industry', null, 'YES', 'An Ordinance limit the discharge of waste water from the Austrian paper industry into public waters; in particular, waste water containing polluting substances must be monitored and amounts curtailed. ', 'http://www.ris.bka.gv.at/ ', 3, 2000);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (38, 'Paper  Industry', 'Austria', 'Waste Water Emission Ordinance - Textile, Leather and Paper', null, 'YES', 'An Ordinance limit the discharge of waste water from the Austrian textile, leather and paper industry into public waters; in particular, waste water containing polluting substances must be monitored and amounts curtailed. ', 'http://www.ris.bka.gv.at/ ', 3, 2000);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (39, 'Paper  Industry', 'Netherlands', 'Decree NO. 183 containing rules relative to packing, packing waste, paper and cardboard', null, 'YES', 'This Decree contains rules relative the gathering, recycling and use of paper and cardboard packing and of paper and cardboard. It places obligations on importers and producers to use recycled paper and lays down percentages of NOxious substances such as lead that may be used in packing. The Decree ', 'http://www.overheid.nl/ ', 3, 2005);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (40, 'Paper  Industry', 'Moldova', 'Law NO. 409-XV amending Law on environmental protection', null, 'YES', 'The law regulates the use of recycled paper.', null, 3, 2004);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (41, 'Paper  Industry', 'Viet Nam', ' Environmental Protection Regulation applicable to discarded materials imported for use as production raw materials', 'NO. 03/2004/QD-BTNMT ', 'YES', 'The Decision provides for the Regulation of the Environment Protection when discarded raw materials (steel, copper, aluminium, zinc, glass, cardboard, paper, plastic etc.) is imported and used in the country as secondary materials NOt considered waste.

Full text
English', null, 3, 1993);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (42, 'Petrochemical', 'China', 'Cleaner production standard   Petroleum refinery industry', 'HJ/T 125-2003', 'YES', 'To implement the "Environmental Protection Law of the People''s Republic of China" and "The Cleaner Production Promotion Law of the People''s Republic of China", to further promote China''s clean production, prevent ecological damage, protect people''s health, promote ecoNOmic development, and provide t', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (43, 'Petrochemical', 'China', 'Emission standards of pollutants for petroleum refining industry', 'GB 31570-2015', 'YES', 'To implement the "Environmental Protection Law of the People''s Republic of China", "Water Pollution Prevention Law of the People''s Republic of China", "Air Pollution Prevention Law of the People''s Republic of China" and other laws and regulations, protect the environment, prevent and control polluti', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (44, 'Petrochemical', 'China', 'Emission standard of pollutants for petroleum chemistry industry', 'GB 31571-2015', 'YES', 'In order to implement the "Environmental Protection Law of the People''s Republic of China", "Water Pollution Prevention Law of the People''s Republic of China", "Air Pollution Prevention Law of the People''s Republic of China" and other laws and regulations, protect the environment, prevent pollution,', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (45, 'Petrochemical', 'China', 'Assessment indicator system of cleaner production for petroleum refinery industry', 'DB11／T 1157-2015', 'YES', 'This standard specifies the evaluation index system, evaluation methods, index calculations and data sources for cleaner production in the petroleum refining industry. This standard applies to the clean production audit, evaluation and performance acceptance of petroleum refining enterprises.', 'http://scjgj.beijing.gov.cn/', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (46, 'Petrochemical', 'China', 'Energy consumption statistics lindices and calculation methods for refinery in petrochemical industry', 'NB/SH/T 5001.1-2013', 'YES', 'This standard specifies the statistical indicators and calculation methods for energy consumption in oil refining production. This standard applies to the production of liquefied petroleum gas, propane, propylene, benzene, toluene, mixed xylene, gasoline, kerosene, diesel, fuel oil, lubricating oil ', 'http://www.nea.gov.cn/', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (47, 'Petrochemical', 'China', 'The NOrm of energy consumption per unit product for petroleum refining', 'GB 30251-2013', 'YES', 'This standard specifies the technical requirements, statistical scope and calculation method, energy conservation management and measures for the energy consumption quota of the unit product of the refinery. This standard is applicable to the production of gasoline, diesel, kerosene, lubricating oil', 'https://www.antpedia.com/standard/6804159.html', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (48, 'Petrochemical', 'China', 'Cleaner production standard- Basic chemical raw material industry (Ethylene oxide & ethylene glycol)', 'HJ/T 190-2006', 'YES', 'In order to implement the "Environmental Protection Law of the People''s Republic of China" and "The Cleaner Production Promotion Law of the People''s Republic of China", protect the environment, and provide technical support and guidance for basic chemical raw material manufacturing enterprises to ca', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (49, 'Petrochemical', 'China', 'Cleaner production standard Petroleum refinery industry（semi-asphaltic flux）', 'HJ 443-2008', 'YES', 'In order to implement the Environmental Protection Law of the People''s Republic of China and the Cleaner Production Promotion Law of the People''s Republic of China, protect the environment, and provide technical support and guidance for cleaner production in the petroleum refining industry (asphalt)', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (50, 'Petrochemical', 'China', 'Cleaner production standard Chlor-alkali industry(Polyvinyl Chloride)', 'HJ 476-2009', 'YES', 'In order to implement the "Environmental Protection Law of the People''s Republic of China" and "The Cleaner Production Promotion Law of the People''s Republic of China", protect the environment, and provide technical support and guidance for PVC production enterprises to carry out cleaner production,', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (51, 'Petrochemical', 'China', 'Cleaner production standard Chlor-alkali industry (Caustic soda)', ' HJ 475－2009', 'YES', 'In order to implement the Environmental Protection Law of the People''s Republic of China and the Cleaner Production Promotion Law of the People''s Republic of China, protect the environment, and provide technical support and guidance for the development of cleaner production by caustic soda enterpris', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (52, 'Petrochemical', 'China', 'Technical specifications for petroleum refining industry waste gases treatment', ' HJ 1094-2020', 'YES', 'In order to implement the "Environmental Protection Law of the People''s Republic of China" and "The Air Pollution Prevention Law of the People''s Republic of China" and other laws and regulations, prevent and control environmental pollution, improve the quality of the ecological environment, and stan', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (53, 'Petrochemical', 'China', 'Technical guidelines of accounting method for pollution source intensity Petroleum refining industry', 'HJ 982—2018', 'YES', 'To implement the Environmental Protection Law of the People’s Republic of China, the Environmental Impact Assessment Law of the People’s Republic of China, the Air Pollution Prevention and Control Law of the People’s Republic of China, the Water Pollution Prevention and Control Law of the People’s R', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (54, 'Petrochemical', 'China', 'Self-monitoring techNOlogy guidelines for pollution sources— Petroleum chemistry industry', 'HJ 947-2018', 'YES', 'In order to implement the Environmental Protection Law of the People''s Republic of China, the Water Pollution Prevention and Control Law of the People''s Republic of China, and the Air Pollution Prevention and Control Law of the People''s Republic of China, and to guide and standardize the self-monito', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (55, 'Petrochemical', 'China', 'Technical specifications for petroleum refining industry wastewater treatment', 'HJ 2045-2014', 'YES', 'In order to implement the "Environmental Protection Law of the People''s Republic of China" and "The Water Pollution Prevention Law of the People''s Republic of China", standardize the design, construction and operation management of wastewater treatment projects in the petroleum refining industry, pr', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (56, 'Petrochemical', 'China', 'Technical guldeline for environmental impact assessment Constructional project of petrochemical', 'HJ/T 89-2003', 'YES', 'This standard specifies the general principles, content and methods of environmental impact assessment of petrochemical construction projects (hereinafter referred to as construction projects). Petrochemical construction projects refer to construction projects that use petroleum and petroleum gas (i', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (57, 'Petrochemical', 'China', 'Technical requirement for environmental labeling products Plastic packaging products', ' HJ 209-2017', 'YES', 'In order to implement the "Environmental Protection Law of the People''s Republic of China", effectively use and save resources, and reduce the impact of plastic packaging products on the environment and human health, this standard is formulated. This standard puts forward environmental protection re', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (58, 'Petrochemical', 'China', 'Technical Specifications for Pollution Control during Collection and Recycle of Waste Plastics', 'HJ/T 364-2007', 'YES', 'In order to implement the "Environmental Protection Law of the People''s Republic of China" and the "Law of the People''s Republic of China on the Prevention and Control of Environmental Pollution Caused by Solid Wastes", in the process of recycling and recycling of waste plastics, this standard is fo', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (59, 'Petrochemical', 'China', 'Technical Requirement for Environmental Labeling Products–Foamed Plastics', 'HJ/T 233-2006', 'YES', 'In order to implement the "Environmental Protection Law of the People''s Republic of China" and reduce the impact of foam on the environment and human health during production and use, this standard is formulated. This standard restricts the use of foaming agents. This standard has made partial chang', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (60, 'Petrochemical', 'China', 'The Technical Requirement for Environmental Labeling Products–Plastic Doors and Windows', 'HJ/T 237-2006', 'YES', 'In order to implement the "Environmental Protection Law of the People''s Republic of China", reduce the impact of plastic doors and windows on the environment and human health in the production and use process, save energy, reduce environmental pollution, reduce raw material consumption, and improve ', 'https://www.mee.gov.cn/ywgz/fgbz/bz/', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (61, 'Petrochemical', 'ISO', 'Petroleum, petrochemical and natural gas industries — Sector-specific quality management systems — Requirements for product and service supply organizations', 'ISO 29001：2020', 'YES', 'This document defines quality management system requirements for product and service supply organizations to the petroleum, petrochemical and natural gas industries.

This document is written as a supplement to ISO 9001:2015. The supplementary requirements and guidance to ISO 9001:2015 have been dev', 'https://www.iso.org/home.html', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (62, 'Petrochemical', 'ISO', 'Energy management systems — Requirements with guidance for use', 'ISO 50001：2018', 'YES', 'This document specifies requirements for establishing, implementing, maintaining and improving an energy management system (EnMS). The intended outcome is to enable an organization to follow a systematic approach in achieving continual improvement of energy performance and the EnMS.

This document:
', 'https://www.iso.org/home.html', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (63, 'Petrochemical', 'ISO', 'Energy management systems — Guidance for the implementation, maintenance and improvement of an ISO 50001 energy management system', 'ISO 50004：2020', 'YES', 'This document gives practical guidelines and examples for establishing, implementing, maintaining and improving an energy management system (EnMS) in accordance with the systematic approach of ISO 50001:2018. The guidance in this document is applicable to any organization.

This document does NOt pr', 'https://www.iso.org/home.html', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (64, 'Petrochemical', 'ISO', 'Energy audits — Requirements with guidance for use', 'ISO 50002：2014', 'YES', 'ISO 50002:2014 specifies the process requirements for carrying out an energy audit in relation to energy performance. It is applicable to all types of establishments and organizations, and all forms of energy and energy use.

ISO 50002:2014 specifies the principles of carrying out energy audits, req', 'https://www.iso.org/home.html', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (65, 'Petrochemical', 'ISO', 'Environmental management systems — Requirements with guidance for use', 'ISO 14001:2015', 'YES', 'ISO 14001:2015 specifies the requirements for an environmental management system that an organization can use to enhance its environmental performance. ISO 14001:2015 is intended for use by an organization seeking to manage its environmental responsibilities in a systematic manner that contributes t', 'https://www.iso.org/home.html', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (66, 'Petrochemical', 'ISO', 'Environmental management — Environmental performance evaluation — Guidelines', 'ISO 14031：2013', 'NO', 'ISO 14031:2013 gives guidance on the design and use of environmental performance evaluation (EPE) within an organization. It is applicable to all organizations, regardless of type, size, location and complexity.

ISO 14031:2013 does NOt establish environmental performance levels.

The guidance in IS', 'https://www.iso.org/home.html', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (67, 'Petrochemical', 'ISO', 'Environmental management — Environmental performance evaluation — Guidelines', 'ISO 14031：2021', 'YES', 'This document gives guidelines for the design and use of environmental performance evaluation (EPE) within an organization. It is applicable to all organizations, regardless of type, size, location and complexity.

This document does NOt establish environmental performance levels. It is NOt intended', 'https://www.iso.org/home.html', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (68, 'Petrochemical', 'ISO', 'Plastics — Guidelines for the recovery and recycling of plastics waste', 'ISO 15270:2008', 'YES', 'ISO 15270:2008 provides guidance for the development of standards and specifications covering plastics waste recovery, including recycling. The standard establishes the different options for the recovery of plastics waste arising from pre-consumer and post-consumer sources. It also establishes the q', 'https://www.iso.org/home.html', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (69, 'Petrochemical', 'World Bank Group', 'E NVIRONMENTAL , H EALTH , AND S AFETY G UIDELINES FOR
P ETROLEUM R EFINING', null, 'YES', '1. The Environmental, Health, and Safety (EHS) Guidelines are technical reference documents withgeneral and industry-specific examples of Good International Industry Practice (GIIP). 1 When one or moremembers of the World Bank Group are involved in a project, these EHS Guidelines are applied as requ', 'www.ifc.org/ehsguidelines.', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (70, 'Petrochemical', 'EU', 'The Industrial Emissions Directive', '2010/75 / EU', 'YES', 'During the revision process, the directive followed the five principles of comprehensive governance, best available techNOlogy, flexibility, monitoring management, and public participation, and made detailed and scientific regulations for various major industrial pollution areas, with a view to mini', 'https://ec.europa.eu/environment/eussd/smgp/index.htm', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (71, 'Petrochemical', 'EU', 'Best Available Techniques (BAT) Reference Document for the Refining of Mineral Oil and Gas. Industrial Emissions Directive 2010/75/EU (Integrated Pollution Prevention and Control)', 'JRC94879', 'YES', 'The BREF entitled ‘Refining of Mineral Oil and Gas’ forms part of a series presenting the results of an exchange of information between EU Member States, the industries concerned, NOn-governmental organisations promoting environmental protection, and the Commission, to draw up, review, and where nec', 'https://publications.jrc.ec.europa.eu/repository/handle/JRC94879', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (72, 'Petrochemical', 'EU', 'The Plastic Bags Directive', '(EU) 2015/720', 'YES', 'The Plastic Bags Directive (Directive (EU) 2015/720) is an amendment to the Packaging and Packaging Waste Directive (94/62/EC) and was adopted to deal with the unsustainable consumption and use of lightweight plastic carrier bags (i.e. plastic carrier bags with a wall thickness below 50 microns), wh', 'https://ec.europa.eu/environment/eussd/smgp/index.htm', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (73, 'Petrochemical', 'EU', 'Proposal for a Directive of the European Parliament and of the Council on Waste Electrical and Electronic Equipment', '2012/19/EU', 'YES', 'In order to prevent or reduce the production of waste electrical and electronic equipment and strengthen the management of electrical and electronic equipment, to protect the environment and human health. Through the use of raw materials, the efficiency of use is improved, and the negative influx ca', 'https://ec.europa.eu/environment/eussd/smgp/index.htm', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (74, 'Petrochemical', 'USA', 'title 40-Protection of Environment', null, 'YES', 'Federal environmental regulations stipulate water pollutants, air pollutants, solid waste discharge standards, energy policies, and toxic substances management plans for various industries.', 'https://www.ecfr.gov/', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (75, 'Petrochemical', 'USA', 'title 18-Conservation of Power and Water Resources', null, 'YES', 'National Energy Management Program and Water Resources Management Program.', 'https://www.ecfr.gov/', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (76, 'Petrochemical', 'Iran', 'Resolution to Determine the Permissible Limit of Air Pollutants', null, 'YES', null, 'rc.majlis.ir', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (77, 'Petrochemical', 'Indonesia', 'Regulation of the State Minister for Environmental Affairs NO. 8/2007 on quality standard of waste water of business and/or activities of upstream petrochemical industry', null, 'YES', 'The purpose of this Regulation is to control water pollution by stipulating quality standards of waste water for businesses and/or activities of upstream petrochemical industries.', 'http://extwprlegs1.fao.org/docs/pdf/ins77178.pdf', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (78, 'Petrochemical', 'Angola', 'Regulation of the National Direction for Petrochemical and Biofuels Refining', ' NO. 185/14 ', 'YES', ' This Regulation, consisting of 4 Chapters and 2 Annexes, establishes composition, duties and responsibilities of the above mentioned Direction, entitled to: a) promote and collaborate for the designing of necessary policies on petroleum refining, petrochemical, production and use of biofuels and lu', 'http://extwprlegs1.fao.org/docs/pdf/ang134834.pdf', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (79, 'Petrochemical', 'Angola', 'Presidential Decree NO. 132/13 establishing the legal framework applicable for any activity related to petroleum products.', 'NO. 132/14', 'YES', 'This Presidential Decree, consisting of 15 Chapters, establishes the legal framework applicable for any activity related to petroleum products, from crude petroleum refining processes, storage, transport of oil products through pipeline, logistic superintendence of Petroleum Products System of the R', 'http://extwprlegs1.fao.org/docs/pdf/ang127373.pdf', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (80, 'Petrochemical', 'Angola', 'Presidential Decree NO. 133/13 creating the Institution regulating Petroleum Products (IRDP)', 'NO. 133/13', 'YES', null, 'http://extwprlegs1.fao.org/docs/pdf/ang130804.pdf', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (81, 'Petrochemical', 'Angola', 'approving the legislation on crude oil refining and transport, storage, trade and supply of petroleum products', 'NO. 28/11', 'YES', 'This Law, consisting of 13 Chapters, approves the legislation on crude oil refining and transport, storage, trade and supply of petroleum products. This legislation aims at regulating the general functioning of the above mentioned activities related to petroleum products and its derivatives. This La', 'http://extwprlegs1.fao.org/docs/pdf/ang120536.pdf', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (82, 'Petrochemical', 'Bangladesh', 'Petroleum Act, 2016', 'NO. 3 of 2016', 'YES', 'This Act, consisting of six Chapters, regulates petroleum import, transport, storage, distribution, refining, blending, testing, licensing and all aspects related to petroleum exploitation. The Act is divided as follows: Definitions (Chap. 1); Control of Petroleum (Chap. 2); Licenses (Chap. 3); Petr', 'http://extwprlegs1.fao.org/docs/pdf/bgd158188.pdf', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (83, 'Petrochemical', 'Portugal', 'Decree-Law NO. 31/2006 on the general bases of the organization and functioning of the National Petroleum System.', 'NO. 31/2006', 'YES', 'This Decree-Law, consisting of 7 Chapters, establishes the general bases of the organization and functioning of the National Petroleum System and the general provisions applicable to the exercise of the activities of storage, transport, distribution, refining and marketing and organization of crude ', 'http://extwprlegs1.fao.org/docs/pdf/por149485.pdf', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (84, 'Petrochemical', 'India', 'Petroleum and Natural Gas Regulatory Board Act', 'NO. 19 of 2006', 'YES', 'This Act provides for the establishment of the Petroleum and Natural Gas Regulatory Board as a body corporate and defines its powers and functions. Functions of the board include: registering entities engaged in refining, processing, transportation, marketing, import and export, etc. of petroleum, p', 'http://extwprlegs1.fao.org/docs/pdf/ind68502.pdf', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (85, 'Petrochemical', 'Ethiopia', 'Petroleum Operations Proclamation', 'NO. 295/1986', 'YES', 'This Proclamation sets out rules relative to operations involving and related to the exploration, development, extraction, production, treatment, storage, transportation and marketing of petroleum, excluding refining of crude oil, but including the processing of natural gas. The Proclamation defines', 'http://extwprlegs1.fao.org/docs/pdf/eth85046.pdf', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (86, 'Petrochemical', 'Australia', 'Product Stewardship (Oil) ', 'Act 2000', 'YES', 'The objects of this Act are: (a) to develop a product stewardship arrangement for waste oils; and (b) to ensure the environmentally sustainable management, re refining and reuse of waste oil; and (c) to support ecoNOmic recycling options for waste oil. A grant (“product stewardship (oil) benefit”) i', 'https://view.officeapps.live.com/op/view.aspx?src=http%3A%2F%2Fextwprlegs1.fao.org%2Fdocs%2Ftexts%2Faus45240.doc&wdOrigin=BROWSELINK', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (87, 'Petrochemical', 'Cabo Verde', 'Decree-Law NO. 56/2010 regulating the National Oil System (SPN)', 'NO. 56/2010 ', 'YES', 'This Decree-Law, consisting of 7 Chapters, establishes the functioning and organization of the National Oil System (SPN). It specifies authorized activities and requirements to be fulfilled in order to perform the below mentioned activities related to crude oil and its byproducts, such as: import & ', 'http://extwprlegs1.fao.org/docs/pdf/cvi109390.pdf', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (88, 'Petrochemical', 'Azerbaijan', 'Ministerial Decree NO.122 on types of enterprises prohibited from discharge of industrial sewage', 'NO.122', 'YES', 'This Decree is issued to specify the types of enterprises prohibited from disposal of industrial sewage in accordance with the Article 39 of the Law NO. 723-IQ on water supply and effluent wastewater. This Decree states that sewage discharge from oil producing, oil refining, chemical and petrochemic', 'http://extwprlegs1.fao.org/docs/pdf/aze160704.pdf', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (89, 'Petrochemical', 'Sweden', 'Ordinance (2013:252) on large incineration plants', '2013:252', 'YES', 'The Ordinance lays down regulations on precautions for large combustion plants and for refined residual fuel (conversion residues from the refining of crude oil used in the refineries). Large incinerator facilities shall apply for an operating permit for the location, measurement and operation of co', 'http://extwprlegs1.fao.org/docs/pdf/swe124074.pdf', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (90, 'Petrochemical', 'Cayman Islands (UK)', 'Fuel Market Regulation Law, 2017 ', 'NO. 20 of 2017', 'YES', 'This Law defines the services offered and provided by the fuel sector are covered services for the purposes of the Utility Regulation and Competition Law, 2016. It provides that the Cabinet shall establish and maintain policies designed to ensure that the importation, exportation, re-export, shippin', 'http://extwprlegs1.fao.org/docs/pdf/cay171866.pdf', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (91, 'Textile', 'China', 'Cleaner production standard–Textile industry（Dyeing and finishing of cotton ）', 'HJ/T185-2006', 'YES', 'This standard is a recommended standard, which can be used for the evaluation of cleaner production potential and opportunity, cleaner production performance evaluation and cleaner production performance anNOuncement system of textile industry (dyeing and finishing of cotton) production enterprises', 'https://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/other/qjscbz/200610/t20061001_78200.htm', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (92, 'Textile', 'China', 'Cleaner production standard －Chemical fibre industry (Spandex)', 'HJ/T359-2007', 'YES', 'This standard is applicable to the cleaner production audit and the judgment of cleaner production potential and opportunity, as well as cleaner production performance evaluation and cleaner production performance anNOuncement system of spandex manufacturers using dry solvent spinning process route ', 'https://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/other/qjscbz/200708/t20070808_107735.shtml', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (93, 'Textile', 'China', 'Cleaner production standard - Chemical fibre industry (polyester fibre)', 'HJ/T429-2008', 'YES', 'This standard specifies the general requirements for cleaner production of chemical fiber industry (polyester) production enterprises. This standard is applicable to cleaner production audit, judgment of cleaner production potential and opportunities, cleaner production performance evaluation and cl', 'https://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/other/qjscbz/200804/t20080414_121142.shtml', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (94, 'Textile', 'China', 'Evaluation index system of cleaner production in jeans washing industry', 'T/GDTEX 05-2019', 'YES', 'This standard specifies the general requirements for cleaner production of jeans washing enterprises, and divides cleaner production indicators into six categories, namely production process and equipment requirements, resource and energy consumption indicators, comprehensive utilization indicators ', 'http://www.gdtextiles.cn/nd.jsp?id=272', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (95, 'Textile', 'China', 'Technical specification for green-design product assessment-cashmere knitting goods', 'T/CAB 0025-2017', 'YES', 'This standard specifies the definition, evaluation requirements of the green design evaluation of the life cycle of cashmere knitting products.', 'https://www.miit.gov.cn/cms_files/filemanager/oldfile/miit/n1146285/n1146352/n3054355/n3057542/c7796801/part/7797276.pdf', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (96, 'Textile', 'China', 'Technical specification for eco-design product assessment-Recycled Polyester products', 'T/CNTAC 52-2020', 'YES', 'This standard provides terms and definitions、evaluation requirements、green design product evaluation report requirements of the life cycle of recycled polyester products.', 'https://www.miit.gov.cn/cms_files/filemanager/oldfile/miit/n1146285/n1146352/n3054355/n3057542/c7796801/part/7797281.pdf', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (97, 'Textile', 'China', 'Technical specification for green-design product assessment-Outdoor multipurpose fabric', 'T/CAB 0034-2018', 'YES', 'This standard specifies the definition, evaluation requirements, and life cycle evaluation report preparation method of life cycle of outdoor multipurpose fabric.', 'https://www.miit.gov.cn/jgsj/jns/qjsc/art/2021/art_651f1af99f914c2fb68ca8a2aab4c943.html', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (98, 'Textile', 'China', 'Technical specification for green-design product assessment-silk product', 'FZ/T 07003-2019', 'YES', 'This standard specifies the terms and definitions, evaluation requirements, evaluation methods and preparation methods of life cycle assessment report of silk products.', 'https://www.miit.gov.cn/jgsj/jns/qjsc/art/2021/art_651f1af99f914c2fb68ca8a2aab4c943.html', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (99, 'Textile', 'China', 'Technical specification for green-design product assessment-Printed and dyed sanded polyester blended fabric', 'T/CAB 0030-2018', 'YES', 'This standard specifies the terms and definitions, evaluation requirements, evaluation methods and preparation methods of life cycle assessment report of printed and dyed sanded polyester blended fabric.', 'https://www.miit.gov.cn/jgsj/jns/qjsc/art/2021/art_651f1af99f914c2fb68ca8a2aab4c943.html', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (100, 'Textile', 'China', 'Technical specification for green-design product assessment-woven towels', 'T/CNTAC 34-2019', 'YES', 'This standard specifies the terms and definitions, evaluation requirements, evaluation methods and preparation methods of life cycle assessment report of woven towels.', 'https://www.miit.gov.cn/jgsj/jns/qjsc/art/2021/art_651f1af99f914c2fb68ca8a2aab4c943.html', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (101, 'Textile', 'China', 'Technical specification for eco-design product assessment - wool worsted product', 'T/CNTAC 39-2019', 'YES', 'This standard gives the terms and definitions, evaluation requirements, self-evaluation report preparation requirements, product life cycle evaluation report preparation requirements and green design product judgment basis of life cycle green design evaluation of wool worsted product.', 'https://www.miit.gov.cn/jgsj/jns/qjsc/art/2021/art_651f1af99f914c2fb68ca8a2aab4c943.html', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (102, 'Textile', 'China', 'Technical specification for eco-design product assessment -cashmere goods', 'T/CNTAC 38-2019', 'YES', 'This standard gives the terms and definitions, evaluation requirements, self-evaluation report preparation requirements, product life cycle evaluation report preparation requirements and green design product judgment basis of life cycle green design evaluation of cashmere goods.', 'https://www.miit.gov.cn/n1146285/n1146352/n3054355/n3057542/n5920352/c7251483/part/7251661.pdf', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (103, 'Textile', 'China', 'Technical specification for eco-design product assessment - indoor ornamental textiles', 'T/CNTAC 41-2019', 'YES', 'This standard gives the terms and definitions, evaluation requirements, self-evaluation report preparation requirements, product life cycle evaluation report preparation requirements and green design product judgment basis of life cycle green design evaluation of indoor ornamental textiles.', 'https://www.miit.gov.cn/jgsj/jns/qjsc/art/2021/art_651f1af99f914c2fb68ca8a2aab4c943.html', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (104, 'Textile', 'China', 'Technical specification for green-design product assessment -Baby wipes', 'T/CAB 0052-2019', 'YES', 'This standard applies to the evaluation of green design products of baby wipes, including wipes made of NOnwovens for infants and babies.', 'https://www.miit.gov.cn/jgsj/jns/qjsc/art/2021/art_651f1af99f914c2fb68ca8a2aab4c943.html', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (105, 'Textile', 'China', 'Technical specification for eco-design product assessment - Spun-dyed yam', 'T/CNTAC 51-2020', 'YES', 'This standard gives the terms and definitions, evaluation requirements, self-evaluation report preparation requirements, product life cycle evaluation report preparation requirements and green design product judgment basis of life cycle green design evaluation of squn-dyes yam.', 'https://www.miit.gov.cn/jgsj/jns/qjsc/art/2021/art_651f1af99f914c2fb68ca8a2aab4c943.html', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (106, 'Textile', 'China', 'Technical specification for eco-design product assessment - knitted Printing and dyeing fabric', 'T/CNTAC 40-2019', 'YES', 'This standard gives the terms and definitions, evaluation requirements, self-evaluation report preparation requirements, product life cycle evaluation report preparation requirements and green design product judgment basis of life cycle green design evaluation of knitted printing and dyeing fabric.', 'https://www.miit.gov.cn/n1146285/n1146352/n3054355/n3057542/n5920352/c7251483/part/7251663.pdf', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (107, 'Textile', 'China', 'Technical specification for green-design product assessment -leather suit', 'T/CNTAC 35-2019', 'YES', 'This standard specifies the terms, definition, evaluation requirements, product lifecycle evaluation report preparation method and evaluation method for green design product evaluation of leather suit.', 'https://www.miit.gov.cn/jgsj/jns/qjsc/art/2021/art_651f1af99f914c2fb68ca8a2aab4c943.html', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (108, 'Textile', 'China', 'Guidelines for assessment of green factory in textile industry', 'FZ/T 07004-2019', 'YES', 'This standard specifies the index system and general requirements for the evaluation of green factories in the textile industry. This standard is applicable to cotton (including cotton chemical fiber) textile and printing and dyeing processing, wool textile and dyeing and finishing finishing, hemp t', 'https://www.spc.org.cn/online/FZ%252FT%252007004-2019/?', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (109, 'Textile', 'China', 'Assessment requirements for green factory in polyester filament fabric printing and dyeing', 'T/CAB 2018-2019', 'YES', 'This standard is applicable to the evaluation of green factories in polyester filament fabric printing and dyeing and the evaluation of green factories in other chemical fiber printing and dyeing factories', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (110, 'Textile', 'China', 'Evaluation index system of green supply chain management for textile industry', 'FZ/T 07005-2020', 'YES', 'This standard specifies the purpose, scope, evaluation system of green supply chain management of textile industries, including green supply chain management strategy, implementing green supplier management, green production, green sales and recycling, green confidence platform construction and info', 'https://www.spc.org.cn/online/FZ%252FT%252007005-2020/?', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (111, 'Textile', 'China', 'Technical specification for dyeing and finishing wastewater treatment of textile industry', 'HJ 471-2020', 'YES', 'This standard provides the technical requirements for the design, construction, acceptance, operation and maintenance of textile dyeing and finishing industrial wastewater treatment project.This standard is a guidance standard', 'https://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/jcffbz/202001/t20200115_759457.shtml', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (112, 'Textile', 'China', 'Green product assessment-Textile products', 'GB/T 35611-2017', 'YES', 'This standard specifies the evaluation index and evaluation method of green textile products.', 'https://www.spc.org.cn/online/GB%252FT%252035611-2017/?', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (113, 'Steel', 'China', 'Emission standard of air pollutants for foundry industry', 'GB39726-2020', 'YES', 'This standard sets out the emission control requirements, monitoring and supervision requirements for atmospheric pollutants in the foundry industry. The corresponding national pollutant emission standards shall be applied to the discharge of water pollutants, odorous pollutants and environmental NO', 'http://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/dqhjbh/dqgdwrywrwpfbz/202012/t20201225_814815.shtml', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (114, 'Steel', 'China', 'Emission standard of air pollutants for steel smelt industry', 'GB28664-2012', 'YES', 'This standard sets out the emission limits, monitoring and monitoring requirements for atmospheric pollutants in steel-making enterprises or production facilities, as well as the implementation and supervision of the standards. This standard applies to the management of atmospheric pollutant emissio', 'http://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/dqhjbh/dqgdwrywrwpfbz/201207/t20120731_234142.shtml', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (115, 'Steel', 'China', 'Emission standard of air pollutants for steel rolling industry', 'GB28665-2012', 'YES', 'This standard sets out the emission limits, monitoring and monitoring requirements for atmospheric pollutants from rolling steel production enterprises or production facilities, as well as the implementation and supervision of the standards. This standard applies to the management of atmospheric pol', 'http://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/dqhjbh/dqgdwrywrwpfbz/201207/t20120731_234143.shtml', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (116, 'Steel', 'China', 'Discharge standard of water pollutants for iron and steel industry', 'GB13456-2012', 'YES', 'This standard sets out the limits, monitoring and monitoring requirements for water pollutant discharge in steel production enterprises or production facilities, as well as the implementation and supervision of the standards. This standard applies to the management of water pollutant discharge in ex', 'http://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/shjbh/swrwpfbz/201207/t20120731_234144.shtml', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (117, 'Steel', 'China', 'Design criterion for Energy Saving of iron and steel industry', 'GB50632-2010', 'YES', 'This specification applies to the overall development plan of steel enterprises, the design of new construction and alteration of the steel industry, and the energy planning of steel enterprises. The production process of steel joint venture includes sintering, ball group, coking, ironmaking, steelm', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (118, 'Steel', 'China', 'General guideline of the greenhouse gas emissions accounting and reporting for industrial enterprises', 'GB/T 32150—2015', 'YES', 'The standard defines the terms and definitions, basic principles, workflow, accounting boundary determination, accounting steps and methods, quality assurance, reporting requirements, etc. of greenhouse gas emission accounting and reporting of industrial enterprises. This standard is applicable to g', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (119, 'Steel', 'China', 'Requirements of greenhouse gas emission accounting and reporting—Part 5:Iron and steel productiong enterprise', 'GB/T 32151—2015', 'YES', 'This part of this document defines the terms related to the accounting and reporting of greenhouse gas emissions of steel production enterprises, accounting boundaries, accounting procedures and accounting methods, data quality management, report content and format.', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (120, 'Steel', 'China', 'Technical specification at the project level for assessment of greenhouse gas emission reductions—Utilization of waste energy in iron and steel industry', 'GB/T 33755—2017', 'YES', 'This standard defines the termiNOlogy and definition of the project''s greenhouse gas emission reduction assessment and the content of the assessment of the steel industry''s residual energy use.', 'http://www.gb688.cn/bzgk/gb/newGbInfo?hcNO=2B101CC72890C5B68115856FFE264D45', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (121, 'Steel', 'China', 'Technical specification for green house ga emission verification of iron and steel production enterprises', 'RB/T 251—2018', 'YES', 'This standard sets out the requirements for verification steps, verification requirements and verification reports for greenhouse gas emissions of steel producers of high-converter (long process) and electric furnace (short process) steel production enterprises.', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (122, 'Steel', 'China', 'Cleaner production standard—Iron and Steel industry', 'HJ/T 189-2006', 'NO', 'This standard is recommended and can be used for the review of clean production and the determination of clean production potential and opportunities in steel joint ventures and furnace steel mills (short processes), as well as for the evaluation of clean production performance and the anNOuncement ', 'http://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/other/qjscbz/200610/t20061001_78207.shtml', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (123, 'Steel', 'China', 'Steel industry cleaner production evaluation indicator system', null, 'NO', 'This index system is used to evaluate the level of clean production of steel enterprises, as the main basis for the creation of advanced clean production enterprises, and to provide technical guidance for enterprises to implement clean production.', 'https://www.ndrc.gov.cn/hdjl/yjzq/201305/W020190927558534301256.pdf', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (124, 'Steel', 'China', 'Cleaner production standard–Steel rolling (plate) industry', 'HJ/T 318-2006', 'NO', 'This standard applies to the clean production audit of thick plate rolled steel in the steel industry, the judgment of the potential and opportunity of clean production, the evaluation of clean production performance and the anNOuncement system of clean production performance.', 'http://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/other/qjscbz/200611/t20061129_96654.shtml', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (125, 'Steel', 'China', 'Cleaner production standard – Sintering industry', 'HJ/T 426-2008', 'NO', 'This standard divides the clean production index into six categories, namely, production process and equipment requirements, resource and energy utilization indicators, product indicators, pollutant generation indicators, waste recycling indicators and environmental management requirements. This sta', 'http://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/other/qjscbz/200804/t20080414_121139.shtml', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (126, 'Steel', 'China', 'Cleaner production standard - Blast furnace', 'HJ/T 427-2008', 'NO', 'This standard divides the clean production indicators into six categories, namely, production process and equipment requirements, resource and energy utilization indicators, product indicators, pollutant generation control indicators, waste recycling indicators and environmental management requireme', 'http://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/other/qjscbz/200804/t20080414_121140.shtml', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (127, 'Steel', 'China', 'Cleaner production standard –Steel-making industry', 'HJ/T 428-2008', 'NO', 'This standard divides the clean production indicators into six categories, namely, production process and equipment requirements, resource and energy utilization indicators, product indicators, pollutant generation control indicators, waste recycling indicators and environmental management requireme', 'http://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/other/qjscbz/200804/t20080414_121141.shtml', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (128, 'Steel', 'China', 'Cleaner production standard Ferroalloy industry', 'HJ 470-2009', 'NO', 'This standard sets out the general requirements for clean production of iron alloy enterprises in the steel industry on the basis of meeting national and local pollutant emission standards, according to the current industry techNOlogy, equipment level and management level. This standard is divided i', 'http://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/other/qjscbz/200904/t20090414_150411.shtml', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (129, 'Steel', 'China', null, null, 'YES', 'The system provides for the emission of particulate matter, sulfur dioxide and nitrogen oxides from the production processes of the steel industry, and also explains the emission standards of water pollutants.', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (130, 'Steel', 'China', null, null, 'YES', 'The index system according to the comprehensive evaluation index total score value of the enterprise clean production level is divided into three levels, I level represents the international clean production leading level, LEVEL II represents the domestic clean production advanced level, level III r', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (131, 'Steel', 'China', null, null, 'YES', 'The index system according to the comprehensive evaluation index total score value of the enterprise clean production level is divided into three levels, I level represents the international clean production leading level, LEVEL II represents the domestic clean production advanced level, level III r', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (132, 'Steel', 'China', null, null, 'YES', 'The index system according to the comprehensive evaluation index total score value of the enterprise clean production level is divided into three levels, I level represents the international clean production leading level, LEVEL II represents the domestic clean production advanced level, level III r', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (133, 'Steel', 'China', null, null, 'YES', 'The index system according to the comprehensive evaluation index total score value of the enterprise clean production level is divided into three levels, I level represents the international clean production leading level, LEVEL II represents the domestic clean production advanced level, level III r', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (134, 'Steel', 'China', 'The NOrn of energy consumption per unit product of major individual-process of crude steel manufaturing process', 'GB21256-2013', 'YES', 'This standard specifies the limits of energy consumption limits, access values and advanced values per unit of crude steel production, statistical scope and calculation methods, and energy-saving measures.', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (135, 'Steel', 'China', 'The NOrm of energy consumption per unit product of ferroalloy', 'GB21341-2017', 'YES', 'This standard specifies terms and definitions, technical requirements, statistical scope, and calculation methods such as energy consumption limits per unit of ferroalloy products.', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (136, 'Steel', 'China', 'Emission standard of pollutants for mining and mineral processing industry', 'GB28661-2012', 'YES', 'This standard sets out the limits for the discharge of water and atmospheric pollutants from iron ore mining enterprises or production facilities, monitoring and monitoring requirements, as well as the implementation and supervision of the standards. This standard applies to the management of water ', 'https://www.mee.gov.cn/ywgz/fgbz/bz/bzwb/shjbh/swrwpfbz/201207/t20120731_234139.shtml', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (137, 'Steel', 'Slovenia', '	Decree on the emission of substances into atmosphere from installations for the production of light alloy, ferrous and steel', null, 'YES', 'This Decree of the Government of the Republic of Slovenia, which is composed of eight articles and two Annexes, lays down requirements for the devices for melting, remelting, retention on temperature and casting of light alloy, ferrous and steel: (1) specific limits for certain substances in waste g', 'http://extwprlegs1.fao.org/docs/html/slv130513.htm', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (138, 'Steel', 'Slovenia', 'Regulation on the emission of substances into the air from from foundries of cast iron, alloy of iron and steel', null, 'YES', 'This Regulation of the Government of the Republic of Slovenia, which is composed of nine articles and two Annexes, establishes, in relation to the emission of substances into the air, from foundries of cast iron, alloy of iron and steel: specific limits of emissions of certain substances in waste ga', 'http://extwprlegs1.fao.org/docs/html/slv97922.htm', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (139, 'Steel', 'Slovenia', 'Regulation on the emission of substances in the discharge of waste water from plants dealing with the production and processing of iron and steel.', null, 'YES', 'This Regulation of the Government of the Republic of Slovenia, which is composed of ten articles and two Annexes, establishes requirements concerning the emission of substances and heat in the discharge of waste water from industrial plants dealing with the production and processing of iron and stee', 'http://extwprlegs1.fao.org/docs/html/slv97930.htm', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (140, 'Steel', 'Ukraine', '《techNOlogical NOrms of permissible emissions of pollutants from equipment (installation) for manufacturing of steel》 (primary and secondary melting)', null, 'YES', 'This Regulation establishes maximum permissible limits of emissions of pollutants from equipment (installation) for manufacturing of or manufacturing of steel (primary and secondary melting), with the productivity exceeding 2, 5 tons per hour (installations of gas-oxygen refining of steel). It also ', 'http://extwprlegs1.fao.org/docs/pdf/ukr171887.pdf', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (141, 'Steel', 'Albania', '	Regulation NO.117 of 2013 on the criteria used for determining when certain types of metal scrap cease to be waste.', null, 'YES', 'This Regulation lays down the criteria used for determining when scraps of iron, steel and aluminum are NO longer considered waste. The Regulation fully transposes into national law the Council of Europe Regulation NO.333/2011. Rules dealing with the conformity declarations, and the allowed percenta', 'http://extwprlegs1.fao.org/docs/pdf/alb137760.pdf', null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (142, 'Cement ', 'China', 'Cleaner Production Standard Cement Industry', 'HJ467-2009', 'NO', null, null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (143, 'Cement ', 'China', 'Emission Standards for Air Pollutants in Building Materials Industry (Shandong)', 'DB372373-2018', 'YES', 'This standard specifies the emission limits and monitoring requirements for cement air pollutants in Shandong Province, as well as the implementation and supervision of the standard and other related requirements. This standard applies to the management of air pollutant emissions from existing cemen', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (144, 'Cement ', 'China', 'Technical Specification for Denitrification Project of Cement Plant', 'GB 51045 - 2014', 'YES', 'Applicable to the design, construction, acceptance and operation and maintenance of denitrification projects for new dry process cement clinker production lines, alteration and expansion', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (145, 'Cement ', 'China', 'Hazardous waste (including medical waste) incineration and disposal facilities dioxin emissions monitoring technical specifications', 'HJ/T365-2007', 'YES', 'Specified the hazardous waste incineration and disposal facilities dioxin emissions detection point layout, sampling operating conditions, sampling equipment, analytical methods, quality assurance and quality control, data processing, results expression and monitoring reports and other technical req', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (146, 'Cement ', 'China', 'People''s Republic of China Geological and Mineral Industry Standard Cement Tuff Green Mine Construction Specification ', 'DZ/T0318-2018', 'YES', 'Specifies the basic requirements for the environment of cement tuff green mine sites, resource development methods, comprehensive utilization of resources, energy conservation and emission reduction, scientific and techNOlogical inNOvation and digital mines, enterprise management and corporate image', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (147, 'Cement ', 'China', 'Cement industry air pollutant emission standards', 'GB 4915-2013', 'YES', 'This standard specifies the air pollution emission limits, monitoring and supervision and management requirements for cement manufacturing enterprises (including independent grinding stations), cement raw material mines, bulk cement transfer stations, cement product enterprises and their production ', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (148, 'Cement ', 'China', 'Cement plant environmental protection facilities design standards', 'GB/T 50558-2019', 'YES', 'Applicable to the design of environmental protection facilities for new construction, expansion and alteration projects of cement plants and grinding stations.', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (149, 'Cement ', 'China', 'Cement plant occupational safety and health design specifications', 'GB 50577-2010', 'YES', 'Applicable to the design of labor safety and occupational health in the engineering design of new, altered and expanded production lines of cement plants.', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (150, 'Cement ', 'China', 'Technical specifications for dust and drug prevention in cement production enterprises ', 'AQ/T4247-2015', 'YES', 'Specifies the basic requirements for dust and toxicity control in cement production enterprises, site selection and layout, process engineering protection, personal protection measures, management measures, accident emergency disposal measures, occupational health supervision and occupational health', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (151, 'Cement ', 'China', 'Technical specification for dust prevention in cement production', 'GB/T16911-2008', 'YES', 'Provides for the selection of cement production enterprises and plant site design of dust control requirements, process design of dust control requirements, workshop dust control measures, dust-producing process dust control measures, individual protection and dust control management.', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (152, 'Cement ', 'China', 'Cement kiln co-disposal of solid waste pollution control standards', 'GB 30485-2013_2500', 'YES', 'Specified the co-disposal of solid waste cement kiln facilities technical requirements, waste characteristics into the kiln requirements, operating technical requirements, pollutant emission limits, the production of cement products pollutant control requirements, monitoring and supervision and mana', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (153, 'Cement ', 'China', 'Technical Guide for Source Strength Accounting of Pollution Sources Cement Industry', 'HJ 886—2018', 'YES', 'Specified the procedures, methods and selection principles, content and requirements for source accounting of pollution sources in the cement industry', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (154, 'Cement ', 'China', 'Greenhouse gas emission accounting and reporting requirements: cement production enterprises', 'GB/T 32151', 'YES', 'Specified the accounting and reporting of greenhouse gas emissions of cement manufacturers and related termiNOlogy, accounting boundaries, accounting steps and accounting methods, data quality management, report content and format.', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (155, 'Cement ', 'China', 'Technical requirements for environmental labeling products Rigid waterproofing materials', 'HJ456-2009', 'YES', 'Specified the terms and definitions, basic requirements, technical content and test methods for rigid waterproofing materials environmental labeling products', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (156, 'Cement ', 'China', 'Hygienic standards for respirable cement dust in workshop air ', 'GB 16238-1996  ', 'YES', 'Specified the maximum permissible concentration of respirable cement dust in the workshop air and its monitoring test methods.', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (157, 'Cement ', 'China', 'Cement Industry Cleaner Production Evaluation Index System', 'National Development and Reform Commission, Ministry of Environmental Protection, Ministry of Industry and Information TechNOlogy', 'YES', 'Specified the requirements of cleaner production in the cement industry enterprises, mainly including the production process and equipment indicators, resource and energy consumption indicators, resource utilization indicators, pollutant generation indicators, product characteristics indicators and ', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (158, 'Cement ', 'China', 'Technical Policy on Pollution Prevention and Control in the Cement Industry', 'Ministry of Environmental Protection NO. 31, 2013 ', 'YES', 'Put forward the technical routes, principles and methods that can be taken to prevent and control pollution in the cement industry, including source control, air pollutant emission control, the use of cement production facilities to co-dispose of solid waste, other pollutant emission control, resear', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (159, 'Cement ', 'China', 'Cleaner Production TechNOlogy Implementation Plan for the Cement Industry', 'Ministry of Industry and Information TechNOlogy', 'YES', 'Requirements in the cement industry focus on the promotion of cement kiln nitrogen oxide emission reduction techNOlogy, cement kiln co-disposal of waste techNOlogy and cement kiln lining using chromium-free refractory materials (bricks) and other techNOlogies.', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (160, 'Cement ', 'China', 'NOtice of the "Fourteenth Five-Year Plan" Circular EcoNOmy Development Plan', 'National Development and Reform Commission', 'YES', 'NOtification of the cement industry is as follows: strengthen the key industries clean production. In accordance with the law in the "double super double high energy consumption" industry to implement mandatory clean production audits, to guide other industries to consciously and voluntarily carry o', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (161, 'Cement ', 'European Union', 'Stationary source emissions - Determination of greenhouse gas (GHG) emissions in energy-intensive industries - Part 3: Cement industry', 'EN 19694-3-2016', 'YES', 'This European Standard specifies a uniform method for calculating greenhouse gas emissions in the cement industry', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (162, 'Cement ', 'European Union', 'Cement and building lime - Environmental product declarations - Product category rules complementary to EN 15804', 'EN 16908-2017', 'YES', 'The product characterization requirements are mainly used to create cradle-to-grave environmental label certification for cement and building lime', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (163, 'Cement ', 'Russia', 'Best available techniques. Production of cement. Industrial ecological control', 'GOST R 56828.45-2019 ', 'YES', 'Best Available Techniques. Cement production. Industrial ecological control', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (164, 'Cement ', 'Austrian Institute for Standardization', 'Emission limits for air contaminants from the cement industries', 'OENORM M9451-1988', 'YES', 'Air pollutant emission limits for the cement industry', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (165, 'Cement ', 'Vietnam', 'Air quality.Emission standards for cement manufacturing', 'TCVN 7735-2007 ', 'YES', 'Air quality. Emission standards for the cement manufacturing industry', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (166, 'Cement ', 'India', 'the emission limits for particulate matter emitted through the cement kiln stack', 'IS 10693 Pt.1-1983 ', 'YES', 'Emission limits for particulate matter emissions from cement kiln chimneys/stacks in silicate cement manufacturing plants.', null, null, null);
INSERT INTO standard.detailEng (detailEng_id, industry, region, standard, number, effectiveness, abstracts, link, scope, year) VALUES (167, 'Cement ', 'Kenya', 'Air quality-Emissions to the air by cement factories guidelines', 'KS EAS 750-2010', 'YES', 'Air Quality . Guidelines for Emission Air Quality from Cement Plants', null, null, null);