create table Tech
(
    NO                  varchar(255) not null
        primary key,
    Country             varchar(255) null,
    Industry            varchar(255) null,
    CleanTechnology     varchar(255) null,
    ProductionStage     varchar(255) null,
    TechnologyOverview  text         null,
    Effect              text         null,
    Fields              text         null,
    Highlights          text         null,
    TypicalApplications text         null,
    Cost                text         null,
    Stability           text         null,
    Innovation          text         null,
    Source              text         null,
    Comment             text         null
)charset = utf8;

INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('CE001', '中国', '水泥', '水泥窑尾烟气高温电除尘+选择性催化还原脱硝技术', '生产过程', '	
水泥窑尾烟气依次通过高温电除尘、金属纤维毡过滤除尘和 SCR 脱硝反应器，完成高效除尘和脱硝，脱硝产物为 N2 和 H2O，无二次污染。出口 NOx 浓度< 50 mg/m3，氨逃逸< 2.5 mg/m3；进入SCR脱硝系统的含尘浓度约为 30 gm3；系统总阻力< 1000 Pa。', '脱硝效率高，净化系统运行阻力低。', '大气污染防治', '碳减排', '登封市宏昌水泥有限公司', '项目总投资约3250万元，其中设备费用2500万元，建设费用600万元，其它投资150万元。以4500t/d水泥SCR脱硝系统为例，总运行成本约650.7万元/年。', null, null, '2021 年《国家先进污染防治技术目录（大气污染防治、噪声与振动控制领域）》', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('CE002', '中国', '水泥', '水泥窑尾烟气高温电除尘+金属纤维毡过滤除尘 +选择性催化还原脱硝技术', '生产过程', '水泥窑尾烟气依次通过高温电除尘、金属纤维毡过滤除尘和SCR脱硝反应器，完成高效除尘和脱硝，脱硝产物为N2和H2O，无二次污染。出口 NOx 浓度< 50 mg/m3，氨逃逸< 2.5 mg/m3；系统总阻力< 1500 Pa。', '进入SCR脱硝反应器的含尘浓度显著降低。脱硝效率高，催化剂寿命长。', '大气污染防治', '碳减排', '登电集团水泥有限公司', '1068万元', null, null, '2021 年《国家先进污染防治技术目录（大气污染防治、噪声与振动控制领域）》', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('CE003', '中国', '水泥', '工业烟气气动脱硫除尘超低排放技术', '生产过程', '通过气动脱硫单元使原烟气剧烈旋转，与脱硫浆液形成两相旋流并互相扰动，从而实现脱硫。脱硫烟气通过气动高效除雾器脱除烟气中的雾滴和微小粉尘，使得烟气污染物含量达到超低排放标准。适用于	脱硫出口二氧化硫浓度小于 35 mg/m3（标态，干基，6%O2）、烟尘浓度小于 5 mg/m3（标态，干基，6%O2）。', '脱硫除尘', '大气污染防治', '烟气脱硫/除尘', null, null, '本技术已经进入工程规模应用阶段，工艺路线成熟、设备及系统集成完善。有近40项工程应用实例，实现技术产值6.38亿元。 ', '（1）工艺创新：创新烟气湿法脱硫除尘超净排放工艺，并进行了工艺流程和系统优化； （2）设计创新：优化设计气动脱硫塔、气动脱硫单元等核心设备、部件，对新型高效除雾器进行原创研究和设计创新，提高了系统脱硫除尘效率和综合性能。', '天津市节能低碳与环境污染防治技术指导目录（第三辑）', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('CE004', '中国', '水泥', '水泥窑炉烟气脱硫脱硝一体化技术', '生产过程', '	
水泥熟料煅烧过程会产生大量的烟气排放，烟气中SO2和NOx浓度可高达2000mg/Nm3和1200mg/Nm3。通过工艺设计和过程控制，将高含CaO热生料送入预热器C1筒和余热锅炉入口处，实现生产过程干法脱硫。通过模拟仿真和工程设计，余热锅炉后端建立烟气中低温（150~220℃）脱硝反应器，采用中低温催化剂和精准喷氨及智能吹灰技术，实现NOx排放＜50mg/Nm3、吨水泥熟料氨水（20%）＜2kg', '通过热生料过程脱硫，烟气脱硫效率＞80%；通过中低温SCR脱硝技术，在吨熟料2千克氨水用量下，烟气脱硝效率＞90%。', '大气污染防治', '烟气脱硫脱硝', '长兴南方水泥有限公司', '前期工程应用表明，增设SCR反应器及配套辅助系统，新增电耗约为2kW·h/吨熟料，按每度电0.6元、5000t/d生产线每年生产150万吨熟料计，即运行费用约为180万，其他折旧和管理费用50万元，小计为230万。催化剂质保三年，三年后每年催化剂更换费用约为200万。', '	
本项目提出的工程技术为过程脱硫和中低温SCR脱硝，以便削减水泥窑炉烟气中SO2和NOx排放，实现水泥生产与环境保护的协同推进。 项目提出的过程脱硫技术采用的是水泥熟料煅烧过程中的中间产物热生料，即高含CaO的生料，进行SO2的吸附及随后的化学反应，生成硫酸盐或亚硫酸盐，并进入到水泥熟料体系中。相比于干法脱硫或湿法脱硫，过程脱硫不需要外购石灰，不需要增设大型烟气脱硫装置，整个脱硫过程与水泥生产过程融合，可保证与水泥生产同步运行，对环境及水泥生产工艺过程没有任何影响。  项目提出的中低温SCR脱硝技术与传统的高温SCR脱硝技术相比，是将SCR反应器置于余热发电锅炉之后，这样既不影响窑炉系统的正常运行，又不影响余热锅炉的发电效率。此外，由于中低温SCR脱硝技术带有自喷氨系统及氨的高效利用，这样也防止了氨水对窑炉管道系统及附属高温材料的腐蚀。这就使得SCR脱硝工艺技术装备不受窑炉水泥熟料煅烧工况的影响，不产生对任何生产工艺设备的损坏，保证了水泥生产工艺技术装备的高效稳定运行和窑炉烟气NOx的超低排放。', null, '绿色技术银行', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('CE005', '中国', '水泥', '预热器低温脱硫技术', '生产过程', '在原脱硝系统的基础上，利用脱硝原有的氨水罐、出口管道及电控元件，只需增加一套输送和喷射装置，投入少，见效快，安装方便，操作简单，具有较强的实用性', '该项革新有效的控制了停磨期间SO2的升高，避免了废气的超标排放，环境效应得到保障；停磨后回转窑不需要再减料调整，回转窑的台时得到稳定，减少了因窑减产带来的经济损失，每次因停磨减产造成熟料损失约三万多元。', '大气污染防治', '烟气脱硫', '枣庄市沃丰水泥有限公司', '1.2万元', null, null, '《水泥行业清洁生产调研报告》', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('CE006', '中国', '水泥', '高效脱硝低氧还原燃烧法', '生产过程', '公司自主创立了“WMF高效脱硝低氧还原燃烧法”，对氮氧化物采用低氮分级燃烧脱硝技术及多层喷氨技术，准确控制和优化窑炉煤量比，从源头上控制氮氧化物的生成量，并采用分解炉分煤燃烧控制技术，通过不断的研究分析实现了氮氧化物控制NOx排放<100mg/Nm3。', '在于空气和煤粉分级的位置、程度及氨水喷枪的形式、喷入位置、角度等，其脱硝效率高低不等。', '大气污染防治', '烟气脱硝', '枣庄市沃丰水泥有限公司', '4.91万元', null, null, '《水泥行业清洁生产调研报告》', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('CE007', '中国', '水泥', '高固气比水泥悬浮预热分解技术', '生产过程', '高固气比预热分解系统主要由高固气比预热器和外循环式分解炉构成，其中高固气比预热器由两列并行排列的旋风预热单元组成。通过提高系统内固体物料与气流的质量比，达到提高系统热效率、增强系统热稳定性的效果。主要技术指标：①窑尾废气温度小于260℃；②水泥熟料烧成的可比热耗低于每公斤熟料2675kJ（640kcal）；③吨熟料电耗小于56kWh；④窑系统运转率大于90%', '与同规格回转窑的新型干法水泥生产线相比，产量增加40%以上，热耗减少20%以上，单位电耗减少15%以上，废气中的SO2排放降低70%以上，NOx 排放降低50%以上。', '能源节约及清洁化', '物料预热降耗', '尧柏阳山庄水泥有限公司', null, '2011年5月该技术已通过陕西省科学技术厅组织的技术鉴定。该技术2011年被评为“中国高等学校十大科技进展”，入选国家工信部《工业节能十二五规划》，荣获“第四届节能中国十大应用技术”', null, '国家重点节能技术推广目录（第四批）', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('CE008', '中国', '水泥', '利用水泥窑协同处置工业废水技术', '源头控制', '	
常压下，在预处理中心将带搅拌机的工业废水在中和罐中进行中和反应，中和反应温度控制在20-95摄氏度。进行中和时，根据不同的酸碱度情况，通过酸、碱添加装置加入Ca(OH) 溶液或废酸，使处理后的工业废水具有弱碱性，PH值控制在8-10。将中和反应后的废液送入板框压滤器，在工作压力为10-14MPa条件下进行压滤，压滤后液体进入液态废弃物储存池，或者与废矿物油、废乳化油、废清洗剂、废有机溶剂等进行混配，调整废液的热值，使调配处理后的工业废液具有相当的热值。将调配热值后的液态废弃物通过泵力输送至炉尾塔架顶部的高位储存罐，通过窑头燃烧器的喷枪射入水泥回转窑窑内进行焚烧，将工业废水中有机物燃烧成二氧化碳和水，含铁质、钙质、铝质、硅质等无机物焚烧生成构成水泥的元素，在高温下参与水泥熟料形成的反应，并最终进入水泥制品。', '该技术主要通过利用水泥窑协同处置工业废水，利用水泥窑高温将工业废水中有机物燃烧成二氧化碳和水，含铁质、钙质、铝质、硅质等无机物焚烧生成构成水泥的元素，在高温下参与水泥熟料形成的反应，并最终进入水泥制品，相较于一般污水处理方法，处置过程安全可靠，没有二次污染。目前公司工业废水年处置能力为16000吨，可以解决山西省部分地区危险工业废水污染问题，具有较好的生态效益和社会效益。', '固体废弃物处置及资源化', '协同处置', '清远海创环保科技发展有限责任公司', null, null, null, '山西省水污染防治技术指导目录技术成果报告（2017年）', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('CE009', '中国', '水泥', '利用水泥窑协同处置固体废物技术', '源头控制', '	
根据废物特性和处置要求，废物经过破碎、筛分、配伍等处理后，根据不同的特性分别通过不同的输送方式从多个处置点入窑焚烧。处置点主要包括三个位置：窑头、窑尾和生料磨。废物可以以替代原料、燃料以及其它的形式参与水泥熟料的煅烧过程，替代燃料通过燃烧放热把热量供给水泥煅烧过程，而燃烧残渣则作为原料通过煅烧时的固、液相反应进入熟料主要矿物，燃烧产生的废气和粉尘通过高效收尘设备净化后排入大气，收集到的粉尘则循环利用，达到既生产了水泥熟料又处理了废物、同时减少环境负荷的良好效果。', null, '固体废弃物处置及资源化', '协同处置', '德州中联大坝水泥有限公司、太富环保公司', null, null, null, '环保技术国际智汇平台', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('CE010', '中国', '水泥', '建筑垃圾再生产品制备混凝土技术', '源头控制', '将废弃的建筑垃圾进行一级破碎、二级破碎、一级筛分、二级筛分等工序后，作为骨料替代部分砂石或作为微粉替代部分水泥，可减少水泥或砂石的使用量，降低碳排放。项目用地200 亩、交通运输距离 30公里范围之内较宜。', '建设规模为150 万吨/年处置利用建筑垃圾，碳减排量可达119000吨CO2/年。', '固体废弃物处置及资源化', '原料替代', '北京联绿技术有限责任公司、北京新奥混凝土集团有限公司', '56000万元', null, null, '国家重点节能低碳技术推广目录（2017年本 低碳部分）', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('CE011', '中国', '水泥', '建筑垃圾中微细粉再生利用技术', '源头控制', '以建筑垃圾为原料，利用固体物料在机械力作用下发生晶格畸变、表面断键等特征，使粉体表面具有较高的表面能；利用碱性化学激发剂对处于介稳状态的玻璃体起到解离和促进水化作用，在化学激发剂形成的化学力与机械力协同作用下，显著提高再生胶凝材料的水化活性和粉磨效率，以此制得高活性矿物掺合料，可以替代部分水泥，从而实现碳减排。', '适用于城市建筑垃圾再生资源化利用，年处理 200万t建筑垃圾，100 万t 工业废渣，碳减排量可达300000吨CO2/年', '固体废弃物处置及资源化', '原料替代', '华新水泥股份有限责任公司、华润水泥（广西）有限公司、重庆垚神建筑垃圾回收处置有限公司', '4000万元', '·', null, '国家重点节能低碳技术推广目录（2017年本 低碳部分）', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('CE012', '中国', '水泥', '全制砂配制混凝土技术的研究', '源头控制', '技术革新，全部使用机制砂配制混凝土', '自产机制砂价格24.5元/吨，外购河沙价格84.5元/吨，差价60元/吨，则每方混凝土降低15元。另外混凝土强度及耐久性能会得以大幅度改善，消除因使用劣质河沙带来的混凝土工程质量隐患，为商混企业创立全部使用机制砂配料典范，防止河沙资源过度开采，保护生态环境。', '能源节约及清洁化', '原料替代', '青州中联水泥有限公司', null, null, null, '《水泥行业清洁生产调研报告》', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('CE013', '中国', '水泥', '水泥粉磨系统创新增效技术改造', '生产过程', '公司通过水泥磨隔仓板改造、入V选四通溜子改造、水泥磨空压机改造；水泥粉磨系统新增在线粒度仪、水泥系统普通三相异步电机改为永磁同步电机、水泥系统气力与机械复合混料机改造、水泥粉磨系统皮带机及提升机液耦改磁耦、水泥储存库均化提质改造等方式对公司水泥粉磨系统进行改造。', '1、水泥磨隔仓板改造，水泥产能按照年产70万吨计算，平均电价按照0.55元/kwh计算，年可增加收益为77000元
2、入V选四通溜子改造，循环提升机电流由145A，降低到130A左右，水泥综合电耗降低约0.073kwh/t。水泥产能按照年产70万吨计算,年可增加收益为28105元。
3、水泥磨空压机改造，按照设备年运转300天，用电单价0.55元/kwh计算，每年可节约电费158400元。
4、水泥粉磨系统新增在线粒度仪，平均台时提高3吨，水泥产能按照年增加产15000吨计算,水泥销售价格按照460元/t计算，水泥综合制造成本按照200元/t计算，年可增加收益为3900000元。
5、水泥系统普通三相异步电机改为永磁同步电机，降低水泥综合电耗0.2kwh/t左右。按照年产70万吨计算,年可增加收益为77000元。
6、水泥系统气力与机械复合混料机改造，气力与机械复合式混料机电机总装机功率21kw，低于单轴铰刀式混料机电机功率9kw每年可节约电费26017元。节约维修费及润滑脂31400元。
7、水泥粉磨系统皮带机及提升机液耦改磁耦，水泥产能按照年产70万吨计算年节约电费：700000*0.1kwh/t*0.55元/kwh=38500元，节约维修费：12000元，合计50500元。
8、水泥储存库均化提质改造，水泥库由现在的2年一清延长为4年一清，年可节省外协施工费用10万元。', '能源节约及清洁化', '粉磨系统改造/节能降耗', '枣庄创新山水水泥有限公司', null, null, null, '《水泥行业清洁生产调研报告》', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('CE014', '中国', '水泥', '水泥回转窑系统降阻增效改造 ', '生产过程', '改造内容：
①预热器系统旋风筒入口降阻改造，将三级、四级、五级旋风筒入口处平段进行取斜改造，避免积料现象，C1筒出口负压降低约80Pa。
②预热器鹅颈管降阻改造，将鹅颈管弯头处底部2100mm大曲率平面改造成600mm，减少积料现象，C1筒出口负压降低约50Pa。
③旋风筒内筒降阻改造。将预热器三级、四级、五级旋风筒内筒缩短，由原5环挂板改为3环，各缩短130cm，降低系统阻力，C1筒出口负压降低约100Pa。', '（1）提升产量增效（每年运行时间按照202天计算，吨熟料利润按照200元计算）：5*24*202*200=4848000元。
（2）降低电耗增效（年熟料产量按照120万吨计算，平均电价按照0.55元/kwh计算）：0.35*1200000*0.55=231000元。', '能源节约及清洁化', '回转窑改造/节能降耗/产量增效', '枣庄创新山水水泥有限公司', null, null, null, '《水泥行业清洁生产调研报告》', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('CE015', '中国', '水泥', '翻板阀改造', '生产过程', '将企业窑尾预热器系统采用的锁风效果较差，系统内漏风严重，容易造成煤耗电耗偏高的老式传统单翻板锁风阀进行改造；并对预热器系统进行优化，降低生产煤耗电耗，对预热器C1-C2 单翻板锁风阀（共计10个）进行改造。', '改造后预期标煤耗可降低0.5kg／t，综合电耗降0.5kwh／t，C1出口温度较前期降低约10℃，年综合效益约159.3万元。', '大气污染防治', '设备改造', '滕州中联水泥有限公司', null, null, null, '《水泥行业清洁生产调研报告》', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('CE016', '中国', '水泥', '烧成系统新型隔热节能耐火砖运用更换', '生产过程', '通过将烧成系统新型隔热节能耐火砖运用更换，采用新型隔热节能耐火砖替代原有的普通耐火砖，新型隔热耐火砖应用于整个回转窑内衬筑砌', '技改后回转窑筒体整体平均温度低于200℃，较当前筒体平均温度降低约120℃，可实现标煤耗降低降低4-5kg／t；按年产熟料110万吨，年可节约成本约467.5万元。', '能源节约及清洁化', '设备改造/碳减排', '滕州中联水泥有限公司', null, null, null, '《水泥行业清洁生产调研报告》', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('CE017', '中国', '水泥', '节能风机改造', '生产过程', '改造为高效节能风机', '经节能改造后，产生的直接经济效益如下：每年将减少285.67万kWh耗电量；每年将节约171.40万元成本。同时，还将间接产生以下效益（按每万度电折合3吨标煤，排放8.72吨C02算）：每年可节省标煤约857.01吨；每年可减少C02排放约2491.04吨。', '能源节约及清洁化', '设备改造/碳减排', '滕州中联水泥有限公司', null, null, null, '《水泥行业清洁生产调研报告》', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('CE018', '中国', '水泥', '袋收尘超低排放改造', '生产过程', '企业窑尾烟气处理采用的低压长布袋除尘器，原设计的粉尘浓度排放浓度＜20mg／Nm3的要求为依据，现在已不能满足当前国家和地方的环保要求。要实现超低排放，排放目标在 5mg／Nm3左右。项目利用原有除尘器本体，不需改造除尘器本体加高，只对布袋及袋笼增加长度即可，同时对除尘器的防腐、密封一并完善，达到节省投资，实现超低排放要求。', '通过上述技改后，工况正常运行时，布袋过滤风速在0.55-0.60m／min，达到了2mg／Nm3以下，实现了超低排放要求。', '大气污染防治', '设备改造/碳减排', '滕州中联水泥有限公司', null, null, null, '《水泥行业清洁生产调研报告》', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('CE019', '中国', '水泥', '布袋除尘器', '生产过程', '尘粒在绕过滤布纤维时，受到惯性力作用与纤维碰撞而拦截。由于纤维间得空隙小于气体分子冲击不断改变运动方向，尘粒便与纤维碰撞而被分离出来。其工作过程与滤料的编制方法。纤维的密度及粉尘的扩散．惯性．遮挡．滤布是布袋除尘器的关键，性能良好的滤布，除特定的致密度和透气性外，还应有良好的性。耐热性及较高的机械强度。耐热性良好的纤维，其耐热度目前可达250℃－350℃。', '除尘效率可达99.9%', '大气污染防治', '设备改造', '滕州中联水泥有限公司', null, null, null, 'http://www.zhixinhb.cn/bdccq/2978.html', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('CE020', '中国', '水泥', '水泥工业大脑', '生产过程', '该项目将大数据、人工智能等技术与水泥熟料生产工艺深度融合，围绕水泥熟料生产的能耗优化、质量稳定，利用人工智能技术精准建模，寻求产量、质量、能耗之间的最佳控制参数，在不改变生产工艺和生产设备的前提下，达到高产量、低能耗、质量稳定的目标。项目研发主要分为数据处理、算法建模、机器学习、自动驾驶四个步骤。', '水泥工业大脑上线运行后，综合能耗下降6.73％。2020年实现同比节约标准煤1.54万吨，节电242.3万度，减排二氧化碳7187.5吨、氮氧化合物166.6吨、二氧化硫179.5吨。', '资源高效利用/能源节约及清洁化', '智能化/优化控制/深度学习', '山东东华水泥有限公司', null, null, null, '《水泥行业清洁生产调研报告》', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PE001', '中国', '石化', '隔油', '源头控制；末端处理', '隔油是重力分离方法的一种，浮油、粗分散油和悬浮物利用两相的重力差进行分离，分离设施有平流、多层平板、斜板和斜管隔油池等。油珠在废水中的上浮速率是隔油池设计的主要依据，一般认为油珠上浮速率主要取决于粒径的大小及油品的密度和黏度。多层平板和斜板、斜管隔油池的分离规律是：沉降澄清液量和沉降槽的总表面积成正比，沉降所需时间和沉降垂直距离成正比因此，它们的分离效率大大优于一般平流隔油池。', '通过物理或化学手段将两种液体分离，以实现回收和利用油品的目的。当油珠粒径越大、油品和水的密度差越大、污水黏度越小时，隔油效果越好。', '水污染防治；资源高效利用', '污染防治；水油分离', '中国石化化工总公司/中国石油化工股份有限公司/中国海洋石油总公司', null, null, null, null, '隔油技术在石化行业中通常被用于源头控制，也就是在原料加工、生产工艺设计等阶段使用，旨在避免油污物进入水体、土壤等自然环境中。这种技术可以减少污染物的排放，降低环境风险和治理成本，并且有助于提高生产效率和节约资源。在一些特定情况下，隔油技术也可以用于末端处理，但这通常是在其他治理手段无法完全清除油污物时使用的辅助手段。');
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PE002', '中国', '石化', '加压溶气气浮法', '末端处理', '溶气气浮分离，是将油珠或颗粒物强制吸附在微细空气泡表面上，使其形成比水轻的颗粒体浮上水面和水分离。油珠等黏附在空气泡表面的几率，首先取决于油珠和空气泡之间的 碰撞速度和碰撞率。另外，其黏附情况和气泡的气相、油珠的液相及水的三相间的界面张力，即和其相互之间的接触角有密切关系。溶气气浮分离法的种类很多，其中最常用的一种是加压溶气气浮法。其过程是用泵将废水送入溶气罐，加压到0.3-0.55 Mpa，同时注入空气，使空气在压力下溶解和分散于废水，一般溶气时间在1~3 min，然后废水通过释放器进入气浮池，由于骤然减压，便形成许多微细气泡逸出，从而捕集水中分散油和悬浮物并实现上浮分离。主要优点是气泡直径小，一般为30~120 mm。因此，在供气量相同的情况下，气泡的总表面积大，吸附能力大；同时气泡上浮的速率慢，与被吸附杂质的接触时间长，从而提高气浮效果', '高效净化水质：加压溶气气浮法能够高效地去除水中的悬浮物、油脂、蛋白质、颜料、氨氮等有机污染物和无机污染物，能够显著提高水质的净化效果。
提高处理效率：加压溶气气浮法能够快速形成气泡悬浮物，悬浮物沉降速度快，处理效率高，可以有效地提高水处理的效率。
节能降耗：加压溶气气浮法相比传统的水处理技术，能够节省大量的能源和化学药剂的使用，降低处理成本。
适用范围广：加压溶气气浮法适用于各种不同的水源和处理工艺，包括污水处理、工业废水处理、饮用水净化等多个领域。', '水污染防治；资源高效利用', '节能降耗；污染防治；水油分离', '中国石油天然气集团公司/中国石化化工总公司/中国石油化工股份有限公司', null, null, null, null, null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PE003', '中国', '石化', '涡凹气浮法', '末端处理', '经过预处理后的污水流入装有涡凹曝气机的小型充气段，污水在上升过程中通过充气段与曝气机产生的微气泡充分混合，曝气机将水面上的空气通过抽风管道转移到水下。曝气机的工作原理是利用空气输送管底部散气叶轮的高速转动在水中形成一个真空区，液面上的空气通过曝气机输入水中，填补真空，微气泡随之产生并螺旋形地上升到水面，空气中的氧气也随之溶入水中。
由于气水混合物和液体之间密度的不平衡，产生了一个垂直向上的浮力，将SS带到面。上浮过程中，微气泡附着到SS上，到达水面后SS便依靠这些气泡支撑和维持在水面，浮在水面上的SS间断地被链条刮泥机清除。刮泥机沿着整个液面运动，并将SS从气浮槽的进口端推到出口端的污泥排放管道中。污泥排放管道里有水平的螺旋推进器，将所收集的污泥送入集泥池中。净化后的污水流入溢流槽再自流至生化处理部分。
开放的回流管道从曝气段沿着气浮槽的底部伸展。在产生微气泡的同时，涡凹曝气机在有回流管的池底形成一个负压区，这种负压作用使废水从池底回流至曝气区，然后又返回气浮段。这个过程确保了40%左右的污水回流及在没有进水的情况下气浮段仍可进行工作。
石油炷和胶体乳化物的表面带有正（负）电荷，存在着双电层，乳化体系的稳定性与其电动电位 (即zeta电位) 有密切关系。乳化层经压缩双电层，失去稳定性，促使极小胶体颗粒凝聚成大颗粒从水中分离，这种现象统称为破乳或脱稳。不过脱稳后的颗粒过小，需相当长的时间方能从水中分离，因而须加入絮凝剂，借助絮凝剂的吸附、中和、架桥和絮体的捕集等作用使其加速分离。
大量试验和生产运行实践证明，采用气浮法处理含油废水，在不投加凝聚剂时分散除率仅为40%左右，而投加适合的凝聚剂（无机凝聚剂）后，分散油的去除率可提高到70%左右。', '涡凹气浮系统是专门为去除工业和城市污水中的油脂、胶状物及固体悬浮物(SS)而设计的系统。', '水污染防治；资源高效利用', '节能降耗；污染防治；水油分离', '中国石油天然气集团公司/中国石油化工股份有限公司/中海油能源发展股份有限公司', null, null, null, null, null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PE004', '中国', '石化', '烟气湿法洗涤', '末端处理', '烟气湿法洗涤（FGS工艺）是烟气与吸附剂反应脱除其中的SO2与颗粒物，吸收剂为石灰石、钠碱、海水等，脱硫技术为典型的湿法洗涤工艺，主要包括湿式气体洗涤器（WGS）和净化处理单元（PTU）两部分，在WGS中使用苛性碱或苏打吸收烟气中的SO2并转化为硫酸钠，夹带的粉尘通过缓冲溶液进行洗涤。洗涤液沉淀后进入PTU单元，再经酸碱中和、沉降、氧化、提浓、脱水后变成符合卫生要求的固体物进行填埋处理。以钠碱为吸收剂时SO2和粉尘脱除率均可达90%以上，固体废弃物少。缺点是试剂费用高。', '气体净化：该技术可以有效地去除石化生产过程中排放的废气中的污染物，如硫化物、氮氧化物、氨气、苯、苯乙烯等有机物等。烟气湿法洗涤技术通过将废气与水接触，将污染物吸附在水中，从而实现气体净化的目的。
节能环保：相较于传统的烟气处理技术，烟气湿法洗涤技术能够大大减少能源的消耗和环境污染物的排放，达到节能环保的目的。
适用性广：烟气湿法洗涤技术适用于各种不同类型的废气处理，包括高温废气、低浓度废气、高浓度废气等。', '大气污染防治', '节能降耗；污染防治；烟气脱硫', '中国石油天然气集团公司/中国石油化工股份有限公司/中国石油大庆油田公司', null, null, null, null, null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PE005', '中国', '石化', '湿法制硫酸', '末端处理', '湿法制硫酸通过固相转化器将烟气中的SO2氧化为SO3，SO3再经水吸收生成硫酸。该工艺技术脱硫率可达95%，且不消耗化学试剂和吸收剂，不产生废弃物，过程简单，操作维护费用较低。', '环保净化：湿法制硫酸技术可以有效地去除石化工业废气中的二氧化硫（SO2），从而实现废气的净化和环保的目的。在该技术中，SO2通过与水反应生成亚硫酸和硫酸，从而实现二氧化硫的净化。
节能降耗：湿法制硫酸技术不仅可以有效地去除SO2，还可以回收和利用废气中的热能，降低能源消耗，从而实现节能降耗的目的。
高效生产：相较于传统的干法制酸工艺，湿法制硫酸技术具有生产效率高、产品质量稳定、工艺流程简单等优点，能够实现高效生产。', '大气污染防治', '节能降耗；污染防治；烟气脱硫', '中国石油天然气集团公司/中国石油化工股份有限公司/中海油能源发展股份有限公司', null, null, null, null, null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PE006', '中国', '石化', '干法/半干法烟气脱硫', '末端处理', '干法工艺使用干粉作吸收剂，半干法工艺则使用湿吸收剂但做成干粉使用。吸收剂在稀相提升管流化床吸附器（ESR）中吸收烟气中的SO2吸收饱和的吸收剂在再生塔鼓泡床中经燃料气再生，再回到吸收器中。吸附剂为金属氧化物（如MgO）,操作温度在120 ~930摄氏度，脱硫率达到95%以上。该工艺的优点是 不降低排气温度，扩散效果好，没有水污染问题；不足之处是吸附反应仅在固体表面进行，内部反应时间长，吸附塔很大且吸收剂用量大。', '环保净化：干法/半干法烟气脱硫技术可以有效地去除石化工业废气中的二氧化硫（SO2），从而实现废气的净化和环保的目的。在该技术中，通过加入适量的氧化剂和碱性吸收剂，将SO2氧化为硫酸根离子，从而实现二氧化硫的净化。
节能降耗：干法/半干法烟气脱硫技术不需要使用大量的水和能源，因此相对于湿法脱硫技术具有更低的能耗和投资成本，可以实现节能降耗的目的。
产品回收：干法/半干法烟气脱硫技术可以回收硫酸根离子，并将其转化为高价值的硫酸，从而实现产品的回收和再利用。
应用灵活：干法/半干法烟气脱硫技术适用于不同种类的燃料和不同的烟气成分，具有应用灵活的优点。', '大气污染防治', '节能降耗；污染防治；烟气脱硫', '中国石油天然气集团公司/中国石油化工股份有限公司/中国海油集团有限公司/中国神华能源股份有限公司', null, null, null, null, null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PE007', '中国', '石化', '低磷水处理技术', '源头控制', '缓蚀剂的作用是其在金属表面与腐蚀介质两相之问形成一层保护膜，通常可分为三种类型：氧化膜、沉淀膜和吸附膜。形成氧化膜的缓蚀剂主要为无机盐氧化剂，如铬酸盐、重铬酸盐、钼酸盐、钨酸盐、亚硝酸盐等；形成沉积膜的缓蚀剂主要为有机盐，如羧酸盐、有机磷酸、聚磷酸盐等，它们与水中的Ca2+等两价金属离子或作为缓蚀剂加人的Zn2+作用，在金属表面形成难溶性沉积膜；形成吸附膜的缓蚀剂主要为某些含O、N、S等杂原子、具有表面活性的有机物，如有机胺类、硫脲类、咪唑啉类、芳香唑类等，它们大都具有能吸附于金属表面的亲水基团和遮蔽金属表面的疏水基团，在清洁的金属表面形成覆盖膜，从而抑制腐蚀。对低磷水处理技术，由于磷酸盐派度降低，一定程度影响其缓蚀效果，因而必须与其他类型的缓蚀剂如锌盐进行复合，利用两者之间存在的协同增效作用原理，弥补了因磷酸盐㳖庋降低而影响循环水处理的缓蚀效果。', '低磷水处理技术可以有效地降低水中磷酸盐的含量，减少对水体的污染，提高废水的水质，达到一定的排放标准，降低环境污染的程度。低磷水处理技术使用的药剂成本较低，且处理后的水质较高，可以降低后续处理的成本，节约企业的运营成本。', '水污染防治', '污染防治；节约资源；循环水处理', '中国石油天然气集团公司/中国石油化工股份有限公司/中海油能源发展股份有限公司', null, null, null, null, null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PE008', '中国', '石化', '无磷水处理技术', '源头控制', '在循环水处理技术领域，由于当前尚无特效的无磷缓蚀剂，因此，无磷水处理技术解决循环水系统设备腐蚀主要是利用无机锌盐与其他类型的缓蚀剂之间存在的协同增效作用，提高其缓蚀剂效果，解决设备腐蚀。并利用具有优异阻垢分散效果的多元共聚物，解决设备的结垢。使用低毒高效的杀生剂，控制滋生生物黏泥，从而使循环水的处理效果满足生产装置长周期运行的需要。', '降低废水中磷的含量：无磷水处理技术可以通过化学沉淀、生物吸附等方法将废水中的磷去除，从而降低废水中磷的含量。这有助于减少水体富营养化的程度，避免水体产生蓝藻等有害生物。
提高污水处理效率：磷是废水中的重要污染物之一，去除磷可以提高污水处理效率，减少处理成本。
保护水资源：无磷水处理技术可以减少污染物对水资源的损害，保护水资源，维护生态平衡。
符合环保要求：无磷水处理技术是一种环保的水处理方法，符合国家和地方环保要求。', '水污染防治', '污染防治；节约资源；循环水处理', '中国石油天然气集团公司/中国石油化工股份有限公司/中海油能源发展股份有限公司', null, null, null, null, null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PE009', '中国', '石化', '剩余污泥减量生化技术', '生产过程', '当前开发的剩余污泥减量的生化工艺技术类型较多，如好氧一沉淀一厌氧(OSA）工艺、高浓度溶解氧工艺、与臭氧结合的活性污泥工艺等，其中活性污泥与分离膜结合形成的膜生物反应器(MBR） 技术最具代表性。1969年 Smith等首先报道的由超滤代替沉淀池技术，不但提高丁污水处理的效果和效率，而且大幅减少了剩余污泥产量，较传统的污水生化处理技术最示出明显优势，因而成为研发热点。MBR技术经过此后的不断完善，技术优势在工业应用中进了验证，膜池MISS质量浓度达到8000~14000 mg/L、剩余污泥量减少1/3以上、占地减少1/2~2/3等。因而到20世纪90年代，在美国、日本等发达国家的市政污水处理、工业污水处理等领域得到了推广应用。', '减少废水处理的难度：石化企业生产过程中，污水中含有高浓度的有机物和氨氮等难以降解的污染物，废水处理难度大。剩余污泥减量生化技术可以在废水处理的过程中减少污泥的产生，从而降低废水处理的难度。
减少废物处理成本：石化企业在生产过程中会产生大量的污泥，废物处理成本很高。剩余污泥减量生化技术可以通过优化污泥的生化过程，减少污泥的产生量，从而降低废物处理的成本。
减少污染物排放：剩余污泥减量生化技术可以减少废水处理和废物处理过程中产生的污泥量，减少污染物的排放，达到环保的目的。', '水污染防治；固体废弃物处置及资源化', '污染防治；固体污染物减量化', '中国石化大庆石化分公司/中国石化上海石化公司/中国石油兰州石化公司', '中国石化湛江东兴石油化工有限公司：ＳＭＲ污泥减量装置运行费用主要包括减量剂、蒸汽、电、净化风、除盐水及硫酸、剩余残渣外委费，根据各物料的单耗和单价计算，标定期间总运行成本６７５０元。', null, null, null, null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PE010', '中国', '石化', '污水适度处理回用', '末端处理', '污水适度处理回用是指达到国家环保排放标准的外排污水再经过生化、消毒、除味、脱色、过滤等技术措施，使水质得到适度改善而达到回用循环冷却水水质标准，回用到循环系统后采用水质稳定技术使设备腐蚀、结垢、生物黏泥等水质问题得到有效控制的过程。因此，污水适度处理回用包括两方面技术：一是改善水质技术，二是稳定水质技术。', '节约淡水资源：适度处理后的污水可以被用于一些不需要高质量水的生产环节，如冷却水循环、消防用水等，从而减少了对淡水的需求，节约了淡水资源。
减少污水排放：通过回用适度处理后的污水，可以减少石化企业的废水排放量，降低对环境的影响。
提高生产效率：适度处理后的污水可以被直接用于生产过程中，这不仅可以节约水资源，还可以提高生产效率，减少企业的生产成本。
降低废水处理成本：适度处理后的污水回用于生产过程中，可以减少废水的产生量，降低废水处理成本。', '水污染防治', '污染防治；节约资源；污水回用', '中国石化大庆石油化工公司/中国石化炼化工程技术有限公司/中国石油天然气集团公司/中国海洋石油总公司', null, null, null, null, null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PE011', '中国', '石化', '污水深度处理回用', '末端处理', '污水深度处理回用是指对达到国家环保排放标准的外排污水，采用生化、氧化、絮凝过滤、活性炭吸附、超滤（UF）、杀菌、反渗透（RO）、混床等组合工艺进行处理，得到脱盐水的技术。污水深度处理回用包括两方面含义：一是采用去除污染物技术，将污水中大部分污染物去除，使污染物降低到接近新水指标，即污水的预处理；二是采用反渗透技术进行脱盐，将99%左右的盐脱除，得到准一级脱盐水，再经混床精处理，使水质达到锅炉给水标准并回用于锅炉。', '节约淡水资源：深度处理后的污水可以被用于需要高质量水的生产环节，如蒸馏、冷凝、洗涤等，从而减少了对淡水的需求，节约了淡水资源。
减少污水排放：通过回用深度处理后的污水，可以减少石化企业的废水排放量，降低对环境的影响。
提高生产效率：深度处理后的污水可以被直接用于生产过程中，这不仅可以节约水资源，还可以提高生产效率，减少企业的生产成本。
提高产品质量：深度处理后的污水中的一些有害物质和离子可以被去除，从而减少了对产品质量的影响，提高了产品的质量和可靠性。
降低废水处理成本：深度处理后的污水回用于生产过程中，可以减少废水的产生量，降低废水处理成本。', '水污染防治', '污染防治；节约资源；污水回用', '中国石油天然气集团公司/中国石油化工股份有限公司/中国海油集团公司', null, null, null, null, null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PE012', '中国', '石化', 'MCI（RICH）最大量提高催化柴油十六烷值的加氢技术', '生产过程', 'MCI（RICH）是一种高效催化剂，能够在中低温下催化裂化重质烃，产生高质量的轻质烃和低芳烃柴油。它能够显著提高催化柴油的十六烷值，同时降低芳烃含量和硫含量。
主要参数：反应温度在300-400℃之间，反应压力在2-6MPa之间，氢油比在500~1000之间。', '该技术能够显著提高柴油的十六烷值，同时降低芳烃含量和硫含量，使得柴油的燃烧更加完全，减少了污染物排放，提高了石化产品的质量。', '能源节约及清洁化；大气污染防治', '污染防治；节约资源；提升品质', '中国石油化工股份有限公司/中国石油天然气集团公司/中海油能源发展股份有限公司', null, null, null, null, null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PE013', '中国', '石化', 'FDAS柴油两段加氢深度脱硫脱芳技术', '生产过程', '该技术的概况：FDAS（Fixed-bed Two-stage Hydrodesulfurization and Aromatics Saturation）柴油两段加氢深度脱硫脱芳技术是一种新型柴油加氢脱硫技术。该技术采用两段反应器，第一段反应器采用固定床反应器，主要用于深度脱硫，第二段反应器采用液相反应器，主要用于脱芳。该技术可以同时降低柴油中的硫含量和芳烃含量，提高柴油的品质。
主要参数：第一段反应器的反应温度在320-380℃之间，压力在2-4 MPa之间；第二段反应器的反应温度在320-360℃之间，压力在1.5-3 MPa之间。', '该技术可以有效地降低柴油中的硫含量和芳烃含量，提高柴油的品质，减少污染物排放。', '能源节约及清洁化；大气污染防治', '污染防治；节约资源；提升品质', '中国石油天然气集团公司/中国石油化工股份有限公司/中海油能源发展股份有限公司', null, null, null, null, null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PE014', '中国', '石化', 'MHUG中压加氢改质', '生产过程', '概况：该系列技术主要是采用高效催化剂，通过加氢反应将重质原油中的杂质、硫、氮、芳烃等物质转化为清洁低凝柴油。
主要参数：反应温度为330-380℃，压力为3.0-4.0 MPa，加氢量为600-800 L/L。', '可以降低燃油中的硫含量、减少颗粒物和NOx的排放，提高燃油的质量和燃烧效率。', '能源节约及清洁化；大气污染防治', '污染防治；节约资源；节能降耗；提升品质', '中国石油化工股份有限公司/中国石油天然气集团公司/中国海油集团有限公司', null, null, null, null, null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PE015', '中国', '石化', '生产清洁低凝柴油的系列加氢技术(包括FHDW、FHUG-DW和FHI等)', '生产过程', '该技术的概况和主要参数是：该技术采用系列加氢反应器，通过加氢反应将原油或重油中的杂质和不饱和烃等有害成分去除，从而生产出清洁低凝点的柴油。主要参数包括反应器温度、压力、氢气流量和催化剂种类等。', '在石化中，该技术可以显著降低柴油中的硫、氮、多环芳烃等有害成分含量，从而减少柴油燃烧排放对环境的影响，提高燃油利用效率，降低机械设备维护费用。', '能源节约及清洁化；大气污染防治', '污染防治；节约资源；节能降耗', '中国石油化工股份有限公司/中国石油天然气集团公司/中海油能源发展股份有限公司', null, null, null, null, null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PE016', '中国', '石化', '高柴油收率的FDC单段加氢裂化技术', '生产过程', '概况：FDC单段加氢裂化技术是指在一段反应器内，采用氢气作为催化剂，对重质石油馏分进行加氢裂化，从而实现高柴油收率的目标。
主要参数：反应温度为430-460℃，压力为3.5-4.0 MPa，空速为1.5-2.5 h^-1。', '可以提高柴油收率，减少催化剂的使用量和能耗，降低产品中的硫含量和芳烃含量。', '能源节约及清洁化；资源高效利用', '节约资源；节能降耗；提升品质', '中国石化集团公司/中国石油化工股份有限公司/中海油能源发展股份有限公司', null, null, null, null, null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PE017', '中国', '石化', 'RTS柴油深度脱硫工艺技术', '生产过程', '该技术的概况和主要参数是：RTS柴油深度脱硫工艺技术采用催化剂在高温高压条件下将柴油中的硫化物转化为可被轻松脱除的硫化氢，从而实现深度脱硫。该工艺的主要参数包括反应器温度、压力、氢气流量、催化剂种类等。', '在石化中，该技术可以显著降低柴油中的硫含量，从而减少柴油燃烧排放对环境的影响，同时提高燃油利用效率和机械设备的使用寿命。', '能源节约及清洁化；大气污染防治', '能源节约及清洁化；大气污染防治', '中国石油天然气集团公司/中国石油化工股份有限公司/中国石化集团公司', null, null, null, null, null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PE018', '中国', '石化', '高芳烃LCO加氢转化生产高价值石脑油技术(包括FHC-LCO和FD2G)', '生产过程', '该技术的概况：通过将低价值的LCO（Light Cycle Oil，轻质环烷烃馏分）加氢转化，生产出高附加值的石脑油产品，以提高原油加工厂的经济效益。
该技术的主要参数包括：反应温度、反应压力、催化剂种类及质量、加氢氢气流量等。例如，该技术在反应温度为370-400℃，反应压力为2.5-3.0 MPa，催化剂种类为CoMo/Al2O3，催化剂质量为2.5-3.0%，加氢氢气流量为600-800 m3/m3·h的条件下进行。', '在石化中，该技术可以提高原油加工厂的经济效益，同时降低产品的硫含量和芳香烃含量，减少环境污染。', '资源高效利用；能源节约及清洁化；大气污染防治', '污染防治；节约资源；节能降耗', '中国石油化工股份有限公司/中国石油天然气集团公司/中海油能源发展股份有限公司', null, null, null, null, null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PE019', '中国', '石化', 'FSDS串联反应器超深度脱硫技术', '生产过程', '该技术主要采用串联反应器结构，利用高效催化剂，通过加氢反应实现柴油中硫化物的脱除。其中，第一级反应器实现前段的脱硫，第二级反应器实现后段的脱硫，从而实现超深度脱硫。
该技术的主要参数包括反应器温度、压力、催化剂种类和用量等。比如，反应器温度一般为280-360℃，压力为2.5-5.0 MPa，催化剂种类可以是CoMo、NiMo等。', '在石化中，该技术可以有效地降低柴油中的硫含量，从而减少大气污染物的排放，提高柴油的质量和环境友好性。', '大气污染防治；资源高效利用', '污染防治；节约资源', '中国石化集团公司/中国石油化工股份有限公司/中海油能源发展股份有限公司', null, null, null, null, null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PE020', '中国', '石化', '柴油加氢新工艺技术', '生产过程', '柴油加氢是一种石化加工技术，通过将原油中的低质量馏分进行加氢处理，提高其质量和降低硫、氮等杂质含量，从而获得更高品质的柴油产品。该技术的主要参数包括加氢反应温度、压力、氢气流量、反应时间等。', '柴油加氢新工艺技术可以有效地提高柴油的品质，降低排放污染物的含量。它可以降低柴油的硫、氮、磷等有害物质含量，提高柴油的辛烷值和密度，并减少烷值分布的不均匀性，使得柴油的燃烧更加完全，减少废气排放和对环境的污染。', '资源高效利用；能源节约及清洁化；大气污染防治；水污染防治', '污染防治；节约资源；节能降耗', '中国石油化工股份有限公司/中国石油天然气集团公司/中海油能源发展股份有限公司/中国海油集团有限公司', null, null, null, null, null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PE021', '中国', '石化', 'S-RASSG柴油超深度脱硫催化剂选择及级配技术', '生产过程', '该技术的主要参数包括催化剂选择、催化剂级配比例和反应温度等。通过选用适当的催化剂和调节反应条件，可以实现对污染物SOx的高效去除，降低柴油的硫含量，提高柴油的质量，同时也能够减少对环境的污染。', '在石化行业中，该技术的效果显著。它可以有效减少石化生产过程中排放的SOx污染物，达到大气污染防治的目的。同时，该技术也可以提高石化产品的质量，满足市场需求。', '能源节约及清洁化；大气污染防治', '污染防治；提升品质', '中国石油化工股份有限公司/
中国石油天然气集团公司/
中海油能源发展股份有限公司/
中国海油集团有限公司/', null, null, null, null, null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PE022', '中国', '石化', 'SRH柴油液相循环加氢技术', '生产过程', '概况：该技术采用液相循环加氢反应器，通过加氢反应将重质原油中的杂质、硫、氮等物质转化为清洁低凝柴油。
主要参数：反应温度为360-390℃，压力为2.5-3.5 MPa，加氢量为400-600 L/L。', '可以降低燃油中的硫含量和芳烃含量，减少颗粒物和NOx的排放，提高燃油的质量和燃烧效率。', '能源节约及清洁化；大气污染防治', '污染防治；节约资源；节能降耗；提升品质', '中石油/中石化', null, null, null, null, null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PE023', '中国', '石化', 'FD2G高芳烃催柴加氢转化生产高辛烷值汽油技术', '生产过程', '该技术主要参数包括选择合适的催化剂、催化剂的载体、反应温度和压力等。通过适当的调节这些参数，可以实现对原油中高芳烃的加氢转化，生产出高质量、高辛烷值的汽油产品。', '在石化行业中，该技术的效果显著。它可以提高石化产品的质量，生产出更高辛烷值的汽油，同时也能够减少对环境的污染，达到大气污染防治的目的。', '能源节约及清洁化；大气污染防治', '污染防治；节约资源；节能降耗；提升品质', '中国石油化工股份有限公司', null, null, null, null, null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP001', '中国', '造纸', '深度脱木素技术', '生产过程', '深度脱木素技术中提高木素选择性的途径主要是通过保护碳水化合物和提高脱木素速率实现的技术突破，其内部发展的冷喷放技术和锅内高温逆流洗涤技术大大的改善了纸浆的强度特性，提高了洗涤效率，简化了洗浆设备，从而针对余热和残碱加以利用，创新了深度脱木素技术的发展。', '既能使脱木素技术减少或避免剥皮反映，又能促进木素的降解和脱落，缩短蒸煮时间，提高蒸煮效率，以此方式增加纸张的强度。', '资源高效利用；能源节约及清洁化', '节能降耗；提升效率', null, null, null, null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP002', '中国', '造纸', '锅炉烟气余热回收技术', '生产过程', '利用省煤器、多管式换热器等装置确保烟气热量的回收，通过加热锅炉补水、加热空气用作锅炉烟气余热保证的原辅助材料，保证节煤效果和锅炉的整体热效率。', '实现了热量的回收利用，减少了煤等能源的消耗。', '资源高效利用；能源节约及清洁化', '热量回收；降低煤耗', null, null, null, null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP003', '中国', '造纸', '厌氧处理废水沼气利用技术', '末端处理', '厌氧处理废水沼气利用技术通过对传统废水处理装置进行改进，增加厌氧与沼气处理系统。', '由于造纸废水中含有较丰富的有机物，采用厌氧工艺处理造纸废水，可以实现造纸废水沼气的回收利用。', '水污染防治；资源高效利用', '沼气处理；沼气回收利用', null, null, null, null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP004', '中国', '造纸', '造纸污泥的生物精炼', '末端处理', '造纸污泥去灰分之后，在生物乙醇制备方面有很大潜力，硫酸盐法制浆得到的造纸污泥可作为丁醇生产的原料；造纸污泥中的有机固体废弃物进行厌氧消化处理用以破坏病原菌和产生再生能源—沼气的同时, 还避免了与有机废弃物处理的相关问题。', '实现了污泥资源化利用的同时，能够产生再生能源沼气，减少了有机废弃物的处理这一环节，做到了清洁生产。', '固体废弃物处置及资源化；资源高效利用', '节能降耗；污泥资源化', null, null, null, null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP005', '中国', '造纸', '造纸污泥填料化', '末端处理', '造纸污泥在制备黏土砖、建筑涂料等方面已具有一定研究进展。', '将污泥用于其他领域的原料，实现了污泥的资源化利用，同时减少了固体废弃物的产生。', '固体废弃物处置及资源化；资源高效利用', '减少固废；污泥资源化', null, null, null, null, null, null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP006', '中国', '造纸', '电机变频改造', '生产过程', '相关电机是根据纸机的最大生产能力设计的, 而生产中客户对于宽幅、克重等的不同需求, 造成电机实际功率需调整, 传统电机只能调整转速, 但电耗是基本相同的。采用变频调速调节方式取代传统的阀门调节, 减少了电机的启动电流, 节电效果明显, 并且改善流量, 流速和压力控制精度, 提高产品质量。', '通过调节电机达到减少启动电流的目的，实现清洁生产和电力资源的节约，减少温室气体CO2的排放。', '资源高效利用；能源节约及清洁化', '电力节约；碳减排', null, null, null, null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP007', '中国', '造纸', '锅炉加装分层给煤装置', '生产过程', '造纸企业使用的正转链条锅炉采用普通给煤方式, 存在燃烧不完全, 着火条件差, 灰渣可燃物含量高等缺点。锅炉分层给煤装置, 由给煤、调煤、分层、传动等部分组成, 位于炉排进煤处, 按照生产负荷调整给煤量煤经过播煤辊和筛分器被筛分成大小块和煤粉由下而上分层布于炉排, 煤层疏松、均匀, 透气性好。', '改善燃烧工况, 减小鼓风阻力, 增大煤与空气接触, 大块于下层易燃尽, 煤粉于上层减少漏煤, 节煤效果明显。', '资源高效利用', '降低煤耗；提高燃烧效率', null, null, null, null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP008', '中国', '造纸', '烘缸冷凝水回收', '生产过程', '多数企业纸机烘缸冷凝水经过管道汇集到水罐内作为锅炉补充水, 少数企业甚至完全不回收烘缸冷凝水直接排掉, 造成热能的极大浪费。采用冷凝水回收机对热量进行回收, 通过疏水装置将冷凝水引入集水罐, 再经消气蚀处理使高温冷凝水打入汽包, 成为一个闭式循环系统, 凝结水的能量直接回收到锅炉里。', '通过采用冷凝水回收机对热量回收，凝结水的回收温度仅丧失在管网降温部分, 节煤及软化水效果明显。', '资源高效利用', '节约水耗；热量回收', null, null, null, null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP009', '中国', '造纸', '超效浅层气浮处理废水', '末端处理', '以原生木浆、废纸为原料的造纸企业, 其废水含悬浮物比例很高。超效浅层气浮技术在污水引入大量微小气泡, 通过表面张力气泡粘附在细小悬浮物上, 形成整体比重小于水的絮凝物, 密度差使悬浮物浮于水面形成浮渣, 从而实现固液分离。', '流失纤维在此过程中回收, 最大限度地循环使用。配合添加絮凝剂, 悬浮物去除率可达90%以上。不仅降低废水中的悬浮物浓度, 还可去除部分溶解性COD、BOD, 极大的提高水循环利用。', '水污染防治', '废水回用；废水资源化', null, null, null, null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP010', '中国', '造纸', '制浆废水回用', '末端处理', '废纸为原料制浆产生的废水，主要是浆料洗涤、设备冲洗产生的，主要成分为 SS和COD，且COD含量较低。经适当处理，上清液可以继续用于制浆生产中。', '采用废水的循环利用，可以降低制浆过程的取水量和废水产生量。', '水污染防治；资源高效利用', '废水回用；废水资源化', null, null, null, null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP011', '中国', '造纸', '提高白水循环利用率', '末端处理', '在满足生产系统用水的前提下，多余白水回用于制浆系统和纸机对水质要求不严格的生产过程。成形脱水区产生的浓白水回用于机前纸浆的稀释，高压脱水产生的稀白水回用于制浆过程以及除渣过程中。', '通过生产系统废水的循化利用，达到减少和降低取水量和废水产生量的目的。', '水污染防治；资源高效利用', '废水回用；废水资源化', null, null, null, null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP012', '中国', '造纸', '浓缩机改造', '生产过程', '使用新式节能型压力筛，动力消耗低，与老式圆网浓缩机相比，同等筛选面积的消耗功率偏小，单位时间内出浆快。', '通过对浓缩机进行新型改造，实现了浓缩机的低动力消耗，节能效果明显。', '能源节约及清洁化', '节约电耗；低动力消耗', null, null, null, null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP013', '中国', '造纸', '污泥机械脱水', '末端处理', '造纸污泥以板框压滤和带式压滤为主，也有企业开发了连续式污泥深度脱水设备。', '实现污泥与水的分离，分别进行进一步的水处理与固体废弃物处理。', '水污染防治', '废水处理；污泥分离', null, null, null, null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP014', '中国', '造纸', '白水处理技术', '末端处理', '气浮法处理白水是目前白水回用中用得较多的一种回用技术，其中的常规溶气气浮法很早就用于处理造纸白水，后来又开发出射流气浮白水回用技术。目前用得较多的是超效浅层气浮技术；真空过滤法处理白水也有广泛的应用，近年来国内的一些大型造纸企业大力推广真空过滤机用于白水处理，提高白水的处理与循环回用的程度；造纸白水先经微孔过滤处理回收纤维，降低白水中的悬浮物含量，在加混凝剂和助凝剂，使白水中的细小纤维、填料、胶体性物质及部分溶解性有机物聚沉（化学混凝法），处理后的澄清水可回用于生产过程。膜分离技术具有处理效果好、能耗低、占地面积小、操作管理容易等优点。但其处理水量的能力不大、费用较高。', '实现了清洁生产和白水的资源化回收利用，减少水中污染物排放。', '水污染防治', '废水处理；废水资源化', null, null, null, null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP015', '中国', '造纸', '热泵二次蒸汽利用', '生产过程', '采用热泵系统，将烘干部新鲜蒸汽直接通汽方式， 改为节能型的热泵供汽方式。', '充分利用二次余热蒸汽，节约新鲜蒸汽用量，起到降低蒸汽的耗用量', '资源高效利用；能源节约及清洁化', '蒸汽回收利用；节约热能', null, null, null, null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP016', '中国', '造纸', '密闭汽罩回收余热', '生产过程', '对现有烘干部进行改造，采用密闭汽罩，提高烘缸热效率。', '采用此技术能够降低热损失，节约蒸汽，以达到节能降耗的目的。', '资源高效利用；能源节约及清洁化', '蒸汽回收利用；节约热能', null, null, null, null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP017', '中国', '造纸', '黑液资源化', '生产过程', '提取造纸黑液中的木质素，经过改性、磺化合成木质素磺酸钙粘合剂。', '通过此技术提取废弃物中的木质素，实现其资源利用，降低生产成本，减少污染。', '资源高效利用；能源节约及清洁化', '木质素资源利用；降低成本', null, null, null, null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP018', '中国', '造纸', '干湿法备料和连续蒸煮', '生产过程', '把原来的干法备料改为干湿法备料，其次改原来的间歇蒸煮为连续蒸煮，最后拆除掉蒸煮麦草的所有蒸球，用连续蒸煮系统代替。', '该技术能够解决干法备料中产生粉尘乱飞的问题，降低备料期间的噪声污染，同时提高草片的质量。以达到耗能低、污染少、保证纸浆质量的目的。', '资源高效利用；噪声污染防治', '减少粉尘；降低能耗', null, null, null, null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP019', '中国', '造纸', '提取车间的封闭式筛选', '生产过程', '改变原来的开式筛选为封闭式筛选，在提取车间增加双辊挤浆机，把漂白浆中的黑液过滤出来，大大提高黑液提取效率。', '通过该技术，能够提高对黑液的提取效率，降低耗水量。', '水污染防治；资源高效利用', '废水处理；节能降耗', null, null, null, null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP020', '中国', '造纸', '变频磨浆', '生产过程', '用变频技术把粗磨和精磨分开，利用其他生产线耗电较小的精磨设备，优化组合生产流程，在保证浆料质量的同时，为主体设备腾出提高产量的空间，从而实现增产降耗。', '通过区分粗磨和精磨，优化生产路线，合理利用设备，减少电耗，提高产量。', '资源高效利用', '生产流程优化；增产降耗', null, null, null, null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP021', '中国', '造纸', '中浓打浆', '生产过程', '利用纤维间的内摩擦效应，可以使打浆电耗节省30％-40％。', '降低电耗，降低电力成本，减少打浆过程中产生的污染。', '能源节约及清洁化', '降低电耗；减少成本', null, null, null, null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP022', '中国', '造纸', '本色麦草浆清洁制浆技术', '生产过程', '麦草经切断、筛选除尘后进入蒸煮器，在高温环境中与蒸煮化学药品发生化学反应，绝大多数木素及部分半纤维素被溶出，分离出的纤维素(含少量未溶出的半纤维素)经后续的机械疏解、氧脱木素、洗涤、筛选净化过程得到纸浆用于纸张的生产。溶出的木素及部分半纤维素被作为废液进入资源化处理系统。', '(1)降低纤维原料消耗10%；(2)提高除尘效果10%；(3)减少化学药品消耗5%；(4)降低蒸汽消耗20%；(5)节约清水用量50%；(6)提高黑液提取率，黑液提取率>90%；(7)降低生产成本，实现废液资源化利用；(8)不产生AOX和二噁英。', '资源高效利用；能源节约及清洁化', '降低原料消耗；提高生产效率', null, null, null, null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP023', '中国', '造纸', '置换蒸煮工艺', '生产过程', '置换蒸煮系统包括预浸装料、初级蒸煮、中级蒸煮、升温/保温、置换回收、冷喷放等工艺步骤。通过对常规立锅间歇蒸煮进行技术改造后实施该技术，可以得到强度高、卡帕值波动小的浆料，同时浆料质量均匀，有利于减少后续漂白过程化学药品用量，降低中段水污染负荷。', '(1)消除废气喷放对空气的污染；(2)减少进入漂白工段的木素含量；(3)降低漂白废水中的可吸收有机卤化物(AOX)产生量，减少漂白废水AOX排放量20%；(4)减少漂白药品消耗；(5)节省蒸汽消耗，蒸汽消耗量减少至0.55～0.75吨/吨浆。', '资源高效利用', '降低原料消耗；提高生产效率', null, null, null, null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP024', '中国', '造纸', '氧脱木素技术', '生产过程', '氧脱木素是蒸煮脱除木素过程的延伸，蒸煮所得到的纸浆经过筛选、洗涤之后，进入氧脱木素系统。氧脱木素反应所用碱来自氧化白液，所用氧来自空气，洗涤水可用蒸汽冷凝水，滤液直接逆流进入碱回收，降低水耗和化学药品的消耗。主要设备有氧反应塔、刮料器、混合器与加热器。氧脱木素系统一般包括中浓浆泵、混合器、反应塔、喷放塔和洗浆机等。对木浆和竹浆，适当提高蒸煮之后纸浆的硬度，然后通过氧脱木素降低浆的硬度，可获得较高的得率。', '(1)提高木素脱除率；(2)降低纸浆卡伯值40%～50%，以满足现代环保型ECF或TCF漂白的要求；(3)提高制浆得率，降低原料成本；(4)降低漂白污减少漂白废水AOX产生量50%～60%；(5)节约漂白化学品消耗40%～50%，减轻漂白废水污染负荷，COD排放量降低40%。', '资源高效利用', '减少原料消耗；降低污染负荷', null, null, null, null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP025', '中国', '造纸', '无元素氯漂白技术', '生产过程', '采用二氧化氯在中浓度(10%～16%)条件下对纸浆进行漂白，取代氯气和次氯酸盐漂白。二氧化氯不含分子氯，漂白废水的AOX比有氯漂白大大降低，而且二氧化氯在破坏木素但不显著降解纤维素或半纤维素方面有很高的选择性。增加二氧化氯发生器、提升改造漂白主要工艺设备，对漂后洗浆设施进行防腐改造等。减轻漂白废水的污染负荷，改造后可不再新增二噁英的排放，减少化学品的消耗。', '(1)取消元素氯漂白；(2)降低漂白废水的污染负荷，减少漂白废水中50%的COD和80%A O X产生量；(3)在提高纸浆白度的同时，改善漂白浆的强度；(4)降低用水量，减少漂白废水40%。', '资源高效利用', '减少原料消耗；降低污染负荷', null, null, null, null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP026', '中国', '造纸', '镁碱漂白浆化机生产关键技术', '生产过程', '对国外先进、成熟化机浆生产技术再创新，使之适应我国化机浆应用需求和生产线特点，利用镁碱(或直接利用Mg(OH)2)部 分替代烧碱和硅酸钠，用于各类漂白化机浆生产，在基本不影响成浆质量指标条件下，镁碱替代率达到30%～50%。', '(1)降低COD产生量，吨浆COD产生量降低30%～50%；(2)减少SS排放量，吨浆SS排放量下降15%以上；(3)提高制浆得率，吨浆节约木质资源约210～ 300m3 ；(4)有效缓解高浓磨、螺旋压榨等设备结垢问题；(5)解决碱回收法化机浆废液处理硅干扰问题。', '资源高效利用', '减少原料消耗；降低污染负荷', null, null, '该技术在工程运行过程中保持稳定，对环境、技术参数等无干扰。', null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP027', '中国', '造纸', '白水循环综合利用技术', '生产过程', '造纸白水循环综合利用技术包括合理的生产工艺、合适的设备、智能化的DCS模拟控制系统和生产系统的节能优化方案几部分组成。根据不同浆料、不同填料、抄速、纸机幅宽和所产品种等多因素，综合考虑，协同利用，达到白水的高效利用。利用纸机白水代替清水，减低清水使用和能量消耗。', '(1)提高白水循环利用水平，降低造纸用水量10%～40%，吨纸水耗可以控制在小于10吨；(2)纤维填料留着率提高至95%以上；(3)纤维与填料节省10%～50%', '资源高效利用', '减少水耗；降低原料消耗', null, null, '该技术在工程运行过程中保持稳定，对环境、技术参数等无干扰。', null, '调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP028', '中国', '造纸', 'RDH蒸煮技术', '生产过程', '当蒸煮结束时，蒸煮国内热黑液用洗浆机的滤液，也就是用冷黑液进行置换，置换出来的黑液根据温度不同被分别储存在不同的黑液槽中，用于下一次蒸煮时原料和蒸煮白液的预热。蒸煮好的纸浆在蒸煮锅内至少完成1次洗涤，并被冷却下来，然后用压缩空气将其喷放或泵抽至喷放锅。', '（1）RDH蒸煮周期更小；（2）比常规法蒸煮大大减少了新鲜蒸汽用量，可节约70%~80%的蒸汽；（3）减少碱耗，提高纸浆得率；（4）未漂浆和漂白浆强度都高出10%以上。', '资源高效利用', '蒸汽资源利用；减少碱耗', '广东鼎丰纸业', null, '此套设备和技术已经实现产业化，运行良好，性能稳定，已实现大规模应用。', null, '书籍P55', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP029', '中国', '造纸', '棕榈果串高得率浆制高强包装纸和纸板技术', '生产过程', '通过采用自主研发的10万吨级棕榈空果串高得率清洁制浆成套关键技术，可以高值利用东南亚储量丰富的棕榈空果串纤维制造高强本色包装纸和纸板产品。缓解当地造纸工业纤维原料短缺状况，取得经济、社会和环境生态协同效益。', '（1）采用清洁生产工艺提高原料利用率，实现了木质素的最大化利用；（2）生产所用锅炉采用生物质锅炉，不增加当地的碳排放。', '资源高效利用；温室气体减排', '碳减排；原料最大化利用', '马来西亚、印度尼西亚等地区', '技术投资：10万吨级棕榈果串高得率浆制高强瓦楞原纸新建工程总投资35600万元，其中设备投资费18200万元，建筑工程费6057万元，安装工程费2326万元，征地费用2400万元，其他工程及预备费9017万元。
年运行维护费用:棕榈收集运输处理、废纸购入以及水、电、化学品消耗、设备折旧、人员工资等总成本23858万元，其中，年平均固定成本5600万元、可变成本20258万元。', '项目技术属于工程化成熟、当地政府鼓励发展技术，可以实现生产线的长期可持续健康稳定运行，符合清洁生产标准，废水达标排放。', null, '成书彩稿P71', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP030', '中国', '造纸', '造纸碱回收白泥渣生产多孔硅酸盐滤料', '末端处理', '本技术针对造纸白泥高含水率、高碳酸钙、重金属浸出等问题，将造纸白泥与水泥混合，进行固化成型反应脱水，可大大降低造纸白泥煅烧入窑含水率，形成低温煅烧技术。经过煅烧后造纸白泥中的碳酸钙可作为水热合成的钙质原料，将其与粉煤灰、石英尾泥等硅质原料混合，经造粒成球、自养、蒸养后得到多孔硅酸盐滤料。', '该技术对固废进行资源化利用，减少了造纸白泥固废的堆积和填埋，实现了造纸白泥的资源化、减量化和稳定化。', '固体废弃物处置及资源化', '固废资源化；固废减排', '浙江中劲环保科技有限公司', null, '此套设备和技术已经实现产业化，运行良好，性能稳定。', null, '成书彩稿P273', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP031', '中国', '造纸', '管道式分离技术及设备', '生产过程', '管道式分离技术是通过T型管、柱形旋流管、轴向旋流管的多种组合，以适应不同流量、不同含率、不同油品、不同工况、不同处理要求的各种实际使用情况。管道式分离技术的主要优点就是体积小、重量轻、占地面积少，分离效率高，工艺流程简单、操作简便，已成为系统的适用于陆地、海洋平台及深海海底、采油井井底等各种使用环境和条件油田采液处理新技术。可用于造纸行业中的多相分离。', '在新建工程中，可以减少征地面积和大型罐建造数量，极大节省投资费用；在老站扩容改造工程中，可以快速灵活接入原有流程，有效提高原有处理能力，改善出水水质，并可降低药剂使用和加热费用。', '资源高效利用', '降低投资；提高效率', null, null, '该技术在工程运行过程中保持稳定，对环境、技术参数等无干扰。', null, '成书彩稿P136', '也可用于其他行业');
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP032', '中国', '造纸', '低品味余热发电技术', '源头控制', '本技术采用改进的有机朗肯循环系统（ORC）设计技术和关键设备设计技术，通过利用温度较低，流量较小的余热资源，包括地热、光热以及工业余热，形成高温高压的有机工质蒸汽，推动透平机膨胀做功，驱动发电机发电，实现不稳定热源及低品位余热高效利用。现已建立自主知识产权的ORC仿真模拟系统，可对系统进行全局优化，获得最佳工艺参数；同时建立较为完整工质物性数据库和优选系统，能针对特定的低温体系，筛选最为合适的工质，针对不同资源和参数的余热，开发出高速、紧凑、一体式的小型发电机组。', '针对不同企业产生的大量低值或废气的预热，设计开发特定的有机朗肯循环系统进行发电，将多余的热能转化为电能，实现能源多级高效利用，具有一定的经济效益和社会效益。', '能源节约及清洁化', '减少电耗；热能高效利用', null, null, '该技术在工程运行过程中比较稳定，对环境、技术参数等干扰较小。', null, '成书彩稿P137', '也可用于其他行业');
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP033', '中国', '造纸', '30万吨/年废纸中浓制浆关键设备研制及系统成套集成', '生产过程', '该技术研制的转鼓式碎浆机通过内部提料板及隔仓板的结构优化，碎浆浓度高达21%，纤维流失率小于0.8%；通过转子及筛壳底部结构的创新设计，研制的中浓压力筛筛选浓度可达4%（粗筛）。', '使用30万吨/年废纸中浓制浆项目不仅可以节能降耗，提高工效，还可以减少污水排放量，降低成本，可获得一举多得的效果。', '资源高效利用', '节能降耗；污水减排', '东莞金田纸业', '以30吨/年废纸中浓制浆生产线为例，技术寿命为5-10年，所需主要设备为BFW2000链板输送机2台，ZDG400鼓式碎浆机2台，ZSA6B高浓浓除渣器2台，ZNS87中浓压力筛2台，ZNS84中浓压力筛2台，ZDF4B纤维分离机2台，RSH-2排渣分离机2台，ZSA6B中浓除渣器2台，ZNS87中浓分级筛2台一段除渣器2套，二段除渣器2套，三段除渣器2套，四段除渣器2套，ZNS86中浓一段精筛2台，ZNS84中浓二段精筛2台，盘式真空过滤机4台，纸机1台，所需投入资金23000万元。', '该技术在工程运行过程中保持稳定，对环境、技术参数等干扰的敏感程度较低。', null, '成书彩稿P149', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP034', '中国', '造纸', '卫生纸机毛布在线清洁技术', '生产过程', '造纸毛毯因其价格较昂贵，在纸张生产成本中占有一定的比例，所以是影响纸厂效益的重要因素之一。该技术解决了毛布脏污引起的毛布寿命、能耗、车速及质量问题。毛布寿命从不到两个月延长到150天以上（最高226天）；通过保洁清洗，保证毛布在整个寿命期内，清洁状况良好。同时，减少了毛布停机清洗的时间；有效减少真空负载。', '1. 解决了毛布脏污引起的毛布寿命、能耗、车速及质量问题。毛布寿命从不到两个月延长到150 天以上（最高226 天）； 2. 通过在线的保洁清洗，保证毛布在整个寿命期内，清洁状况良好。同时，减少了毛布停机清洗的时间； 3. 因毛布清洁状况改善，真空效率提升，有效减少真空负载； 4. 因真空负载降低，传动阻力下降，纸机传动负载得以降低，减少传动电耗； 5. 因毛布清洁状况获得改善，毛布透水性改善，有效提升压榨脱水效果，降低纸页上缸水分，节省蒸汽耗用成本。', '资源高效利用', '降低负荷；减少电耗', '维达纸业（浙江）有限公司', '技术投资：总费用约42万元，加上管道、阀门、仪表、自控系统，总投资约60万元。
年维护费用：5万元。', '该技术在工程运行过程中保持稳定，对环境、技术参数等无干扰。', null, '成书彩稿P234', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP035', '中国', '造纸', '商业智能系统开发项目', '末端处理', '目前，纸张多采用BOPP 等塑料进行表面覆膜，以保证纸张的美观和使用。但表面覆膜的纸张在回收利用时给纸浆分离增加了很大的难度，导致废纸回收利用率低。其中，回收过程面临的主要问题如下：较大的塑料碎片不利于连续水相中的流动和收集，容易造成纸浆剥落不完全；较小的塑料碎片会导致纸浆与塑料无法分离，增加能耗，影响分离产品的质量和使用效果。因此，该技术利用智能系统控制塑料碎片的大小，找到最佳的纸浆分离效果。破碎机采用内嵌式设计，即在内桶上和动轴上嵌有定刀和动刀，根据不同的物料性质和回收要求，其转速、形状、尺寸大小、刀片安装位置、大小与形状均可以变化；旋转刀片形状为弧形，刀片长度为485mm、宽度为lOOmm、厚度为22mm；固定刀片形状为条状，刀片长度为495mm、宽度为llOmm，厚度为25 mm；刀片高速运转，转速为960r/min；破碎进料室有分开安装的筛网和缓冲室。', '（1）破碎机内嵌式设计可满足破碎尺寸要求，保证破碎效果。（2）缓冲室可避免喂料时的泼撒，机器噪音低，安全可靠。（3）大块塑料切割成10～125px 的长条碎片，纸浆脱离效果最佳。（4）破碎机刀片的高转速运行可实现对固体废弃物的再粉碎，并在强力机械作用帮助下实现一定尺寸的小塑料碎片与纸浆纤维的水中分离。', '固体废弃物处置及资源化', '智能化；固废减排', null, null, '此设备作为环保流水线主体设备的关键设备，提供给公司客户，运行安全可靠，实现了纸浆与塑料的有效分离。', null, 'https://www.greentechbank.com/greentech/web/achv/achivementDetail/b5c09ece6fdc47edbe0017822fbb31c0', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP036', '中国', '造纸', '造纸污泥转化成环保吸收剂', '末端处理', '造纸污泥（来自造纸业）经适当处理后能形成一种高效光吸收材料，可悬浮在水面，有效地吸附疏水性物质（植物油、合成和矿物油、动物脂肪、燃料、有机物质）。经适当应用后，甚至能吸附水面的灰尘。', '实现了污泥资源化利用的同时，能够产生再生能源沼气，减少了有机废弃物的处理这一环节，做到了清洁生产。', '固体废弃物处置及资源化；资源高效利用', '节能降耗；污泥资源化', null, null, '此设备作为环保流水线主体设备的关键设备，提供给公司客户，运行安全可靠，实现了纸浆与塑料的有效分离。', null, 'https://www.greentechbank.com/greentech/web/achv/achivementDetail/eb5934efc8584bcdbebe1b4c83cbedca', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP037', '中国', '造纸', '造纸废弃物再回收设备', '末端处理', '该设备能够高效率实现造纸废弃物再回收。造纸废弃物再回收的设备主要包括破碎机、搓揉机、漂洗槽、离心分离机。
破碎机采用内嵌式设计，即在内桶上和动轴上嵌有定刀和动刀，以满足破碎尺寸要求，保证破碎效果，根据不同的物料性质和回收要求，其转速、形状、尺寸大小、刀片安装位置、大小与形状均可以变化。搓揉机是保证洗脱效果的关键辅助装置，根据不同的物料性质和回收要求，其大小形状，运行参数均可以变化。漂洗槽是进一步洗脱和实现大尺寸物料初步分离的辅助设备，根据不同的物料性质和回收要求，其大小形状，运行参数均可以变化。离心分离机是实现塑料和纸浆连续分离的高效分离设备，其滤网的孔径大小和离心机的大小可以调整和变化。', '通过该技术和设备，能够实现高效率的造纸废弃物再回收，方便进一步实现固体废弃物的资源化，同时在一定程度上减少了固废的排放量，从而减少浪费。', '固体废弃物处置及资源化；资源高效利用', '固体废弃物回收利用', null, null, '此套设备和技术运行良好，性能稳定，生产线生产能力强。此流水线设备分离出的塑料经过加工形成的塑料颗粒，经上海维谱化工技术服务有限公司检测，性能良好。', null, 'https://www.greentechbank.com/greentech/web/achv/achivementDetail/a64b9c23376f43278edfd361f8f32490', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP038', '中国', '造纸', '单张纸高端印刷机关键技术', '生产过程', '单张纸高端印刷机是指具有高速、高精度、高效率的多色印刷机，是该技术突破了与高速纸张控制有关的传递、检测、时序控制等关键技术，发明了高速纸张输送、传递、交接技术，研制了光纤限定反射和超声波技术相结合的高速纸张检测系统，实现了精准的纸张时序控制；突破了墨层控制高精度、强实时、宽印刷幅面等关键技术，研制了国内首套高性能自动墨量控制系统；攻克了高精度印刷过程控制涉及的自动套准、间隙调整、散尾变形、水墨平衡等关键技术，发明了适应厚纸印刷和最少纸张交接次数的滚筒排列结构，研制了不依赖滚筒倾斜调整的印版斜向调整装置，；攻克了印刷机械特性匹配、故障诊断、网络控制等关键技术，开发了符合CIP3/CIP4 国际标准且支持印刷企业管控一体化架构的数字化、网络化、智能化印刷流程系统，可实现印刷作业全过程自动化，大幅提高印刷效率。 ', '该技术的应用，极大地促进了印品质量和印刷效率提高、材料浪费减少、成本降低，使中国印刷向绿色印刷发展，从整体上推进了中国印刷机及印刷行业的科技进步。', '资源高效利用', '智能化印刷；降低成本；提高生产效率', '本成果在国外著名印刷机制造企业得到应用。使用本成果的印刷企业超一千家，并出口到日本、俄罗斯、南非、巴西等国家。', null, '此套设备和技术已经实现产业化，运行良好，性能稳定，生产线生产能力强。', null, 'https://www.greentechbank.com/greentech/web/achv/achivementDetail/3fd0452e608d4409b9b43f8e98b2370b', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP039', '中国', '造纸', '粉煤灰综合利用技术', '末端处理', '该技术的原理与技术关键是把外营力自然成岩理论应用到生产粉煤灰建筑材料中去，它的创造点是利用造纸废水中的废弃物，其中含有大量的表面活性剂和碱性物质，其掺入后对粉煤灰的凝聚、集结起到积极的作用，从而激发了粉煤灰的潜在活性，同时也产生了一种结构性防水、憎水性能。是一种新型节能、利废的建筑材料。', '将造纸废水中的废弃物与粉煤灰混合形成建筑材料；实现了废弃物的资源化利用，同时减少了固体废弃物的产生。', '固体废弃物处置及资源化；资源高效利用', '废弃物利用；粉煤灰资源化', null, null, '该技术在工程运行过程中保持稳定，对环境、技术参数等无干扰。', null, 'https://www.greentechbank.com/greentech/web/achv/achivementDetail/84428fca3cc34c68af4f7a762b268439', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP040', '中国', '造纸', '生物制浆技术', '生产过程', '生物制浆是直接利用微生物降解纤维原料中的木素，解离出纤维，使之成为纸浆。', '该技术具有环境友好性，可降低能耗和化学品用量，因此将生物技术作用于制浆造纸过程，有利于克服化学法所存在的缺点如高化学品消耗、高污染负荷等，从而降低纤维原料用量和废水污染负荷。', '能源节约及清洁', '生物技术；减少污染', null, null, '该技术具有很高的发展潜力，但目前仍处于研究阶段，稳定性一般，距离应用于实际生产还有一定差距，应加大投资，争取早日将生物制浆技术投人产业化生产。', null, 'http://www.paper.com.cn/news/daynews/2017/17040607250667194.htm', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP041', '中国', '造纸', '高得率制浆技术', '生产过程', '高得率制浆可提高资源利用率，减少纤维和化学药品的消耗，采用不产生有机氯化物的新漂剂，能使漂白废水中的BOD,COD和AOX等含量比化学浆少得多，生产过程排放废液的污染负荷轻，废液的回收处理比较简单。例如APMP的制浆得率一般都在85%左右，生产过程中仅有原料量15%的溶出物进入制浆废水中，因此，相对于化学浆(得率为40%~50%)来说，其污染负荷要低得多。', '高得率技术制得的浆中所含废水80%~90%通过螺旋压榨脱水机挤压后可回用，污染负荷的排放量低于其发生量。且排放的废水具有可生化性，采用生物处理最终可达标排放。同时高得率浆具有再制浆的优良性能，有利于废纸的回收再利用。', '资源高效利用', '废水回用；降低污染负荷', null, null, '该技术在工程运行过程中比较稳定，对环境、技术参数等干扰较小。', null, 'http://www.paper.com.cn/news/daynews/2017/17040607250667194.htm', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('PP042', '中国', '造纸', '全无氯漂白技术', '生产过程', '全无氯漂白是无元素氯漂白技术的进一步发展，用不含氯的物质如H202、O2、O3等作为漂剂在中高浓条件下对纸浆进行漂白。无元素氯漂白产生的废水一仍具有一定的微生物毒性，而全无氯漂白废水则检测不出毒性。', '采用全无氯漂白技术可从根本上消除有机氯化物的产生，改变漂白废水对环境的污染。漂白废水可以用作蒸煮后的洗浆用水和配蒸煮药液的稀释水，这样既可节约制浆用水，同时又回收利用废液中的碱基，获取废液中有机物的热能，达到节能增效的作用。', '资源高效利用', '降低水耗；节能增效', null, null, '该技术在工程运行过程中比较稳定，对环境、技术参数等干扰较小。', null, 'http://www.paper.com.cn/news/daynews/2017/17040607250667194.htm', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('ST001
', '中国', '钢铁', '高炉富氧喷煤工艺', '生产过程', '通过在高炉冶炼过程中喷入大量的煤粉并结合适量的富氧。高炉高氧鼓风后，高炉煤气量减少，燃烧温度升高，高温区下移，炉顶温度降低，同时使冶炼行程加快，炉料在炉内的停留时间缩短；而喷吹煤粉后，煤气量增加，理论燃烧温度降低，中心煤气流发展，炉缸温度均匀，高中温区扩大，炉顶温度升高，焦比降低，炉料在炉内的停留时间增长。高炉高氧鼓风与喷吹煤粉两者配合具有协同作用。（相关标准可查阅GB/T33969-2017）', '节能降焦、提高产量、降低生产成本和减少污染。', '大气污染防治', '节能降焦；提高产量', '鞍钢股份有限公司', null, null, null, '钢铁行业调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('ST002
', '中国', '钢铁', '轧钢氧化铁皮生产还原铁粉技术', '生产过程', '采用隧道窑固体碳还原法生产还原铁粉。主要工序有：还原、破碎、筛分、磁选。铁皮中的氧化铁在高温下逐步被碳还原，而碳则气化成CO。', '通过二次精还原提高铁粉的总铁含量，降低O、C、S含量，消除海绵铁粉碎时所产生的加工硬化，从而改善铁粉的工艺性能，达到循环利用的目的。', '资源高效利用', '铁循环利用', '武汉钢铁', null, null, null, '钢铁行业调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('ST003
', '中国', '钢铁', '新型固体物料节能环保输送技术', '生产过程', '通过离散元方法及有限元方法，采用三维立体设计建模技术，借助于先进的颗粒学仿真软件以及有限元分析软件，对散状物料输送过程中颗粒体系的行为特征进行较真实的模拟，对溜槽和导料中的粉粒体和空气的行为特征进行比较真实的模拟和再现。该套产品由多个可独立应用设备组成，主要有高效环保转运系统(含控速溜槽、密封导料槽、控流引擎槽、智能分流器、双密封自降尘系统、阻尼减压器、静电吸尘挡帘等)、高效环保卸料车、单体高效除尘等设施。', '将物料从卸料、转运到受料的整个过程控制在密封空间进行；实现根据物料特性和输送结构形式要求，通过仿真模拟，建立独有的输送结构模型，减少粉尘产生、降低除尘风量。', '资源高效利用', '智能化；减少粉尘产生', '河钢集团邯钢公司', null, null, null, '钢铁行业调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('ST004
', '中国', '钢铁', 'LT法转炉煤气净化与回收技术', '末端处理', '首先将转炉煤气经过废气冷却系统，然后进入蒸发冷却器，喷水蒸发使烟气得到冷却，并由于烟气在蒸发器中得到减速，使其粗颗粒的粉尘沉下来，此后将烟气导入设有四个电场的静电除尘器，在电场作用下，使得粉尘和雾状颗粒吸附在收尘极板上，这样得到净化。当符合煤气回收条件时，回收侧的阀门自动开启，高温净煤气进入煤气冷却器喷淋降温至约73℃，而后进入煤气储柜。经加压机加压后将高洁度的转炉煤气(含尘10mg/Nm3)提供给用户使用。', '转炉吹炼时，产生含有高浓度CO和烟尘的转炉煤气(烟气)。对其进行净化，达到回收利用高热值的转炉煤气的目的。', '大气污染防治', '减少颗粒污染；煤气循环利用', '宝山钢铁股份有限公司', null, null, null, '钢铁行业调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('ST005
', '中国', '钢铁', 'LT法转炉粉尘热压块技术', '末端处理', '粉尘在充气保护下，经输送和储存，将收集的粉尘按粗细粉尘以0.67:1的配比混合，加入间接加热的回转窑内进行氮气保护加热。当粉尘被加热至580℃时，即可输入辊式压块机，在高温、高压下压制成45×35×25mm成品块。约500℃的成品块经冷却输送链在机力抽风冷却下，成品块温度降至~80℃，装入成品仓内。定期用汽车运往炼钢厂作为矿石重新入炉冶炼。', '与LT法转炉煤气净化回收技术配套，回收含铁高的粉尘。', '资源高效利用', '铁循环利用', '宝山钢铁股份有限公司', null, null, null, '钢铁行业调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('ST006
', '中国', '钢铁', '烧结机逆流式活性炭脱硫脱硝脱二噁英一体化技术', '末端处理', '在吸附装置中把脱硫、脱硝两段任务分离，分两个步骤完成烟气净化过程。在第一个活性炭床层进行粉尘、二噁英、重金属、SO2、卤化物的脱除，烟气分离出来再进入下一个活性炭床层完成脱硝任务。为实现脱硫与脱硝分区目的，在脱硫与脱硝之间的有限空间内设置过渡区，过渡区采用活性炭排料漏斗组、配气格与布料管组集成布置的方式，实现了在脱硫脱硝过渡区有限空间内的集成布置，解决了脱硫区与脱硝区有效分离的难题', '烟气污染物实现超低排放；吸附装置作业效率高，保证烧结生产；资源回收利用，实现循环经济；该方案可以充分发挥两个工艺过程的协同优势，有利于提升污染物的脱除效率。', '大气污染防治', '减少硫污染；循环利用', '邯郸钢铁集团有限责任公司', null, null, null, '钢铁行业调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('ST007
', '中国', '钢铁', '焦炉烟气活性炭-烟气逆流集成净化技术', '末端处理', '处理过程在一个反应器内进行，能够一步达到脱硫脱硝的处理效果。其中活性炭是这一处理过程的关键，它既作为优良的吸附剂，又是催化剂与催化剂载体。脱硫是利用活性炭的吸附特性，脱硝是利用活性炭作催化剂，通过氨、NO/NO2发生催化还原反应除去。该技术在脱硫、脱硝的同时可对烟气中的汞、砷、氟化氢、氯化氢、二噁英等有害物质一并脱除，并将尘滞留在焦层中。', '降低了净化后的烟气中所含有害物质的含量，避免了烟气中不同污染物治理设施的串联建设，大大提高了设备的投资利用率。', '大气污染防治', '减少大气污染；提高设备利用率', '安阳钢铁集团有限责任公司', null, null, null, '钢铁行业调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('ST008
', '中国', '钢铁', '内置式直燃炉技术', '末端处理', '内置式直燃炉布置在烟气脱硝系统中，位于GGH的U形(或倒形)烟道中，一般情况下，位于喷氨格栅之后。内置式直燃炉由燃烧系统、烟气系统和控制系统三部分组成。内置式直燃炉将燃烧室布置在烟道中，同时采用烧结烟气进行助燃。', '目前，钢铁行业烧结机烟气脱硝的主流技术路线之一就是，中低温SCR催化剂+回转式GGH+加热系统，内置式直燃炉就属于这个技术路线中的加热系统。能够通过燃烧的方式减少烧结机烟气中各种可燃的污染物质，比如一氧化碳、甲烷等，有效的减少了各种污染物质的排放并用于加热烟气自身，变废为宝，在节约能源的同时，可以有效的减少烟气中部分可的有害物质的排放。', '大气污染防治', '减少大气污染；节约能源', '河北津西钢铁集团股份有限公司，河北唐银钢铁有限公司', null, null, null, '钢铁行业调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('ST009
', '中国', '钢铁', '焦炉烟气SCR中低温脱硝技术', '末端处理', '脱硫后烟气与喷氨段喷入的氨初步混合后通过烟气均布段进行充分混合，然后经管道送入低温 SCR 脱硝催化剂段，将烟气中 NOx 还原为 N2和 H2O。运行烟气温度200°C~ 280°C，入口 NOx 浓度 ≤1200mg/m3，出口 NOx 浓度≤130mg/m3;系统氨逃 逸≤3ppm， 阻 力 ≤1500Pa。', '排除了 SO2 对脱硝的影响，有利于减少脱硝催化剂填装量、延长催化剂寿命', '大气污染防治', '减少大气污染', '鞍钢股份有限公司', null, null, null, '钢铁行业调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('ST010
', '中国', '钢铁', '密相塔脱硫除尘协同SCR脱硝超低排放技术', '末端处理', '密相脱硫技术属于半干法烟气脱硫工艺，其是以钙基脱硫剂为主的增湿类烟气脱硫技术。含有较多活性CaO组分的细粉状循环灰脱硫剂在加湿混合器内加湿活化，再通过脱硫塔烟气入口处设置的搅拌装置强力破碎后进入脱硫塔。原烟气进入脱硫塔后，携带脱硫剂向上运动过程中，脱硫剂与烟气中的SO2进行反应，实现原烟气脱硫。SCR的全称为选择催化还原法，是利用液氨、氨水等作为还原剂，在一定的温度下通过催化剂的催化作用，还原剂NH3还原废气中的NOx，将NOx转化为无害的氮气和H2O。', 'SO2和NOx均易实现超低排放；半干法脱硫系统自带的布袋除尘系统，确保净烟气粉尘达到超低排放。', '大气污染防治', '减少大气污染', '首钢矿业公司，河北钢铁集团唐山炼铁厂', null, null, null, '钢铁行业调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('ST011
', '中国', '钢铁', '基于新型微晶材料的煤气源头污染物综合治理技术', '末端处理', '本技术的原理是采用新型纳米疏水微晶材料作为吸附材料，采用多塔变温吸附技术，在较低温度下同时选择性地吸附硫化氢、有机硫、氨气、苯、萘、焦油以及重质芳烃等，获得满足净化要求的焦炉煤气或高炉煤气。当吸附饱和后，利用少部分净化后煤气经过加热后对吸附塔进行解吸再生。每个吸附塔交替进行吸附和解吸，系统连续运行。', '工艺简洁、操作简单，运行费用低；可以有效脱除硫化氢、氯化物等，脱除精度高；可以脱除有机硫，是目前脱硫工艺中能有效脱除有机硫为数不多的技术之一；可以脱除苯、萘、氨、氰化氢、焦油等；吸附剂疏水，可减少煤气中水蒸汽的影响；微晶材料吸附剂耐高温，结构稳定，可反复再生，使用寿命长。', '大气污染防治', '减少大气污染', '中信特钢铜陵泰富特种材料有限公司，中信特钢湖北新冶钢有限公司，山钢集团莱芜钢铁有限公司，中新钢铁集团有限公司', null, null, null, '钢铁行业调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('ST012
', '中国', '钢铁', '转炉一次烟气超低排放技术', '末端处理', '干法除尘：调整了煤气冷却器的位置，并且开发了超净煤气冷却器，从而使系统达到超净排放指标。
半干法除尘：在传统湿法除尘基础上，将喷淋塔更换为蒸发冷却器，可将烟气中40％的灰粉将通过蒸发冷却器被分离，部分粗颗粒粉尘沉降至灰斗内并通过内置链式输灰机排出，后通过外部链式输灰机等装置送至粗灰仓；粗除尘后的烟气由管道先进入RSW环缝长颈可调喉口文氏管进一步精除尘：转炉烟气与喷入的水混合后高速通过环缝喉口，其流速最高可达150m/s，从而使烟气中的细颗粒灰尘被分离出来，除下的灰尘由浊环水带走，同时转炉烟气被进一步降温至65℃。
湿法除尘：新型的RSW环缝长颈可调喉口文氏管可有效使烟气中的灰尘被分离出来，保证经过湿法除尘后含尘量小于50mg/Nm3，再经过一级湿式电除尘进行精细除尘，最终保证排放烟气含尘量<10mg/Nm3。', '一次烟气排放含尘浓度均小于10mg/Nm3，远低于国家排放标准，更是达到了超净排放标准。减少对于大气的污染，除尘效果达到国内领先水平。', '大气污染防治', '减少大气污染', '河北敬业钢铁', null, null, null, '钢铁行业调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('ST013
', '中国', '钢铁', '钢铁窑炉烟气颗粒物预荷电袋式除尘技术', '末端处理', '钢铁窑炉高温烟气先经冷却器降温至 60℃～ 200℃后，经粉尘预荷电装置荷电，再经气流分 布装置进入袋滤器，细颗粒物被超细面层精细滤料截留去除。颗粒物排放浓度可＜ 10mg/m3。 运 行 阻 力700Pa～1000Pa。', '采用复合式预荷电+袋滤器结构可显著降低设备运行阻力。', '大气污染防治', '减少大气污染；保护设备', '中国钢铁集团', null, null, null, '钢铁行业调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('ST014
', '中国', '钢铁', '静电滤槽电除尘技术', '末端处理', '在电除尘器收尘板末端设置采用冷拔锰镍合金丝织成的微孔网状结构静电滤槽收尘装置，可有效捕集振打清灰产生的二次扬尘。颗粒物排放浓度可＜5mg/m3。', '增加电除尘器有效收尘面积，有效控制振打清灰产生的二次扬尘。', '大气污染防治', '减少大气污染', '广东省韶关钢铁集团有限公司', null, null, null, '钢铁行业调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('ST015
', '中国', '钢铁', '转炉煤气干法电除尘及煤气回收成套技术', '末端处理', '
转炉出炉煤气经冷却降温并调质后，采用圆筒形防爆电除尘器除尘。煤气符合回收条件时， 经冷却器直接喷淋冷却至 70℃以下进入气柜； 不符合回收条件时，通过烟囱点火放散。蒸发冷却器内约 30%的粗粉尘沉降到底部，粗灰返回转炉循环利用。转炉炉口处烟气含尘量约 200g/m³，经除尘后颗粒 物 排 放 浓 度 可 ＜ 10mg/m³。氧气（O2）浓度
＜1%时，煤气完全回收利用。', '实现了转炉煤气的干法深度净化、粉尘循环利用、煤气高效回收，及全系统的自动化、智能化保证了系统的运行安全。', '大气污染防治', '减少大气污染；粉尘循环利用', '柳州钢铁股份有限公司', null, null, null, '钢铁行业调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('ST016
', '中国', '钢铁', '转炉煤气湿法洗涤与湿式电除尘复合除尘技术', '末端处理', '转炉一次烟气经湿法洗涤除尘后进入湿式电除尘器除尘，形成湿法除尘与双电场湿式电除尘器串联形式的复合除尘系统。湿式电除尘极板上收集的粉尘经水冲洗后送至水处理厂处理。出口颗粒物浓度可＜20mg/m3。', '湿法洗涤结合湿式电除尘，大幅提高转炉烟气除尘效率。', '大气污染防治', '减少大气污染；粉尘循环利用', '柳州钢铁股份有限公司', null, null, null, '钢铁行业调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('ST017
', '中国', '钢铁', '炭基催化剂多污染物协同脱除及资源化利用技术', '末端处理', '利用炭基催化剂的选择性催化还原性能，喷入氨将氮氧化物（NOx）还原为氮气（N2）；利用炭基催化剂的吸附性能，吸附烟气中二氧化硫（SO2），吸附饱和后催化剂可再生循环使用。解吸出富含 SO2 的气体用于生产浓硫酸、硫酸铵、液体 SO2 等产品。入口SO2 浓度约 500mg/m3 ~ 3000mg/m3 、 NOx 浓 度 约 200mg/m3 ~ 650mg/m3 时，出口 SO2 浓 度 ≤10mg/m3 、 NOx 浓 度 ≤50mg/m3。反应器入口温 度 120°C~150°C。 ', '采用两级移动床工艺，实现多污染物协同脱除。', '大气污染防治', '减少大气污染', '山东钢铁股份有限公司', null, null, null, '钢铁行业调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('ST018
', '中国', '钢铁', '多孔碳低温催化氧化烟气脱硫技术', '末端处理', '烟气经预处理系统除尘、调质，当温度、颗粒物浓度、水分、氧浓度等指标满足要求后进入装填有多孔碳催化剂的脱硫塔。烟气经过催化剂床层时，SO2、O2、水（H2O）被催化剂捕捉并催化氧化生成硫酸，脱硫塔出口烟气达标排放饱和催化剂可水洗再生，再生淋洗液可用于制备硫酸铵。入 口 烟 气 中 SO2 浓 度 ≤8000mg/m3 时，出口 SO2 浓度≤50mg/m3，出口硫酸 雾浓度≤5mg/m3。脱硫塔 内反应温度 50°C~ 200°C ， 空 塔 气 速 ≤0.5m/s。 ', '脱硫效率高，可适应烟气量及SO2 浓度波动大的情况。', '大气污染防治', '减少大气污染；粉尘循环利用', null, null, null, null, '钢铁行业调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('ST019
', '中国', '钢铁', '电炉烟气多重捕集除尘与余热回收技术', '末端处理', '电炉炉内排烟经余热锅炉回收余热降温后经袋式除尘器除尘达标排放；采用“半密闭导流烟罩+屋顶贮留集尘罩+铁水溜槽排烟罩”相结合的方式全过程捕集电炉在加废钢、兑铁水、熔炼、出钢等过程中产生的排烟，烟气在半密闭导流烟罩及铁水溜槽排烟罩导流作用下流经屋顶贮留集尘罩，再经袋式除尘器除尘达标排放采用炉内一次排烟和炉外移动半密闭罩二次排烟相结合的方式捕集钢包电弧炉烟气，经袋式除尘器除尘达标排放。电炉炉内排烟除尘系统 入口颗粒物平均浓度10g/m3~13g/m3、钢包电 弧炉除尘系统入口颗粒 物平均浓度 16g/m3；除尘 后出口颗粒物平均浓度 可<10mg/m3。', '

余热锅炉回收电炉炉内排烟余热；采用组合式集气装置有效捕集烟气，除尘效率高。', '大气污染防治', '减少大气污染', '山东钢铁股份有限公司莱芜分公司', null, null, null, '钢铁行业调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('ST020
', '中国', '钢铁', '焦化烟气旋转喷雾法脱硫+SCR 脱硝技术', '末端处理', '采用高速旋转雾化器将碱性浆液雾化成细小雾滴与烟气接触反应脱硫，雾滴被烟气热量干燥为固体颗粒物后经袋式除尘器去除；脱硫除尘后烟气经热风炉升温后进入 SCR 脱硝系统与喷入的氨气混合，在导流板作用下均匀流向催化剂床层，将其中 NOX 还原脱除后达标排放。出口烟气中颗粒物浓度 可<10mg/m3，SO2 浓度可 <30mg/m3，NOx 浓度可< 130mg/m3。', '排除了 SO2 对脱硝的影响，有利于减少脱硝催化剂填装量、延长催化剂寿命', '大气污染防治', '减少大气污染', '邯钢集团邯宝钢铁有限公司焦化厂', null, null, null, '钢铁行业调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE001', '中国', '纺织', '静电处理技术', '末端控制', '该技术适用于纺织热定型工序油烟废气处理。静电式除尘器的净化效率高，集油极上收集的油可收集后作为燃烧油使用。热定型机排放油烟宜采用三、四电场静电除尘器。对于温度达180℃~230℃的油烟需经冷却处理后，再进入静电除尘器。', '静电处理技术利用静电场使油烟颗粒带电，在电场力作用下向收尘极板移动而从气流中分离处理，从而达到净化烟气的目的。', '大气污染防治', '油烟废气/资源再利用', null, null, null, null, '纺织印染行业清洁生产技术调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE002', '中国', '纺织', '水喷淋+静电处理技术', '末端控制', '该技术适用于纺织定型机工序废气处理。水喷淋技术与静电处理技术的结合应用，即先进行水喷淋预处理再进行高压静电净化处理，一次性解决了静电处理的相关问题，又充分利用了水喷淋式处理工艺的优势。', '具备了废气降温、除毛屑、除蜡、除油、防火、易维护清理等功能。', '大气污染防治', '定型工序废气/资源再利用', null, null, null, null, '纺织印染行业清洁生产技术调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE003', '中国', '纺织', '小浴比前处理及染色技术', '生产过程', '低浴比染色技术通常是指使用气流染色机或低浴比溢流染色机进行染色，染液和织物可快速循环、升温和翻动，浴比可低至1：5（甚至1：3）。', '小浴比染色能够减少能源和水的消耗；降低盐和碱剂的用量；减少染料用量；有利于改善染料重现性和匀染性。', '资源高效利用', '小浴比/节能减排/节水降耗', null, null, null, null, '纺织印染行业清洁生产技术调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE004', '中国', '纺织', '丝光碱液加热浓缩回收技术', '生产过程', '通过加装扩容蒸发器对丝光废水中的液碱进行浓缩蒸发后回用。', '达到生产要求浓度的碱液进行回收重复应用于生产，从而减少液碱的流失并减少废水量。', '资源高效利用', '丝光废水/碱液回收', null, null, null, null, '纺织印染行业清洁生产技术调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE005', '中国', '纺织', '丝光碱液膜回收技术', '生产过程', '利用耐碱超滤膜对淡碱液进行过滤，去除杂质后再补充少量浓碱和纯水进行回用。', '达到生产要求浓度的碱液进行回收重复应用于生产，从而减少液碱的流失并减少废水量。', '资源高效利用', '丝光废水/碱液回收/耐碱超滤膜', null, null, null, null, '纺织印染行业清洁生产技术调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE006', '中国', '纺织', '氧漂水回用', '生产过程', '氧漂废水污染较轻，其中含有残余的漂白剂、少量醋酸、草酸、硫代硫酸钠等，且因杂质较低，而退煮工序使用的助剂中含有烧碱和双氧水，而这些试剂在布上的残留，不会对处理效果产生影响，因此氧漂废水可以回用于退煮工序充当水洗用水。', '可实现在节水的同时减少废水的排放量。', '资源高效利用', '氧漂水回用/节水减排', null, null, null, null, '纺织印染行业清洁生产技术调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE007', '中国', '纺织', '碱性印染废水脱硫技术', '生产过程', '利用碱性印染废水作为脱硫除尘液，中和酸性烟气，SO2去除率达到了75％，具有明显的环境和经济效益，所以热电厂尾气处理也可以作为用水节点，接受碱性废水。', '碱性印染废水可以有效中和印染集中区外的热电厂锅炉排放的大量酸性烟气，实现较好的脱硫效果的同时减少新鲜水的消耗。', '大气污染防治/资源高效利用', '烟气脱硫/碱性印染废水', null, null, null, null, '纺织印染行业清洁生产技术调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE008', '中国', '纺织', '生物酶应用技术', '生产过程', '生物酶是生物细胞产生的一种无毒、对环境友好的生物催化剂，是具有极强催化效率的特殊蛋白质，主要有淀粉酶、蛋白酶、果胶酶和过氧化氢酶等。', '生物酶在棉印染企业里主要应用于退浆、精炼 、过氧化氢漂白和后整理中，具有极强催化效率且环境友好。', '生物多样性保护', '生物酶催化/环境友好', null, null, null, null, '纺织印染行业清洁生产技术调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE009', '中国', '纺织', '冷轧堆前处理技术', '生产过程', '将传统的退浆、煮练、漂白三部前处理合为二步或一步工艺，其质量达到3道工序的水平。使用该工艺后平均生产用水量为24L/h，消耗蒸汽量为2.25t/h，比传统工艺用水量节省22.6t/h，蒸汽消耗量减少1.52 t/h。', '节约大量的能源和劳动力，减少废水的排放，比传统工艺节约用汽80%，节水75%，节约化工原料20%。', '能源节约及清洁化/水污染防治', '冷轧堆/节能降耗', '浙江美欣达印染集团股份有限公司、上海东美化工有限公司、北京第三印染厂、江苏悦达纺织集团有限公司、江苏常熟市精诚化工有限公司', '月产100万米各色机织物，采用ECONTROL染色机。投资金额为100万元。建设期为0.5年。年节约水资源费33万元，年节约蒸汽费145万元，年节约排污费16万元，年降低生产成本218万元，项目投资回收期为6年。', null, null, '纺织印染行业清洁生产技术调研报告、印染行业水污染治理成套集成技术', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE010', '中国', '纺织', '活性染料冷轧堆染色技术', '生产过程', '主要是对染料和纤维的吸附、扩散和固色反应是在堆置中完成的，通常都在室温下进行的，较轧染省去了中间烘燥和汽蒸或焙烘两道工序，较大的节约了能耗，同时由于该工艺中染料水解少，固色率较高，在冷染后的皂洗过程中，也将节省大量的生产用水和蒸汽。该技术工艺流程短、设备简单、成本低，特别适合小批量、多品种生产，是印染企业提高产品档次、降低成本、改善环境的重要途径之一。', '染色得色率高、能耗低、准备周期短、重现性好、污染少，能节省大量的生产用水和蒸汽。与连续轧染工艺相比，冷轧堆染 色工艺在蒸汽与电的消耗方面降低30%~40%，染料固着率可提高20%~25%， 污水处理降耗10%。除此之外，冷轧堆染色工艺的条件相对连续轧染工艺也较温和，织物在染色过程中受到较小的张力，所以织物的染色效果和手感都有较大的提高。', '能源节约及清洁化/水污染防治', '冷轧堆/节能降耗/降低成本', '浙江美欣达印染集团股份有限公司', null, null, '由于冷轧堆染色是在室温下长时间缓慢固色，避免了泳移现象的发生，对于松紧厚薄织物，染料的渗透性都极佳，产品的色光更纯正;冷轧堆染色在室温下进行，没有烘燥和汽蒸工序，节省能源;冷轧堆染色具有较高的重现性和可靠性;冷轧堆染色设备投资少，占地面积小;冷轧堆染色采用开幅处理方式进行，织物没有折痕;冷轧堆染色处理过程中，织物受到的张力、摩擦力小，避免了织物的起毛问题，织物的表观效果和手感均有较大提高。', '纺织印染行业清洁生产技术调研报告、印染行业水污染治理成套集成技术', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE011', '中国', '纺织', '涂料染色技术', '生产过程', '涂料染色是一种新型的染色技术，它用涂料代替染料依靠螯合剂及交联剂作用固着在织物上。不同于染料，涂料是不溶性的有色物质，由颜料、分散剂和润湿剂等组成，不能进入纤维内部，与纤维没有亲和力，不能按常规染料的染色工艺条件进行染色，只能借助黏合剂、交联剂的作用固着在纤维表面，即涂料染色是表面固着的过程。涂料染色是将涂料、黏合剂、其他助剂等混合制成色浆，根据产品质量、生产量等因素合理选择染色加工方式，浸渍或浸轧，织物均匀带液后，经预烘、焙烘，使之固着在织物表面。', '涂料染色与传统染色工艺相比加工工艺简单、加工流程短、色谱广、易于拼色、设备简单、成本低、生产效率高、节能节水、污水排放少。', '能源节约及清洁化', '涂料染色/简化工艺/环境友好', null, null, null, '涂料染色和染料染色相比，具有如下创新:1.涂料对任何纤维都没有亲和力，不存在上染过程，只存在黏着或着色过程。因此，它对各种纤维不存在选择性，适用于各种纤维，包括染料无法染色的玻璃纤维、金属纤维等，且特别适用于多组分纤维纺织品染色。2. 由于没有亲和力，使它在拼色时不存在竞染和配伍性问题，易于拼色，重现性好，便于从小样放大样和颜色控制。3.可以选用不同发色体系的有色物质，染色包括同时选用有机和无机有色物质拼用，不但色谱齐全，且可以获得染料染色无法得到的颜色或效果，如金银色、珠光和闪光色等特殊染色效果;也容易得到高耐光、耐气候和耐化学品作用的品种。4.加工工艺简单，因为只对纺织品发生着色或黏着过程。最简单的工艺只包括染色和烘干两步，加工流程短，设备简单，不仅生产效率高，更重要的是节能节水，污水排放少，因此大大降低了成本。', '纺织印染行业清洁生产技术调研报告、印染行业水污染治理成套集成技术', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE012', '中国', '纺织', '喷墨印花技术', '生产过程', '喷墨印花技术是一种全新的印花方式 ，它摒弃了传统印花需要制版的复杂环节，直接在织物上喷印，提高了印花的精度，实现了小批量、多品种、多花色印花，而且解决了传统印花占地面积大、污染严重等问题，因此具有广阔的发展前景。', '较传统印花技术占地面积小、污染少。', '水污染防治', '喷墨印花/环境友好', null, null, null, null, '纺织印染行业清洁生产技术调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE013', '中国', '纺织', '高效水洗技术', '生产过程', '在印染加工中，水洗工序产生大量的废水，所以应用高效水洗设备和设计合理的水洗工艺，在生产中积极推行采用低水位、逆流水洗技术和设备，应用固色剂或交联剂提高固色效果，从而减轻水洗负担，降低用水量和洗液颜色深度。', '可以有效降低用水量和洗液颜色深度。', '水污染防治', '逆流水洗/节能减排', null, null, null, null, '纺织印染行业清洁生产技术调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE014', '中国', '纺织', '气流染色技术', '生产过程', '染液以雾状喷向织物，使得染液与织物在很短的时间内充分接触，以达到匀染的目的，其最大特点是浴比低 (浴比可至1：3)。', '气流染色机的特殊结构及运行方式弥你补了溢流染色机的诸多不足，具备了溢流染色机无法比拟的技术、经济优势。统计数据表明:使用气流染色机后，缩短染色加工时间20%，减少耗水量45%，减少耗蒸汽量30%，减少耗助剂量30%，减少排污量40%，提高了净洗效率和匀染效果，提高了产品质量。', '能源节约及清洁化', '节能减排/间歇式绳状染色', '金纺集团公司、邵阳纺织机械有限责任公司', null, null, '气流染色技术相比传统染色技术具有水消耗低、高效节能、节约染化料、减少污染、节省时间以及一次成功率高等优点，同时为织物间歇式绳状染色提供了新的加工方法，极大地促进了印染行业向高效、节能和环保的方向发展。', '纺织印染行业清洁生产技术调研报告、印染行业水污染治理成套集成技术', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE015', '中国', '纺织', '变频调速技术', '生产过程', '变频调速可根据企业生产实际情况，调节电机交流电频率，从而调节电机转速，达到降低用电的目的。在棉印染企业中的染色机、烘干机、定型机 、罗茨风机、空压机、水泵等均可应用，投资回收期短，节电效果明显。', '有较好的节电效果', '资源高效利用', '变频调速/高效节电', null, null, null, null, '纺织印染行业清洁生产技术调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE016', '中国', '纺织', '工业锅炉节能改造', '生产过程', '常见工业锅炉节能改造主要有锅炉烟气余热利用和安装分层燃烧装置。锅炉烟气余热利用主要有安装余热蒸汽发生器或安装空气预热器，降低排烟温度。企业锅炉安装了分层燃烧装置，通过对燃煤进行粒度分选，使落到炉排上的燃煤按粒度大小分层排列，即大块煤在下面，中块煤在中间，细煤在煤层表面，有效避免炉排上出现的火口和燃烧不均匀现象。', '改善煤的着火条件，提高火床的热强度和燃烧速度，有利于煤的充分燃烧，提高锅炉热效率。', '资源高效利用', '锅炉烟气/余热利用/分层燃烧', null, null, null, null, '纺织印染行业清洁生产技术调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE017', '中国', '纺织', '印染废水余热利用', '生产过程', '印染企业生产过程中需消耗大量热能，同时排出大量高温废水，废水平均温度达到60~80 ℃，废水仍具有大量的潜热，通过热交换可回收利用废水余热。印染废水余热利用有两种方式：单体式和组合式。单体式主要用于连续排水的单台设备，如退煮漂联合机等。组合式可用于车间污水集中热回收回用。', '印染废水余热利用可明显节约蒸汽、电消耗，经济效益比较显著，尤其当排放的废水温度较高时。', '资源高效利用/能源节约及清洁化', '节能降耗/余热利用/高温废水', null, null, null, null, '纺织印染行业清洁生产技术调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE018', '中国', '纺织', '集中退浆和连续式平幅退浆', '生产过程', '将退浆工序从染色机中分离出来，对残液连续回用。', '可以减少退浆残液COD排放量的60%，节水的同时减少液碱消耗。', '资源高效利用/水污染防治', '退浆残液/液碱回用', '江苏盛虹印染有限公司、江苏吴江二练亚氏印染有限责任公司', null, null, null, '纺织印染行业清洁生产技术调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE019', '中国', '纺织', '短流程湿蒸染色技术', '生产过程', '该工艺是利用安装在反应蒸箱内人口处的远红外辐射器，将经过染色液浸渍轧吸的湿织物预热，使织物迅速升温，经过反应箱内少量蒸汽和干热空气的混合气体继续受热，2~3min固色，活性染料即固着于纤维，它的给色得以提高，并具有充分渗透、色泽均匀的优点。除一般织物外，此工艺特别适用于具有转移性的织物，如丝绒、灯芯绒、毛圈类织物。', '高得色率使染料用量降低10%-15%，高固色率和较低的水解作用使其在水洗过程中的用水量比传统工艺减少20%，年节省用水16000 t。', '资源高效利用', '湿蒸染色/高得色率/高效节水', '浙江美欣达印染集团股份有限公司', null, null, null, '纺织印染行业清洁生产技术调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE020', '中国', '纺织', '高效节能前处理技术', '生产过程', '对生产用水、汽、液进行全自动控制，蒸洗箱采用逐格蛇行回流，均匀轧液、轧水，煮炼、漂白、丝光各段废水均利用换热器进行热回收利用', '与传统工艺生产中退煮漂、丝光工艺比较，该设备节水可达40%，每年可节水近14.1万t。', '资源高效利用', '余热利用/智能化/高效节水', '浙江美欣达印染集团股份有限公司', null, null, null, '纺织印染行业清洁生产技术调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE021', '中国', '纺织', '无水液氨丝光技术', '生产过程', '无水液氨丝光工艺是在一个密闭的系统中进行的，从而防止了氨的泄漏。该工艺是用液氨作为丝光液，含有织物丝光、除氨、氨回收和循环、冷却系统和控制系统等。与烧碱相比较，氨更容易渗透到织物内部，与棉纤维作用，使织物在液氨作用下产生了轻微的膨胀，从而使织物表面产生绸缎的效果。织物在经受由磨损和多次水洗所带来的应力时，具有更好手感和柔软性。展现了更强的塑性和延展性，从而使服装的寿命和“新的”外观得以延长和保持。', '大大地减少了水的消耗和废水的产生。', '水污染防治', '液氨丝光/节水减排', '开平奔达纺织有限公司', null, null, null, '纺织印染行业清洁生产技术调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE022', '中国', '纺织', '活性染料染色残液盐回用系统', '生产过程', '活性染料染色残液回用的基本原理是将棉染过程中含盐最高的染色残液单独收集，采用萃取分离技术将高盐高色度染色残液中的染料萃取分离出来，再将浓盐液回用于染色过程中。染色残液的处理过程中形成了水+盐（水相）和萃取剂（油相）两个体系的闭环循环，在萃取装置中相互作用，连续地将染色残浴中的水解染料提取出来，高盐浓液则循环使用。', '染色废水中的盐减排率大于70%，盐回用率可达80%以上，进入污水厂的污水含盐量显著降低，经常规生化处理就可达标排放。', '资源高效利用', '活性染料/盐液回用', null, '以棉染日产量20吨的染色车间为例，建立相应的染色残液盐回用系统的处理容量为100吨/日，处理染色残液的流量为5吨/小时。新建车间染色残液盐回用系统，需设备投资￥380万元（RMB），该盐回用系统的使用年限为10年。年运行维护费用:156万元（其中：每天处理染色残液100吨，需萃取费用2570元/天；按每班1人，三班倒需3人，再加领班1人，共需4人，人工费用为4×5000 / 30 = 667元/天，设备折旧按10年约1041元/天。）', '需要保持系统设备在10℃以上的运行温度，环境的其它因素无特别要求。整个系统自动化控制，自主运行，除最后的调盐过程外，无需人为操作干预。', '独创的活性染料染色残液盐回用系统和相应技术能够使生产企业用可承受的生产成本，解决棉染废水高盐排放对环境造成严重盐污染的难题，这是困扰印染行业几十年的世界难题。该技术的最大特点是在不改变原有染色生产要素，包括染料和设备设施，生产过程，工艺处方，和生产经验等，仅在车间增加一套盐回收系统，在源头上截留并针对小容量高盐度的染色残液进行有效处理，因此比其他任何一种印染废水除盐或无盐染色的方法都经济易行。', '纺织印染行业清洁生产技术调研报告', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE023', '中国', '纺织', '复合生物酶清洁印染前处理技术', '生产过程', '利用效率高、功能强、条件温和、环境友好的生物酶及复合生物酶在棉针织物印染过程中去除棉纤维上的杂质，或者完成其他重要加工过程的工艺。复合精炼酶wck-3主要用于棉纱和棉针织物染整加工中的精炼过程，复合除氧抛光酶wck-d主要用于练漂后去除织物上的残留H2O2，以利于后续加工和整理过程去除纤维表面的毛羽而实现织物表面光洁。', '在去除果胶物质的同时，又能与其他酶产生协同效应随即去除蜡状物和其他非纤维杂质，从而实现理想的精炼效果。', '生物多样性保护', '复合生物酶/染整精炼/环境友好', '江苏坤风纺织品有限公司', null, '实际产品设计定型，通过功能、性能测试；可进行产品小批量生产', '拥有独立自主知识产权、自主研发的复合生物酶wck-3和wck-d。', '印染行业水污染治理成套集成技术', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE024', '中国', '纺织', '无水染色技术', '生产过程', '无水染色是利用超临界CO2流体作为介质进行染色，该技术无污染、零排放，实现了染色过程的清洁化生产。', '可以彻底实现绿色、环保、清洁化生产。', '能源节约及清洁化', '超临界CO2流体/零排放', null, null, null, '开发SC-CO2流体染色专用商品化染料体系。与传统染色技术相比，SC-CO2流体染色技术中染料及其CO2介质的扩散性能好，扩散系数大，远高于传统水浴中的情况，可以节约能源和加工时间，而且染浴中一般不添加其他助剂，有利于染色产品的色泽鲜艳度和牢度的提高，以及保护纤维/织物的品质，同时无染色废水和其他废弃物产生。与水介质染色过程相比， SC-COz流体染色全过程无水，CO2无毒、不易燃烧、价格低廉，染料和COz可循环使用，“零排放”无污染，并具有上染速度快、上染率高的优势，可实现清洁、绿色、环保化加工。', '印染行业水污染治理成套集成技术', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE025', '中国', '纺织', '精炼酶一步一浴法前处理技术', '生产过程', '采用高效精练酶一步一浴法前处理工艺技术集精练、稳定、渗透、乳化、螯合、分散于一体，无需加入双氧水稳定剂、碱等，确保前处理的稳定性和一致性，适用于棉及其混纺织物的前处理过程。可以有效去除织物上的蜡类、浆料等疏水物质，使织物得到最佳的吸水性和白度。采用新工艺后，其工艺流程相当于传统工艺的1/2，无碱，综合能耗降低近50%，前处理污水排放COD值降低约50%，在生产综合成本降低的同时实现了节能减排。', '可以有效缩短前处理加工周期，克服了原工艺消耗高、效率低的缺点，既节约了污水处理费用又减轻了污水处理压力，工艺流程短，污染物排放少，综合成本低，实现节能环保、绿色加工。', '资源高效利用', '高效精炼酶/一步一浴法/', '锦州宏丰印染有限公司', null, null, '与传统工艺比较，用高效精练酶处理的织物手感较好，白度较高，克重损失小，断裂强力较大。毛细效应远远高于传统工艺。用高效精练酶前处理的织物染色和印花，其耐洗色牢度、耐摩擦色牢度及耐热压色牢度等指标高于传统的工艺。用高效精练酶技术处理所得废水的色度、pH值、悬浮物含量、COD、BOD 和总残渣量均低于传统工艺，这就确保了高效精练酶一步一浴法技术实现清洁生产的可能性。', '印染行业水污染治理成套集成技术', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE026', '中国', '纺织', '双氧水漂白前处理技术', '生产过程', '双氧水漂白简称氧漂。织物用双氧水漂白的工艺适用于各类纤维及其制品。氧漂后的织物白度和稳定性较好，能去除纤维素纤维中的大部分杂质和棉籽壳，适合练漂连续化生产。设备要求较高，生产成本比用次氯酸钠要高，但漂白效果较好，常用于较高档棉及含棉混纺织物的漂白。以“轧漂”和冷轧堆工艺为主，棉针织物可“浸漂”，可同时煮练。如织物上黏附铁、铜等重金属成分，则会催化双氧水的剧烈分解，使漂白织物产生破洞。双氧水对棉纺织物的漂白是在碱性介质中加热进行的，兼有一定的煮练作用，对煮练的要求较低。', '用双氧水漂白棉布具有许多优点，例如产品的白度较高并较为稳定，漂白的织物手感好，同时对退浆和煮练要求较低，便于漂练过程的连续化。此外，采用双氧水漂白无有害气体产生，可改善劳动条件。', '大气污染防治', null, null, null, null, null, '印染行业水污染治理成套集成技术', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE027', '中国', '纺织', '气液染色技术', '生产过程', '气液染色技术是改进传统溢流染色技术而得到的一种全新的间歇式绳状染色技术。气液染色机采用独立的气流循环和液流循环的设计理念，对加工织物产生不同作用，利于染料均匀上染织物。', '相较于传统的溢流染色工艺，气液染色工艺技术具有低浴比、高效率，能源、物料、时间消耗少的特点，一定程度上解决了染色废水及污染物高排放的问题。与传统气流雾化染色机相比，可节省用电60%以上，节省用水20%，节省蒸汽30%，且缩短工艺时间30%。解决了针织物幅宽变化、分散染料染深色浅、敏感色难控制，以及水洗不充分等问题。', '资源高效利用', '小浴比/节能减排', null, null, null, '减少气流循环无效损失，风机功率下降50%，染液与气流的循环采用了全新的设计结构，在充分提高气流有效利用率的同时，大幅度降低了风机消耗功率，将循环风机的额定功率降低到原来的 50%以下，解决了当前气流染色机电耗大的问题，在1:4以下低浴比染色时更加节水、省汽，特别是节电。', '印染行业水污染治理成套集成技术', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE028', '中国', '纺织', '小浴比匀流染色技术', '生产过程', '匀流染色机为超低浴比溢流染色机，不使用气流输送织物，整个绳状漂染处理过程包括前处理、染色及后续水洗工艺均由浴液完成。匀流染色机使溢流染色机能提供与气流染色机相同的小浴比，由于水洗效率更高，使得整个处理过程的总耗水量小于气流染色机。', '该技术的使用既达到了节能减排的目的，又成功避免了使用气流染色机对织物造成的张力大、布面起毛严重以及高耗电、高噪声和处理织物品种有限等实际生产问题。小浴比染色可减少能源和水的消耗，还可加快上染速率，在一定程度上提高固色率， 故可以减少盐用量，进行低盐染色，且能提高染料和碱剂的利用率，有利于改善善染色重现性、匀染性，提高净洗效率，确保产品品质。', '资源高效利用', '小浴比/节能减排', null, null, null, null, '印染行业水污染治理成套集成技术', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE029', '中国', '纺织', '泡沫染色技术', '生产过程', '泡沫染色技术是以空气代替部分水，使染液以泡沫的形式上染织物的一种节能节水的环保染色过程。泡沫染色以泡沫为传递介质，浴比小，可减少染料、助剂用量和用水量。', '以棉织物染色加工为例，相比传统浸轧方式，棉织物带液率下降 40%以上，可降低能耗 50%，节水40%，节约化学品20%，提高生产效率 50%，还能避免泳移、染色不匀。', '资源高效利用', '节能降耗/小浴比', null, null, null, null, '印染行业水污染治理成套集成技术', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE030', '中国', '纺织', '转移印花技术', '生产过程', '把颜料或染料印刷在纸、橡胶或其他载体上，然后移印到待印的商品上称转移印花，但狭义而言转移印花系指以纺织品作载体的移印技术。转移印花主要应用在聚酯纤维品上，随着转移印刷术的提高，在尼龙、丙烯腈、棉、麻、毛织品上也得到普遍应用。转移印花分湿法、干法、蒸汽法、真空法、热法等多种形式。转移印花法能够精确再现图案，便于机械化生产，且工艺简单，尤其是印花后处理工艺比传统印染简单而印花手感与印染相同，因而大有逐步替代老法印花之势。', '能够明显提高染料对棉纤维的转移率，且不需要对棉纤维进行预处理，不产生污水。', null, null, '苏州市彩旺纺织整理有限公司、无锡市东北塘宏良染色厂', null, null, null, '印染行业水污染治理成套集成技术', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE031', '中国', '纺织', '数码印花技术', '生产过程', '数码印花技术是随着计算机技术不断发展而逐渐形成的一种集机械、计算机电子信息技术为一体的高新技术产品。数码印花的生产过程通过各种数字化手段，例如将扫描、数字相片、图像或计算机制作处理的各种数字化图案输入计算机，再通过电脑分色印花系统处理后，由专用的RIP 软件通过对其喷印系统将各种专用染料(活性、分散、酸性为主的涂料)直接喷印到各种织物或其他介质上，再经过处理加工后在各种纺织面料上获得所需的高精度的印花产品。', '与传统印染工艺相比，数码印花的生产过程使原有的工艺路线大大缩短，接单速度快，打样成本大大降低。由于数码印花的生产工艺流程摆脱了传统印花在生产过程中分色描稿、制片、制网过程，从而大大缩短了生产时间。接受花样的方式，可以通过光盘、E-mail 等各种先进手段，一般打样时间不超过1个工作日，而传统打样的周期一般在1周左右。另外，由于工艺的简化，使打样成本也大大降低。', '资源高效利用', '数字化/', '上海八达纺织印染服装有限公司', null, null, '数码喷墨印花没有颜色限制、没有重复单元大小限制、制样时间显著缩短、几分钟内就能生成多色配色、筛网成本大大减少、企业生产效率大大提高、能够减少修补节约织物、减少库存和劳动力成本。', '印染行业水污染治理成套集成技术', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE032', '中国', '纺织', '泡沫整理技术', '生产过程', '泡沫整理是一种将化学品浆料(一般为水溶性)与表面活性剂共混，通过充入大量空气后，采用机械发泡的方式生成大量泡沫，并将泡沫施加于纺织品表面，提高纺织品附加值的一种纺织后整理方式。泡沫整理是将整理剂或涂层剂、发泡剂混合后发泡并施加到织物上，可单面处理也可双面处理，与常规轧烘焙整理相比，可大量节省化学品用量，还减少整理剂之间的相互影响，可用于各类功能面料的产品开发。', '由于泡沫是采用空气代替大部分的水，在节能减排上起到了很大作用，并且在很大程度上可以提高产品的品质。是一种环境友好型技术，在降低能耗、提高企业生产效率及产品质量方面具有很好的效果。', '资源高效利用', '泡沫整理/节能减排/环境友好', null, null, null, '泡沫整理技术系统可以控制工作液在被加工织物中的渗透距离，既可以使工作液只停留在织物表面，也可以使工作液浸透织物。因此可以对织物两面进行不同的加工，这是浸轧法根本无法实现的。并且与涂层整理相比，泡沫整理加工时工作液中通常只需要增添起泡剂和稳泡剂，与浸轧法的工作液并没有大的差别，所以施加到织物上，破泡后可以迅速渗透到纤维内部，因此加工后的织物耐洗性和手感都比较好。', '印染行业水污染治理成套集成技术', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE033', '中国', '纺织', '液氨整理技术', '生产过程', '液氨加工工艺是从纱线整理入手，以替代纱线丝光处理技术。由于液氨对纱线有着极强的渗透性，残留在纱线上的氨液比碱液更易于去除，而且比碱液丝光效果更好，因而引起重视。', '液氨整理可以提高纯棉等天然纤维及其混纺产品的穿着服用性能，其结合树脂整理新技术可进一步提高免烫效果。', null, null, null, null, null, null, '印染行业水污染治理成套集成技术', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE034', '中国', '纺织', '水性涂层整理技术', '生产过程', '涂层整理就是将一层或者多层能形成薄膜的高分子化合物均匀地涂覆在纺织物的表面，以实现织物的两面有不同功能的织物表面整理技术。涂层既能改变织物的外观风格，也能增加织物的功能性，使织物的附加值得到提高。然而大部分涂料都需要有机溶剂作为分散政介质给后续废水处理带来很大负荷。由于近年来有机溶剂价格高涨及环保部门对有机溶剂的使用和废物排放的严格限制，水性聚氨酯取代溶剂型聚氨酯成为一个重要的发展方向。', '可以在改变织物的外观风格，增加织物的功能性，使织物的附加值得到提高的同时，降低废水处理负荷。', '水污染防治', '水性涂料/涂层整理', null, null, null, '水性涂料是以水为分散介质代替有机溶剂，具有无污染、安全可靠、机械性能优良、相容性好、低挥发性有机化合物(VOCs)排放、易于改性等优点，符合环保、节能发展新理念，具有广阔的应用前景。', '印染行业水污染治理成套集成技术', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE035', '中国', '纺织', '交联盐析技术', '末端控制', '由于退浆废水中含有聚乙烯醇(PVA)、淀粉、羧甲基纤维素(CMC)和表面活性剂等难降解物质，COD浓度高、可生化性差，用单一的生化法难处理且耗时长，COD 去除效率一般不高。因此，退浆废水在处理前应尽量将 PVA 从废水中去除，盐析法操作简易，可去除废水中大部分 COD。若能从退浆废水中回收大部分 PVA，则在治理污染的同时可以变废为宝，既可以减少污染源又能获得一定的经济效益。', '盐析法处理棉退浆废水回收 PVA的效果很好，广泛应用于多个行业。在退浆废水中，除PVA 外还含有 CMC 及淀粉，故考虑可将废水中 PVA 回收用作黏合剂或其他领域中，具有较好的环境效益与经济效益。', '资源高效利用/水污染防治', '退浆废水/盐析法/PVA回收', null, null, null, null, '印染行业水污染治理成套集成技术', null);
INSERT INTO technology.Tech (NO, Country, Industry, CleanTechnology, ProductionStage, TechnologyOverview, Effect, Fields, Highlights, TypicalApplications, Cost, Stability, Innovation, Source, Comment) VALUES ('TE036', '中国', '纺织', '碱减量废水处理关键技术', '末端控制', '采用酸析法可回收碱减量废水中的对苯二甲酸，回收后的对苯二甲酸再经过提纯，可作为聚酯、电缆、除草剂等的生产原料。酸析法主要利用对苯二甲酸(TA)在酸性溶液中能沉淀析出的特点，在碱减量废水中加入酸，把pH值调至2~4，使TA析出结晶，实现与废水分离的一种方法。酸析法可实现废水中大部分对苯二甲酸的回收，使废水中的 COD 大幅度降低，同时操作简便，作为碱减量废水的预处理被广泛使用。', '碱减量废水经预处理回收对苯二甲酸后，不但实现了清洁生产，回收了可用资源，而且废水的 COD 值得到大幅度削减，使废水 COD 值从几万 mg/L 降到10000mg/L 以下，因此减轻了后续处理的负荷。', '资源高效利用/水污染防治', '碱减量废水/酸析法/TA回收', null, null, null, '碱减量废水的COD 值占印染废水总量的50%以上，而对苯二甲酸钠又占其中的75%， 所以碱减量废水经回收 TA后污水总 COD 值可以降低80%以上;更重要的是，混合印染废水在可生化性上发生了质的变化，使废水更加容易处理。从碱减量废水中回收TA给印染行业提供了有效治理污水的途径。', '印染行业水污染治理成套集成技术', null);
